Repository vimeo/psalm, pull requests merged in 2021-11, with the labels that each got.

#6790 detect Yield in new
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php
  tests/GeneratorTest.php
Labels: release:fix

#6793 emit UnevaluatedCode after exit or never returning functionlike
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ExitAnalyzer.php
  tests/BinaryOperationTest.php
  tests/ClassTest.php
  tests/Config/ConfigTest.php
  tests/EndToEnd/DestructiveAutoloaderTest.php
  tests/EndToEnd/SuicidalAutoloaderTest.php
  tests/MethodCallTest.php
  tests/MethodSignatureTest.php
  tests/Traits/InvalidCodeAnalysisTestTrait.php
  tests/Traits/ValidCodeAnalysisTestTrait.php
  tests/UnusedCodeTest.php
Labels: release:feature

#6768 Template support for @psalm-self-out
  docs/annotating_code/adding_assertions.md
  docs/annotating_code/supported_annotations.md
  src/Psalm/DocComment.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallReturnTypeFetcher.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php
  tests/DocumentationTest.php
  tests/IfThisIsTest.php
  tests/SelfOutTest.php
  tests/ThisOutTest.php
Labels: release:feature

#6801 accept ::class constant strings for literal argument
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  tests/FunctionCallTest.php
Labels: release:fix

#6802 Add pcntl_alarm to the list of impure functions
  src/Psalm/Internal/Codebase/Functions.php
Labels: release:fix

#6805 added mysqli::connect() to callmap
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#6811 Added 'Removed' section to release notes
  .github/release.yml
Labels: release:internal

#6815 add "error" from php-parser to baseline
  psalm-baseline.xml
Labels: release:fix

#6807 deprecate exitFunctions in XML
  config.xsd
  src/Psalm/Config.php
Labels: release:deprecation

#6816 Removed PHPUnit coverage badge
  README.md
Labels: release:docs

#6818 Improved Github Actions output
  src/Psalm/Report/GithubActionsReport.php
  tests/ReportOutputTest.php
Labels: release:fix

#6812 backticks shell_exec taint
  src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php
  tests/TaintTest.php
Labels: release:fix

#6810 Array cast pass taints
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  tests/TaintTest.php
Labels: release:fix

#6809 don't taint the result of most binary operations
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOpAnalyzer.php
  tests/TaintTest.php
Labels: release:fix

#6813 don't register taints for numeric variables
  src/Psalm/Internal/Analyzer/Statements/EchoAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  tests/TaintTest.php
Labels: release:fix

#6823 allow assertion to work on $var::class
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  tests/TypeReconciliation/ConditionalTest.php
Labels: release:fix

#6820 Fix parameter names in CoreGenericFunctions.phpstub for PHP 8 named p…
  stubs/CoreGenericFunctions.phpstub
Labels: release:fix

#6663 Allow Symfony 6
  composer.json
Labels: release:fix

#6828 allow declaring functions and classLikes after a never-returning call
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  tests/UnusedCodeTest.php
Labels: release:fix

#6824 Makes $_SESSION possibly undefined at the source
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
Labels: release:fix

#6825 create a tmp fake var for ternaries inside coalesce
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/CoalesceAnalyzer.php
  tests/BinaryOperationTest.php
Labels: release:fix

#6829 only return true in Union::is*Type* if there is a single type
  src/Psalm/Type/Union.php
Labels: release:fix

#6830 Mixed contain every types and Never is contained in every type
  src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php
Labels: release:fix

#6766 chore(ci): update psl version used in e2e tests
  bin/test-with-real-projects.sh
Labels: release:internal

#6833 add PSL back to CI
  .circleci/config.yml
Labels: release:internal

#6836 Forbid properties on enums
  .php-version
  config.xsd
  docs/running_psalm/issues/NoEnumProperties.md
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Issue/NoEnumProperties.php
  tests/DocumentationTest.php
Labels: release:feature, enum

#6838 better understands value and name properties for enum
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  src/Psalm/Type/Atomic/TEnumCase.php
  tests/EnumTest.php
Labels: release:feature

#6834 don't consider calls to methods with assertions as Unused
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallPurityAnalyzer.php
  tests/UnusedCodeTest.php
Labels: release:fix

#6839 Added test for NoEnumProperties
  .php-version
  tests/EnumTest.php
Labels: release:internal, enum

#6840 Forbid enum instantiation
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php
  tests/EnumTest.php
Labels: release:fix, enum

#6844 Added ext-curl to composer.json suggest property
  composer.json
Labels: release:docs

#6848 Taint comments
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php
  tests/TaintTest.php
Labels: release:fix

#6847 add stub for taint detection on vprintf
  stubs/CoreGenericFunctions.phpstub
Labels: release:fix

#6845 Added phpcs SelfMemberReference rule, and applied
  phpcs.xml
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/ScopeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ConstFetchAnalyzer.php
  src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  src/Psalm/Type.php
  src/Psalm/Type/Reconciler.php
  tests/TypeParseTest.php
Labels: release:internal

#6843 Forbid declaring enums as attributes
  src/Psalm/Internal/Analyzer/AttributeAnalyzer.php
  tests/EnumTest.php
Labels: release:fix

#6851 DOMParentNode and DOMChildNode stubs (php 8)
  dictionaries/PropertyMap.php
Labels: release:fix

#6852 Fixed signature for newInstanceArgs for PHP 8.0
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
Labels: release:fix

#6853 Fixed RedisCluster::setOption() argument types
  dictionaries/CallMap.php
  dictionaries/CallMap_74_delta.php
Labels: release:fix

#6856 Added option to forbid `eval()` in codebase
  src/Psalm/Internal/Analyzer/Statements/Expression/EvalAnalyzer.php
  tests/ForbiddenCodeTest.php
Labels: release:feature

#6846 Fixed callmap for function openssl_sign, it changed in PHP 8.0 (modif…
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
Labels: release:fix

#6861 Use positive integers for various time functions
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:feature

#6872 allow signature type for promoted property as well as property docblock
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  tests/AnnotationTest.php
Labels: release:fix

#6873 load the ReturnTypeWillChange stubs for all versions to allow using it on every PHP version
  stubs/CoreGenericClasses.phpstub
  stubs/Php81.phpstub
  tests/AttributeTest.php
Labels: release:fix

#6876 do not treat __halt_compiler() as an expression being executed
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  tests/UnusedCodeTest.php
Labels: release:fix

#6878 detect unevaluated inline-html code after an rearly return
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  tests/UnusedCodeTest.php
Labels: release:fix

#6880 Fix --enable-autocomplete=false
  src/Psalm/Internal/Cli/LanguageServer.php
Labels: release:fix

#6884 Flag duplicate constants
  config.xsd
  docs/running_psalm/issues.md
  docs/running_psalm/issues/DuplicateConstant.md
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Issue/DuplicateConstant.php
  tests/ConstantTest.php
Labels: release:feature

#6890 Add ImagickPixel::getColor return type provider
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  src/Psalm/Internal/Provider/MethodReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ImagickPixelColorReturnTypeProvider.php
Labels: release:feature

#6899 don't stop processing for class usage after raising an issue
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  tests/UnusedCodeTest.php
Labels: release:fix

#6903 SimpleXMLIterator is not always truthy
  src/Psalm/Type/Union.php
  tests/TypeReconciliation/ConditionalTest.php
  tests/TypeReconciliation/ReconcilerTest.php
Labels: release:fix

#6904 Fix typos in message about Attribute usage
  src/Psalm/Internal/Analyzer/AttributeAnalyzer.php
Labels: release:typo

#6895 make ignore falsable/nullable dependent on the config
  src/Psalm/Config.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  src/Psalm/Type/Atomic.php
Labels: release:fix

#6905 Fix invalid SoapClient::__doRequest() signature
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  stubs/soap.phpstub
Labels: release:fix

#6909 Fix promoted readonly properties
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  tests/ReadonlyPropertyTest.php
Labels: release:feature

#6910 Fix mb_convert_encoding to accept any array.
  dictionaries/CallMap.php
  dictionaries/CallMap_72_delta.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  stubs/CoreGenericFunctions.phpstub
Labels: release:fix

#6913 Report deprecated config elements
  src/Psalm/Config.php
  src/Psalm/Internal/PluginManager/ConfigFile.php
  tests/Config/ConfigFileTest.php
Labels: release:fix

#6912 Infer mb_strtolower() result as string when encoding is specified
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
  tests/FunctionCallTest.php
Labels: release:fix

#6850 ConsoleReport: Add hyperlinks to open file in editor
  src/Psalm/Internal/Analyzer/DataFlowNodeData.php
  src/Psalm/Issue/TaintedInput.php
  src/Psalm/Report/ConsoleReport.php
  tests/ReportOutputTest.php
Labels: release:feature

#6920 Multiple variables in @psalm-trace
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  src/Psalm/IssueBuffer.php
  tests/TraceTest.php
Labels: release:feature

#6922 Allow references to enum cases in class constants
  src/Psalm/Internal/Codebase/ClassLikes.php
  tests/ConstantTest.php
  tests/EnumTest.php
  tests/Traits/ValidCodeAnalysisTestTrait.php
Labels: release:fix, enum

#6932 session_set_cookie_params signature changed in 8.0
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#6529 Reconcile `class-constant`
  src/Psalm/Internal/Codebase/ClassConstantByWildcardResolver.php
  src/Psalm/Internal/Type/AssertionReconciler.php
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  src/Psalm/Type/Reconciler.php
  tests/AssertAnnotationTest.php
  tests/Internal/Codebase/ClassConstantByWildcardResolverTest.php
  tests/TypeReconciliation/ReconcilerTest.php
Labels: release:feature

#6946 expand type aliases when comparing unions
  src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php
  tests/TypeAnnotationTest.php
Labels: release:fix

#6949 Correct missing key-value for stream_get_meta_data function
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#6952 fix null propagation in return
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
Labels: release:fix

#6954 Update $data argument types of file_put_contents
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#6953 check __callStatic purity instead of the pseudoMethod purity
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  tests/PureAnnotationTest.php
Labels: release:fix

#6955 sleep(0) is valid
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#6961 usleep(0) is valid
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#6964 Make UnitEnum name property non-empty
  stubs/Php81.phpstub
Labels: release:feature

#6927 Invalid SoapClient::__doRequest() response type
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#6972 prevent Psalm from considering throwing methods as unused just because they're immutable
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallPurityAnalyzer.php
  tests/UnusedCodeTest.php
Labels: release:fix

#6963 Attempt to fix #6937
  src/Psalm/Internal/Analyzer/MethodComparator.php
  tests/ReturnTypeTest.php
Labels: release:fix

#6971 fix counting array properties when some are Never
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
  tests/TypeReconciliation/RedundantConditionTest.php
Labels: release:fix

#6974 Attempt fixing issue 6973
  src/Psalm/Internal/Analyzer/MethodComparator.php
  tests/ReturnTypeTest.php
Labels: release:fix

#6981 using lenght istead of count for php 7.1 compatibility
  src/Psalm/Config.php
Labels: release:fix

#6979 don't accept unresolved literal string as valid callable-strings
  src/Psalm/Internal/Type/Comparator/ScalarTypeComparator.php
  tests/CallableTest.php
  tests/TypeParseTest.php
Labels: release:fix

#6984 allow using EnumCase in an Attribute
  src/Psalm/Internal/Stubs/Generator/StubsGenerator.php
  tests/EnumTest.php
Labels: release:feature

#6986 Stub fixes for mysqli extension
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  dictionaries/PropertyMap.php
  src/Psalm/Config.php
  stubs/mysqli.phpstub
Labels: release:fix

#6993 Taint can't be transmitted through numerics nor bool
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  tests/TaintTest.php
Labels: release:fix

#7002 Disable list flag for TKeyedArray after unset
  src/Psalm/Internal/Analyzer/Statements/UnsetAnalyzer.php
  tests/ArrayAccessTest.php
Labels: release:fix

#7003 Use return type hints instead of php doc "@return void"
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Plugin/EventHandler/Event/AfterClassLikeVisitEvent.php
  tests/BinaryOperationTest.php
  tests/ClassTest.php
  tests/Config/ConfigTest.php
  tests/ErrorBaselineTest.php
  tests/MethodCallTest.php
  tests/MethodSignatureTest.php
  tests/Traits/InvalidCodeAnalysisTestTrait.php
  tests/Traits/ValidCodeAnalysisTestTrait.php
Labels: release:internal

#7005 Make test runnable on plain windows
  composer.json
Labels: release:internal

#7004 Drop unused $fq_classlike_names property
  src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php
Labels: release:internal

#7006 Display target PHP version
  src/Psalm/Codebase.php
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Cli/Psalter.php
  src/Psalm/Internal/CliUtils.php
  tests/Config/ConfigTest.php
  tests/DocumentationTest.php
  tests/EndToEnd/PsalmEndToEndTest.php
  tests/FileManipulation/FileManipulationTestCase.php
  tests/FileReferenceTest.php
  tests/FileUpdates/AnalyzedMethodTest.php
  tests/FileUpdates/CachedStorageTest.php
  tests/FileUpdates/ErrorAfterUpdateTest.php
  tests/FileUpdates/ErrorFixTest.php
  tests/FileUpdates/TemporaryUpdateTest.php
  tests/ForbiddenCodeTest.php
  tests/LanguageServer/CompletionTest.php
  tests/LanguageServer/FileMapTest.php
  tests/LanguageServer/SymbolLookupTest.php
  tests/MethodSignatureTest.php
  tests/ProjectCheckerTest.php
  tests/StubTest.php
  tests/TestCase.php
  tests/Traits/InvalidCodeAnalysisTestTrait.php
  tests/Traits/ValidCodeAnalysisTestTrait.php
  tests/TypeReconciliation/ValueTest.php
  tests/UnusedCodeTest.php
  tests/UnusedVariableTest.php
  tests/VariadicTest.php
  tests/fixtures/DummyProjectWithErrors/composer.json
Labels: enhancement, release:feature

#6995 Drop special handling of constant references on enums
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ClassConstFetchAnalyzer.php
  tests/EnumTest.php
Labels: release:fix, enum

#4160 Colorized file name and line in console output
  src/Psalm/Report/ConsoleReport.php
  tests/ReportOutputTest.php
Labels: release:feature

#7008 Fix signatures of gmstrftime and strftime
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#7009 Fix failing symlink test on Windows
  tests/Config/ConfigTest.php
Labels: release:internal

#7010 Include enum cases in const wildcards
  src/Psalm/Internal/Type/TypeExpander.php
  tests/EnumTest.php
Labels: release:fix

#7011 Infer `::from()` and `::tryFrom()` return types on backed enums
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Codebase/Methods.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  stubs/Php81.phpstub
  tests/EnumTest.php
Labels: release:feature

#7012 Added enum-related stubs and callmaps
  dictionaries/CallMap.php
  dictionaries/CallMap_81_delta.php
  stubs/Php81.phpstub
Labels: release:feature

#7013 Allow overriding the signature type by a param docblock for promoted properties
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  tests/AnnotationTest.php
Labels: release:fix

#6997 Raise RedundantCast when using array_values on a list (fixes #6988)
  src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NamedFunctionCallHandler.php
  src/Psalm/Internal/Analyzer/Statements/Expression/MatchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/TernaryAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/UnsetAnalyzer.php
  src/Psalm/Internal/Fork/Pool.php
  tests/ArrayAssignmentTest.php
  tests/ReportOutputTest.php
  tests/Template/ClassTemplateTest.php
Labels: release:feature

#7014 Fix mysqli_fetch_* stubs
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  stubs/mysqli.phpstub
Labels: release:fix

#7016 Escape GHA output
  src/Psalm/Report/GithubActionsReport.php
Labels: release:fix

#6987 fix signature for openssl_open under PHP >= 8.0
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
Labels: release:fix

#7017 Disabled coverage (and xdebug) for CI builds
  .github/workflows/build-phar.yml
  .github/workflows/ci.yml
  .github/workflows/windows-ci.yml
Labels: release:internal

#7021 Add tests for UnresolvableInclude
  tests/UnresolvableIncludeTest.php
Labels: release:internal

#7023 refine abs return type
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#7024 Add --php-version to CLI help
  src/Psalm/Internal/CliUtils.php
Labels: release:internal

#7025 flag DeprecatedProperty on static fetch
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/StaticPropertyFetchAnalyzer.php
  tests/DeprecatedAnnotationTest.php
Labels: release:fix

#7022 remove the remaining dynamic property assignment
  src/Psalm/Internal/PhpVisitor/SimpleNameResolver.php
  tests/CodebaseTest.php
Labels: release:fix

#7031 Prevent VoidProgress from outputting anything
  src/Psalm/Progress/VoidProgress.php
Labels: release:internal

#7033 ignore irrelevant errors for php-parser 4.13.2
  psalm-baseline.xml
  src/Psalm/Node/Stmt/VirtualFunction.php
  src/Psalm/Node/VirtualConst.php
Labels: release:fix

#7032 refine getdate array structure
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:feature

#7027 Improved `preg_match()` output param type inference
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  src/Psalm/CodeLocation.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeDocblockParser.php
  stubs/CoreGenericFunctions.phpstub
  tests/FunctionCallTest.php
  tests/Traits/ValidCodeAnalysisTestTrait.php
Labels: release:feature

#7029 Enhancing composer scripts
  composer.json
  docs/contributing/index.md
Labels: release:internal
