Repository vimeo/psalm, pull requests merged in 2021-10, with the labels that each got.

#6566 Convert finfo functions to use object instead of a resource
  dictionaries/CallMap.php
  dictionaries/CallMap_81_delta.php
Labels: hacktoberfest-accepted

#6567 Convert imap functions to use object instead of a resource
  dictionaries/CallMap.php
  dictionaries/CallMap_81_delta.php
  stubs/Php81.phpstub
Labels: hacktoberfest-accepted

#6570 Convert LDAP resources to objects
  dictionaries/CallMap.php
  dictionaries/CallMap_81_delta.php
  stubs/Php81.phpstub
Labels: hacktoberfest-accepted

#6569 Convert PSpell resources to objects
  dictionaries/CallMap.php
  dictionaries/CallMap_81_delta.php
  stubs/Php81.phpstub
Labels: hacktoberfest-accepted

#6784 Ability to forbid `exit()` and `die()`
  src/Psalm/Internal/Analyzer/Statements/Expression/ExitAnalyzer.php
  tests/Config/ConfigTest.php
  tests/ForbiddenCodeTest.php
Labels: release:feature

#6785 Require one of `release:*` labels on PRs
  .github/workflows/pr-labels.yml
Labels: release:internal
