Repository vimeo/psalm, pull requests merged in 2021-12, with the labels that each got.

#7036 Throw exception when baseline file is empty
  src/Psalm/ErrorBaseline.php
Labels: release:fix

#7040 document the behavior of methods in IssueBuffer
  src/Psalm/IssueBuffer.php
Labels: release:docs

#7041 Beautified phpcs.xml
  phpcs.xml
Labels: release:internal

#7043 flag usage of get_class outside class without args
  src/Psalm/Context.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  tests/FunctionCallTest.php
Labels: release:feature

#7030 Fix RedisCluster::getOption() and RedisCluster::setOption() argument types
  dictionaries/CallMap.php
  dictionaries/CallMap_74_delta.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#7042 get_class does not return false
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#7045 Consider emptiness for array_count_values()
  stubs/CoreGenericFunctions.phpstub
Labels: release:fix

#7056 Remove always-false args
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
Labels: release:internal

#7049 Don't output console links in CI env
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/CliUtils.php
  src/Psalm/Report.php
  src/Psalm/Report/ConsoleReport.php
  src/Psalm/Report/ReportOptions.php
  tests/EndToEnd/PsalmRunnerTrait.php
  tests/ReportOutputTest.php
Labels: release:fix

#7059 Improve count_chars stub
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
Labels: release:feature

#7063 Refined `*strlen()` return type to exclude negative integers
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
Labels: release:feature

#7070 Fix #6968: PHP_INT_MAX isn't positive
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ConstFetchAnalyzer.php
Labels: release:feature

#7068 Detect yield in array expression
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php
  tests/GeneratorTest.php
Labels: release:feature

#7073 Refined `strlen()` return type to not include negative ints
  stubs/CoreGenericFunctions.phpstub
Labels: release:fix

#7077 Make name property of enum cases return non-empty-strings
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  tests/EnumTest.php
Labels: release:fix

#7084 Don't crash when checking purity of __callStatic in a trait
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  tests/PureAnnotationTest.php
Labels: release:fix

#7076 Fixed generic assertions for list and array
  src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php
  src/Psalm/Storage/Assertion.php
  tests/Template/FunctionTemplateAssertTest.php
Labels: release:fix

#7089 abs should always return a positive integer
  stubs/CoreGenericFunctions.phpstub
  tests/FunctionCallTest.php
Labels: release:fix

#7064 Updated list of current maintainers
  README.md
Labels: release:docs

#7097 Remove useless chunk of code in ScopeAnalyzer
  src/Psalm/Internal/Analyzer/ScopeAnalyzer.php
Labels: release:internal

#7105 Fix non-empty-literal-string to behave as subtype of non-empty-string (fixes #7095).
  src/Psalm/Internal/Type/TypeCombiner.php
  tests/TypeCombinationTest.php
Labels: release:fix

#7103 Allow operator overloading for Decimal extension (fixes #3938).
  .github/workflows/ci.yml
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ArithmeticOpAnalyzer.php
  stubs/decimal.phpstub
  tests/BinaryOperationTest.php
Labels: release:feature

#7106 fix reconciliation between positive-int and inferior/superior assertions
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  src/Psalm/Type/Atomic/TIntRange.php
  src/Psalm/Type/Union.php
  tests/IntRangeTest.php
Labels: release:fix

#7093 don't stop analyzing array, even if we already have a type and we can't create an object like
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
  tests/ArrayAssignmentTest.php
Labels: release:fix

#7094 Fix count_chars stubs
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  tests/FunctionCallTest.php
Labels: release:feature

#7054 fix missing case for displaying varId
  src/Psalm/Internal/Analyzer/Statements/Expression/ExpressionIdentifier.php
  src/Psalm/Type/Reconciler.php
Labels: release:fix

#7115 array_count_values return type for uncertain arrays
  stubs/CoreGenericFunctions.phpstub
Labels: release:fix

#7113 Added support for first-class callables
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallReturnTypeFetcher.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NamedFunctionCallHandler.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  src/Psalm/Internal/Provider/AddRemoveTaints/HtmlFunctionTainter.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ClosureFromCallableReturnTypeProvider.php
  tests/ClosureTest.php
Labels: release:feature

#7129 Detect unused properties that are written to inside arrays
  src/Psalm/Codebase.php
  src/Psalm/Context.php
  src/Psalm/Internal/Analyzer/CanAlias.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
  src/Psalm/Internal/Scope/IfScope.php
  src/Psalm/Storage/ClassConstantStorage.php
  src/Psalm/Storage/FunctionLikeStorage.php
  tests/UnusedCodeTest.php
Labels: release:fix

#7130 Class property issue suppression fixes.
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/CommentAnalyzer.php
  src/Psalm/Internal/Codebase/ClassLikes.php
  tests/IssueSuppressionTest.php
Labels: release:fix

#7134 Use getSingleAtomic() instead of array_values(getAtomicTypes())[0].
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/ArrayAssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NamedFunctionCallHandler.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ClassConstFetchAnalyzer.php
  src/Psalm/Internal/Codebase/ConstantTypeResolver.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/MinMaxReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/RandReturnTypeProvider.php
  src/Psalm/Internal/Type/AssertionReconciler.php
  src/Psalm/Internal/Type/Comparator/ScalarTypeComparator.php
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
  src/Psalm/Internal/Type/TemplateInferredTypeReplacer.php
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Storage/Assertion.php
  src/Psalm/Type/Union.php
  tests/TypeCombinationTest.php
Labels: release:internal

#7137 fix some more expressions that can be replaced by getSingleAtomic
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  src/Psalm/Internal/Analyzer/Statements/ReturnAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/TypeHintResolver.php
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  src/Psalm/Internal/Type/TypeParser.php
Labels: release:internal

#7135 Fix type inference of closure params
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  tests/CallableTest.php
  tests/FunctionCallTest.php
Labels: release:fix

#7082 Fix parser cache files maintenance
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Internal/Provider/ParserCacheProvider.php
  src/Psalm/IssueBuffer.php
Labels: release:internal

#7133 Allow suppressing UnusedPsalmSuppress, remove unused suppressions.
  psalm.xml.dist
  src/Psalm/CodeLocation.php
  src/Psalm/Config.php
  src/Psalm/Config/Creator.php
  src/Psalm/FileBasedPluginAdapter.php
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  src/Psalm/Internal/CliUtils.php
  src/Psalm/Internal/Codebase/InternalCallMapHandler.php
  src/Psalm/Internal/Codebase/Reflection.php
  src/Psalm/Internal/Fork/Pool.php
  src/Psalm/Internal/LanguageServer/LanguageServer.php
  src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php
  src/Psalm/Internal/PhpVisitor/CheckTrivialExprVisitor.php
  src/Psalm/Internal/PhpVisitor/OffsetShifterVisitor.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeDocblockParser.php
  src/Psalm/Internal/Provider/FakeFileProvider.php
  src/Psalm/Internal/Provider/ParserCacheProvider.php
  src/Psalm/Internal/Provider/StatementsProvider.php
  src/Psalm/Internal/Type/TypeTokenizer.php
  tests/IssueSuppressionTest.php
  tests/TestConfig.php
Labels: release:feature

#7136 Forbid positional arg after named arg
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  tests/ArgTest.php
Labels: release:feature

#7139 Fix closure param type inference with named params
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  tests/CallableTest.php
Labels: release:fix

#7143 Post-assertions in loops
  src/Psalm/Issue/CodeIssue.php
  src/Psalm/IssueBuffer.php
  tests/Loop/ForeachTest.php
Labels: release:fix

#7141 in_array returns false in strict mode if types are incompatibles
  src/Psalm/Internal/Provider/FunctionReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/InArrayReturnTypeProvider.php
  src/Psalm/Internal/Type/TypeCombiner.php
  tests/ReturnTypeProvider/InArrayTest.php
  tests/TypeReconciliation/InArrayTest.php
Labels: release:feature

#7150 "No errors found!" message is now printed within a nice green block
  src/Psalm/IssueBuffer.php
  tests/IssueBufferTest.php
Labels: release:feature

#7162 Use igbinary for communication between processes if possible
  src/Psalm/Internal/Codebase/Analyzer.php
  src/Psalm/Internal/Codebase/Scanner.php
  src/Psalm/Internal/Fork/Pool.php
Labels: release:feature

#7153 fix CI
  dictionaries/CallMap.php
  dictionaries/CallMap_81_delta.php
  stubs/Reflection.phpstub
Labels: release:fix

#7159 Fix optional arguments in number_format (fixes #7158).
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  tests/FunctionCallTest.php
Labels: release:fix

#7156 Add Set::map() to ext-ds stub
  stubs/ext-ds.phpstub
Labels: release:feature

#7145 Fix ldap_set_rebind_proc signature
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#7149 Set allow-plugins for Composer 2.2
  composer.json
Labels: release:internal

#7140 Fixed compatibility with SoapClient
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  dictionaries/PropertyMap.php
  stubs/soap.phpstub
Labels: release:fix

#7152 display class-strings in keyed arrays syntax and allow using them for assertions
  src/Psalm/Internal/Type/ParseTreeCreator.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  tests/AssertAnnotationTest.php
Labels: release:fix

#7157 ISSUE-5962 Fixed wrong line number for @method annotations
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeDocblockParser.php
  tests/AnnotationTest.php
Labels: release:fix

#7167 Fix conflicting array_map return provider fake variables.
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayFilterReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMapReturnTypeProvider.php
  tests/ReturnTypeTest.php
Labels: release:fix

#7168 Remove superflous exclude pattern in phpcs.xml
  phpcs.xml
Labels: release:internal

#7175 Fix faulty comparison with typed closure
  src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php
  tests/ClosureTest.php
Labels: release:fix

#7180 doesn't infer empty for ReflectionClass::getAttributes without params
  stubs/Reflection.phpstub
  tests/AttributeTest.php
Labels: release:fix

#7182 Fixed ignoreTypeStats & useStrictTypes flag value detection for directories in config
  src/Psalm/Config/FileFilter.php
  tests/Config/ConfigTest.php
Labels: release:fix

#7183 Removed misleading parentheses after language construct
  docs/running_psalm/issues/UnresolvableInclude.md
Labels: release:internal

#7189 fix #7178 again
  stubs/Reflection.phpstub
  tests/AttributeTest.php
Labels: release:fix

#7190 fix other occurences of getAttributes
  stubs/Reflection.phpstub
Labels: release:fix

#7186 MySqli: some parameters are nullable
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#7193 allow destructuring on a possible null variable as long as there is an array alongside
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  tests/ArrayAssignmentTest.php
Labels: release:fix

#7194 Added pure annotations to enum functions
  stubs/Php81.phpstub
Labels: release:fix

#7197 fix(stubs): UnitEnum::cases() can return an empty list
  stubs/Php81.phpstub
Labels: release:fix

#7195 fix wrong handling of flags in context
  src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfConditionalAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/SwitchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/SwitchCaseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/ArrayAssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/StaticPropertyAssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArrayFunctionArgumentsAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ClassConstFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/InstancePropertyFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/IncDecExpressionAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/IncludeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/InstanceofAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/YieldFromAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php
  src/Psalm/Internal/Codebase/Methods.php
Labels: release:internal

#7161 Improve project files discovery performance
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Internal/Provider/FakeFileProvider.php
  src/Psalm/Internal/Provider/FileProvider.php
Labels: release:feature

#7192 allow marking enum cases as deprecated
  docs/running_psalm/issues/DeprecatedConstant.md
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ClassConstFetchAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Storage/EnumCaseStorage.php
  tests/DeprecatedAnnotationTest.php
  tests/DocumentationTest.php
  tests/EnumTest.php
Labels: release:feature

#7205 allow phpcodesniffer-composer-installer plugin
  composer.json
Labels: release:internal

#7208 Workaround for PHPUnit process isolation issue with composer 2.2
  bin/tests-github-actions.sh
Labels: release:internal

#7202 Remove unused in-array assertions
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Type/Reconciler.php
Labels: release:internal

#7201 Add early file filtering to `FileProvider::getFilesInDir()`
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Internal/Provider/FakeFileProvider.php
  src/Psalm/Internal/Provider/FileProvider.php
Labels: release:fix

#7203 flag the context as "inside_conditional" when analyzing leftover cases to prevent emitting unused error
  src/Psalm/Internal/Analyzer/Statements/Block/SwitchCaseAnalyzer.php
  tests/SwitchTypeTest.php
Labels: release:fix

#7217 Restore attributes in ClassConstantStorage
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Storage/ClassConstantStorage.php
Labels: release:fix

#7220 Use `strpos` instead of `str_contains`
  bin/test-with-real-projects.sh
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMapReturnTypeProvider.php
  vendor-bin/box/composer.json
Labels: release:fix

#7225 quote more chars in keyed array names
  src/Psalm/Type/Atomic/TKeyedArray.php
  tests/AssertAnnotationTest.php
Labels: release:fix

#7224 handle literal equality with integer ranges
  src/Psalm/Internal/Type/AssertionReconciler.php
  tests/IntRangeTest.php
Labels: release:fix

#7211 Allow XdebugHandler version 3
  composer.json
  src/Psalm/Internal/Fork/PsalmRestarter.php
Labels: release:fix

#7210 Improve CliUtils $argv handling
  src/Psalm/Internal/CliUtils.php
  tests/Internal/CliUtilsTest.php
Labels: release:fix

#7200 Fix closure param type inference in generic context
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  tests/CallableTest.php
Labels: release:fix

#7207 Fix @psalm-internal with trailing whitespaces
  src/Psalm/Internal/Analyzer/CommentAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeDocblockParser.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php
  tests/InternalAnnotationTest.php
Labels: release:fix

#7215 add missing samesite array attribute
  dictionaries/CallMap.php
  dictionaries/CallMap_73_delta.php
Labels: release:fix

#7228 Contextual inference for closure param types
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  tests/CallableTest.php
Labels: release:fix

#7229 remove always true/false conditions
  src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/NonComparisonOpAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMapReturnTypeProvider.php
  src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php
  src/Psalm/Internal/Type/Comparator/ScalarTypeComparator.php
  src/Psalm/Internal/Type/TypeCombiner.php
  src/Psalm/Type/Reconciler.php
  tests/TestCase.php
Labels: release:internal

#7230 code grooming
  dictionaries/scripts/update_signaturemap_from_other_tool.php
  examples/TemplateChecker.php
  examples/TemplateScanner.php
  examples/plugins/ClassUnqualifier.php
  examples/plugins/FunctionCasingChecker.php
  examples/plugins/PreventFloatAssignmentChecker.php
  examples/plugins/StringChecker.php
  examples/plugins/composer-based/echo-checker/EchoChecker.php
  psalm
  psalm-language-server
  psalm-plugin
  psalm-refactor
  psalter
  scoper.inc.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallReturnTypeFetcher.php
  src/Psalm/Internal/Cli/LanguageServer.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Cli/Psalter.php
  src/Psalm/Internal/Cli/Refactor.php
  src/Psalm/Internal/Stubs/Generator/ClassLikeStubGenerator.php
  src/Psalm/Internal/Stubs/Generator/StubsGenerator.php
  src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  src/Psalm/Issue/IfThisIsMismatch.php
Labels: release:internal

#7233 more code grooming
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  src/Psalm/Internal/Codebase/ClassLikes.php
  src/Psalm/Internal/ExecutionEnvironment/BuildInfoCollector.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMapReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/FilterVarReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/RandReturnTypeProvider.php
  src/Psalm/Internal/Scanner/DocblockParser.php
  src/Psalm/Internal/Type/ParseTreeCreator.php
  src/Psalm/Internal/Type/TypeCombiner.php
Labels: release:internal

#7236 allow suppressing unevaluatedCode
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  tests/IssueSuppressionTest.php
Labels: release:fix

#7240 mysqli_fetch_object: added missing generic
  stubs/mysqli.phpstub
Labels: release:fix

#7232 Fix first-class callables with built-in, magic, undefined methods and callable expressions
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallReturnTypeFetcher.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MissingMethodCallHandler.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ExpressionIdentifier.php
  tests/ClosureTest.php
Labels: release:feature

#7245 Speed up Windows tests
  .github/workflows/windows-ci.yml
  bin/generate_testsuites.php
Labels: release:internal

#7251 Checking `psalm-if-this-is` before applying `psalm-this-out`
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php
  tests/IfThisIsTest.php
Labels: release:fix

#7253 allow calling mutation_free function inside a mutation_free context
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  tests/ImmutableAnnotationTest.php
Labels: release:fix
