Repository vimeo/psalm, pull requests merged in 2022-06, with the labels that each got.

#8042 Bugfix/splfileobject fputcsv invalidnamedargument
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#8055 Performance: cut the selected_text from snippet
  src/Psalm/CodeLocation.php
Labels: release:internal

#8054 store origin location by ID to speed up psalm by up to 75%
  src/Psalm/Internal/Codebase/VariableUseGraph.php
Labels: release:internal

#8058 Bring back disableVarParsing option
  config.xsd
Labels: release:fix

#8060 Clarify in docs that zero is not considered a positive-int
  docs/annotating_code/type_syntax/scalar_types.md
Labels: release:docs, PR: Need review

#8064 Coerce null to empty string in array keys
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  tests/ArrayAssignmentTest.php
Labels: release:fix

#8069 Fix generic object comparison to use template constraint as default.
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  src/Psalm/Internal/Type/Comparator/GenericTypeComparator.php
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  src/Psalm/Storage/ClassLikeStorage.php
  tests/Template/ClassTemplateExtendsTest.php
  tests/Template/FunctionClassStringTemplateTest.php
Labels: release:fix

#8080 Skip native classlike aliases
  src/Psalm/Internal/Codebase/ClassLikes.php
Labels: release:fix

#8100 fix #8099: ob_implicit_flush argument type changed to bool
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
Labels: release:fix

#8098 Fix nasty parameter storage corruption bug
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
Labels: release:fix

#8102 Change return type of createFromInterface() on DateTime and DateTimeImmutable to static
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  tests/MethodCallTest.php
Labels: release:fix

#8114 number_format: allow third and forth parameters to be nullable
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#8117 Add ReflectionClass & ReflectionObject::isEnum()
  dictionaries/CallMap.php
  dictionaries/CallMap_81_delta.php
Labels: release:fix

#8126 Add missing ldap_unbind mapping for php 8.1
  dictionaries/CallMap.php
  dictionaries/CallMap_81_delta.php
Labels: release:fix

#8135 PossiblyNullArgument: Adding common problem cases and possible solutions
  docs/running_psalm/issues/PossiblyNullArgument.md
Labels: release:docs

#8147 Fix signatures of ldap_* functions
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_81_delta.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#8153 Fix datefmt_* function signatures
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#8152 Fix filter_var and filter_var_array signatures
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#8151 Fix array_* function signatures
  dictionaries/CallMap.php
  dictionaries/CallMap_73_delta.php
  dictionaries/CallMap_74_delta.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#8148 Add ReflectionProperty properties
  dictionaries/PropertyMap.php
  src/Psalm/Internal/Codebase/Reflection.php
Labels: release:fix

#8155 Run method call prohibition analyzer when cloning
  src/Psalm/Internal/Analyzer/Statements/Expression/CloneAnalyzer.php
  tests/DeprecatedAnnotationTest.php
  tests/InternalAnnotationTest.php
Labels: release:internal

#8165 Improve @psalm-internal and prevent usage of IssueBuffer::add().
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/CommentAnalyzer.php
  src/Psalm/Internal/Analyzer/FileAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/InterfaceAnalyzer.php
  src/Psalm/Internal/Analyzer/NamespaceAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/InstancePropertyAssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallProhibitionAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/ExistingAtomicStaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ClassConstFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  src/Psalm/Internal/Codebase/Populator.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeDocblockParser.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  src/Psalm/Internal/Provider/StatementsProvider.php
  src/Psalm/Internal/Scanner/ClassLikeDocblockComment.php
  src/Psalm/Internal/Scanner/DocblockParser.php
  src/Psalm/Internal/Scanner/FunctionDocblockComment.php
  src/Psalm/Internal/Scanner/VarDocblockComment.php
  src/Psalm/Issue/InternalClass.php
  src/Psalm/IssueBuffer.php
  src/Psalm/Storage/ClassLikeStorage.php
  src/Psalm/Storage/FunctionLikeStorage.php
  src/Psalm/Storage/PropertyStorage.php
  tests/InternalAnnotationTest.php
Labels: release:feature

#8164 Encapsed literal strings
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/EncapsulatedStringAnalyzer.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/FilterVarReturnTypeProvider.php
  src/Psalm/Type/Atomic/TFalse.php
  src/Psalm/Type/Atomic/TTrue.php
  src/Psalm/Type/Union.php
  tests/BinaryOperationTest.php
  tests/TypeReconciliation/EmptyTest.php
Labels: release:feature

#8174 Fix crash when redefining method with fewer params (fixes #8141).
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  tests/AttributeTest.php
Labels: release:fix

#8181 Avoid re-parsing template types
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
Labels: release:internal

#8077 Feature: allow non-union assertion types
  src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php
  src/Psalm/Type/Atomic/TLiteralFloat.php
  src/Psalm/Type/Atomic/TLiteralInt.php
  src/Psalm/Type/Atomic/TLiteralString.php
  src/Psalm/Type/Union.php
  tests/AssertAnnotationTest.php
Labels: release:feature

#8191 Fix namespace of test
  tests/Template/PropertiesOfTemplateTest.php
Labels: release:internal

#8193 Various minor improvements to speed up by ~10%
  src/Psalm/Internal/Algebra.php
  src/Psalm/Internal/Clause.php
  src/Psalm/Internal/Provider/ClassLikeStorageCacheProvider.php
  src/Psalm/Internal/Provider/FileStorageCacheProvider.php
Labels: release:internal

#8203 chore: Included githubactions in the dependabot config
  .github/dependabot.yml
Labels: release:internal
