Repository vimeo/psalm, pull requests merged in 2022-05, with the labels that each got.

#7951 fix missing is_a() parameter type
  stubs/CoreGenericFunctions.phpstub
Labels: release:fix

#7935 Infer object shape when array or scalar is cast to object
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  src/Psalm/Type/Atomic.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  src/Psalm/Type/Atomic/TList.php
  tests/ArgTest.php
  tests/ReturnTypeProvider/GetObjectVarsTest.php
  tests/ReturnTypeTest.php
Labels: release:feature

#7967 Improve @return annotation for implode() so that it can handle non-empty-array of non-empty-strings case
  stubs/CoreGenericFunctions.phpstub
  tests/ArrayFunctionCallTest.php
Labels: release:feature

#7982 Bugfix/#7912 class APCuIterator does not exist
  src/Psalm/Config.php
  stubs/ext-apcu.phpstub
Labels: release:feature

#7992 Fix class const issue when using floats declared in future consts (fixes #7973).
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ArithmeticOpAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ClassConstAnalyzer.php
  tests/BinaryOperationTest.php
  tests/ConstantTest.php
Labels: release:fix

#7981 Improve array_unique callmap stubs
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#8007 igbinary_serialize code was missing in file
  src/Psalm/Internal/Provider/FileReferenceCacheProvider.php
Labels: release:internal

#8011 Performance only load files once
  src/Psalm/Internal/Provider/FakeFileProvider.php
  src/Psalm/Internal/Provider/FileProvider.php
Labels: release:internal

#8023 Fix a typo in MissingConstructor.md
  docs/running_psalm/issues/MissingConstructor.md
Labels: release:docs

#8022 Improve handling of unsupported references (fixes #8018).
  config.xsd
  docs/running_psalm/issues.md
  docs/running_psalm/issues/UnsupportedReferenceUsage.md
  src/Psalm/Context.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/GlobalAnalyzer.php
  src/Psalm/Issue/UnsupportedReferenceUsage.php
  tests/ReferenceTest.php
Labels: release:fix

#8028 Fix syntax check failures
  .github/workflows/ci.yml
Labels: release:internal

#8024 Update master
  .github/workflows/shepherd.yml
  composer.json
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  src/Psalm/Internal/Cli/Plugin.php
  src/Psalm/Internal/Codebase/Reflection.php
  src/Psalm/Internal/LanguageServer/LanguageServer.php
  src/Psalm/Internal/LanguageServer/Server/TextDocument.php
  src/Psalm/Internal/PluginManager/Command/DisableCommand.php
  src/Psalm/Internal/PluginManager/Command/EnableCommand.php
  src/Psalm/Internal/PluginManager/Command/ShowCommand.php
  src/Psalm/Internal/Provider/ClassLikeStorageCacheProvider.php
  src/Psalm/Internal/Provider/FakeFileProvider.php
  src/Psalm/Internal/Provider/FileProvider.php
  src/Psalm/Internal/Provider/FileReferenceCacheProvider.php
  src/Psalm/Internal/Provider/FileStorageCacheProvider.php
  src/Psalm/Internal/Provider/ProjectCacheProvider.php
  src/Psalm/Internal/Type/TypeParser.php
  stubs/CoreGenericFunctions.phpstub
  stubs/ext-apcu.phpstub
  tests/ArgTest.php
  tests/ArrayFunctionCallTest.php
  tests/ReturnTypeProvider/GetObjectVarsTest.php
  tests/ReturnTypeTest.php
  tests/Template/ClassTemplateTest.php
  tests/Template/FunctionTemplateTest.php
Labels: release:internal

#8027 Backport #7506
  src/Psalm/Config.php
Labels: release:internal

#8029 Run Shepherd with 8.0
  .github/workflows/shepherd.yml
Labels: release:internal

#8032 Precise stat return type
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix
