Repository vimeo/psalm, pull requests merged in 2022-08, with the labels that each got.

#8364 add ", but" for InvalidArgument error message where a type is provided
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArrayFunctionArgumentsAnalyzer.php
  tests/ClosureTest.php
  tests/ReturnTypeTest.php
  tests/Template/ClassTemplateTest.php
  tests/TypeReconciliation/TypeTest.php
  tests/UnusedVariableTest.php
Labels: release:typo

#8360 Add BitwiseNot and BooleanNot operators to SimpleTypeInferer
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  tests/ConstantTest.php
Labels: release:fix

#8350 Added better stubs for `DateTimeImmutable`, highlighting how the constructor is **NOT** immutable
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  stubs/CoreImmutableClasses.phpstub
  tests/MethodCallTest.php
Labels: release:fix

#8376 Use classlike_storage_provider only if it has the required data
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  tests/Template/ClassTemplateTest.php
Labels: release:fix

#8400 added truthy-string alias for non-falsy-string
  src/Psalm/Type/Atomic.php
  tests/TypeCombinationTest.php
Labels: release:feature

#8372 always use lock when writing/reading cache data to/from file
  src/Psalm/Internal/Provider/ClassLikeStorageCacheProvider.php
  src/Psalm/Internal/Provider/FileReferenceCacheProvider.php
  src/Psalm/Internal/Provider/FileStorageCacheProvider.php
  src/Psalm/Internal/Provider/ParserCacheProvider.php
  src/Psalm/Internal/Provider/Providers.php
Labels: release:internal

#8402 Add capability to use inclusion files in a different directory (fix)
  config.xsd
Labels: release:feature

#8403 Fix `imageinterlace` function signature
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_81_delta.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#8405 Clarification of `Reflection::getModifierNames()` result type
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#8408 Adding note about referencedMethod
  docs/running_psalm/dealing_with_code_issues.md
Labels: release:docs

#8418 fix: Fix template resolution of complex extended types
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ClassTemplateParamCollector.php
  tests/Template/ClassTemplateTest.php
Labels: release:fix

#8370 Ensure we recognize inherited static methods for the first-class callables
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  tests/ClosureTest.php
Labels: release:fix

#8424 Fix doc typos
  docs/annotating_code/supported_annotations.md
  docs/annotating_code/templated_annotations.md
  docs/annotating_code/type_syntax/scalar_types.md
  docs/contributing/editing_callmaps.md
  docs/contributing/how_psalm_works.md
  docs/contributing/philosophy.md
  docs/manipulating_code/refactoring.md
  docs/running_psalm/installation.md
  docs/running_psalm/issues/FalsableReturnStatement.md
  docs/running_psalm/issues/InvalidExtendClass.md
  docs/running_psalm/issues/PropertyTypeCoercion.md
  docs/running_psalm/issues/TaintedCallable.md
  docs/running_psalm/issues/TaintedLdap.md
  docs/running_psalm/issues/TaintedTextWithQuotes.md
  docs/running_psalm/plugins/authoring_plugins.md
Labels: release:typo

#8427 added SensitiveParameter, AllowDynamicProperties php 8.2 attributes
  stubs/CoreGenericClasses.phpstub
  tests/AttributeTest.php
Labels: release:feature

#8431 Allow *bin2hex and *bin2base64 functions to keep non-empty-string type
  stubs/CoreGenericFunctions.phpstub
Labels: release:feature

#8435 Add support for callable in array_reduce
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayReduceReturnTypeProvider.php
  tests/ClosureTest.php
Labels: release:fix

#8436 Configure a correct attribute target in stubs/CoreGenericClasses.phpstub
  stubs/CoreGenericClasses.phpstub
  tests/AttributeTest.php
Labels: release:fix

#8428 Allow any attribute for complex types in schema
  config.xsd
Labels: release:feature

#8444 trim(), ltrim(), rtrim() now keep lowercase string attribute
  stubs/CoreGenericFunctions.phpstub
  tests/FunctionCallTest.php
Labels: release:feature
