Repository vimeo/psalm, pull requests merged in 2022-04, with the labels that each got.

#7828 Psalm considers most readline functions as pure, but they have side effects
  src/Psalm/Internal/Codebase/Functions.php
Labels: release:fix

#7475 Invert meaning of dupe_key
  psalm-baseline.xml
  src/Psalm/Internal/Analyzer/AlgebraAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOpAnalyzer.php
  src/Psalm/Internal/LanguageServer/Server/TextDocument.php
  src/Psalm/Internal/Type/AssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  src/Psalm/IssueBuffer.php
Labels: release:feature

#7837 Avoiding double spaces (v2)
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/InstancePropertyFetchAnalyzer.php
Labels: release:fix

#7844 fix refining lowercase string and non-empty-string together
  src/Psalm/Internal/Type/AssertionReconciler.php
  tests/AssertAnnotationTest.php
Labels: release:fix

#7849 Document `@psalm-yield`
  docs/annotating_code/supported_annotations.md
  docs/annotating_code/type_syntax/array_types.md
  docs/annotating_code/typing_in_psalm.md
  docs/running_psalm/language_server.md
  tests/DocumentationTest.php
Labels: release:docs

#7851 Document `@psalm-ignore-variable-*`
  docs/annotating_code/supported_annotations.md
  tests/DocumentationTest.php
Labels: release:docs

#7838 Fix Incompatible types found for T (Stub&ProxyQueryInterface is not in ProxyQueryInterface&Stub)
  src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php
  tests/Template/ClassTemplateTest.php
Labels: release:fix

#7866 Fix openssl_csr_export() signature
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
Labels: release:fix

#7859 Resolve #7855 remove false from return type, in php8.0 and further ve…
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
Labels: release:fix

#7861 Disable filepath formatting as a link for Drone CI's output
  src/Psalm/Internal/CliUtils.php
Labels: release:feature

#7867 Documented the allowMissingFiles attribute for ignoreFiles
  docs/running_psalm/configuration.md
Labels: release:docs

#7876 cache statements even without persistent parser cache
  src/Psalm/Internal/Provider/StatementsProvider.php
  src/Psalm/Internal/Provider/StatementsVolatileCache.php
  src/Psalm/Internal/RuntimeCaches.php
Labels: release:feature

#7872 don't emit issues when doing arithmetics on float templates
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ArithmeticOpAnalyzer.php
  tests/Template/FunctionTemplateTest.php
Labels: release:fix

#7894 Fix return type of `ldap_search`
  dictionaries/CallMap.php
  dictionaries/CallMap_81_delta.php
Labels: release:fix

#7904 Alter order of baseline option loading to permit updating custom baseline
  src/Psalm/Internal/Cli/Psalm.php
Labels: release:fix

#7887 improve LSP
  src/Psalm/Internal/LanguageServer/LanguageServer.php
  src/Psalm/Internal/LanguageServer/Server/TextDocument.php
Labels: release:fix

#7908 Fix sort assert annotation
  stubs/CoreGenericFunctions.phpstub
  tests/ArgTest.php
  tests/ArrayFunctionCallTest.php
Labels: release:feature
