Repository vimeo/psalm, pull requests merged in 2022-07, with the labels that each got.

#8166 Allow testing expected CallMap return types
  dictionaries/CallMap.php
  dictionaries/CallMap_81_delta.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:internal

#8217 Fix several CallMap function signatures
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#8220 Fix codestyle errors in InternalCallMapHandlerTest
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:internal

#8219 fix: ltrim may return class-string #8218
  stubs/CoreGenericFunctions.phpstub
Labels: release:fix

#8000 update property map
  bin/update-property-map.php
  dictionaries/ManualPropertyMap.php
  dictionaries/PropertyMap.php
  phpcs.xml
  src/Psalm/Internal/Codebase/PropertyMap.php
  src/Psalm/Internal/Codebase/Reflection.php
  stubs/Reflection.phpstub
Labels: release:internal

#8240 use lock to fix race condition in cache
  src/Psalm/Internal/Provider/ParserCacheProvider.php
Labels: release:fix

#8243 use error_log instead of trigger_error
  src/Psalm/Config.php
  src/Psalm/Internal/Provider/ParserCacheProvider.php
Labels: release:internal

#8214 Fix GEOSGeometry stubs with default values
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#8244 New "Count" Report Format
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/IssueBuffer.php
  src/Psalm/Report.php
  src/Psalm/Report/CountReport.php
  src/Psalm/Report/ReportOptions.php
  tests/ReportOutputTest.php
Labels: release:feature

#7994 Adds support for fixing missing throws doc block
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Internal/FileManipulation/FunctionDocblockManipulator.php
  tests/FileManipulation/FileManipulationTestCase.php
  tests/FileManipulation/ThrowsBlockAdditionTest.php
Labels: release:feature

#8249 Improve inferring the "final" `static` type when calling static methods inside a different class
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/ExistingAtomicStaticCallAnalyzer.php
  tests/Template/ClassTemplateTest.php
Labels: release:fix

#8273 Remove special handling for elseifs that breaks for else if
  src/Psalm/Context.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/IfAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php
  tests/TypeReconciliation/TypeAlgebraTest.php
Labels: release:internal

#8283 Allow `value-of` to work with backed enums (fixes #7874).
  UPGRADING.md
  docs/running_psalm/plugins/plugins_type_system.md
  src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php
  src/Psalm/Internal/Type/TemplateInferredTypeReplacer.php
  src/Psalm/Internal/Type/TypeExpander.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Type/Atomic/TIntMaskOf.php
  src/Psalm/Type/Atomic/TKeyOf.php
  src/Psalm/Type/Atomic/TTemplateKeyOf.php
  src/Psalm/Type/Atomic/TTemplateValueOf.php
  src/Psalm/Type/Atomic/TValueOf.php
  tests/ValueOfTest.php
Labels: release:feature

#8304 fix triggerErrorExits not working
  src/Psalm/Config.php
Labels: release:fix

#8306 Fix type reconciliation breaking Context::$references_in_scope (fixes #8289).
  src/Psalm/Internal/Analyzer/Statements/Block/DoAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfConditionalAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/ElseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/ElseIfAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/IfAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/SwitchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/SwitchCaseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/AndAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/OrAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/MatchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/TernaryAnalyzer.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayFilterReturnTypeProvider.php
  src/Psalm/Type/Reconciler.php
  tests/ReferenceTest.php
Labels: release:fix

#8308 Fixed ini_set types for arg value
  dictionaries/CallMap.php
  dictionaries/CallMap_81_delta.php
Labels: release:fix

#8282 Update `CachingIterator::getCache` stub.
  stubs/CoreGenericIterators.phpstub
Labels: release:fix

#8312 Add stub for DatePeriod
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  stubs/CoreImmutableClasses.phpstub
  stubs/Php80.phpstub
  tests/CoreStubsTest.php
Labels: release:fix

#8044 Fix various array spread issues.
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayCreationInfo.php
  src/Psalm/Type/Atomic.php
  tests/ArrayAssignmentTest.php
Labels: release:fix

#8324 Fix union assertions
  src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php
  src/Psalm/Type.php
  src/Psalm/Type/Atomic/TLiteralFloat.php
  src/Psalm/Type/Atomic/TLiteralInt.php
  src/Psalm/Type/Atomic/TLiteralString.php
  src/Psalm/Type/Union.php
  tests/ArrayAssignmentTest.php
  tests/AssertAnnotationTest.php
  tests/InterfaceTest.php
  tests/Template/FunctionTemplateAssertTest.php
  tests/TypeParseTest.php
Labels: release:fix

#8335 #8330 - take into account that `static` type may have been unwrapped in `hasStaticInType()`
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/ExistingAtomicStaticCallAnalyzer.php
  tests/Template/ClassTemplateTest.php
Labels: release:fix

#8341 recognize `@psalm-allow-private-mutation` in PHP 8+ constructors
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  tests/ReadonlyPropertyTest.php
Labels: release:fix

#8344 ReflectionProperty::getValue $object is nullable since php 8.0
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
Labels: release:fix

#8345 Applied ArraySpreadInsteadOfArrayMergeRector (take 2)
  src/Psalm/Codebase.php
  src/Psalm/Config/Creator.php
  src/Psalm/ErrorBaseline.php
  src/Psalm/Internal/Algebra/FormulaGenerator.php
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Internal/Analyzer/ScopeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/DoAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfConditionalAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/ElseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/ElseIfAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/IfAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/SwitchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/SwitchCaseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/WhileAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/InstancePropertyAssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/AndAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/OrAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ClassTemplateParamCollector.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/TernaryAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/ReturnAnalyzer.php
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  src/Psalm/Internal/Analyzer/TypeAnalyzer.php
  src/Psalm/Internal/Cli/Psalter.php
  src/Psalm/Internal/Codebase/DataFlowGraph.php
  src/Psalm/Internal/Codebase/Methods.php
  src/Psalm/Internal/Codebase/Populator.php
  src/Psalm/Internal/Codebase/TaintFlowGraph.php
  src/Psalm/Internal/Codebase/VariableUseGraph.php
  src/Psalm/Internal/Diff/FileStatementsDiffer.php
  src/Psalm/Internal/Diff/NamespaceStatementsDiffer.php
  src/Psalm/Internal/EventDispatcher.php
  src/Psalm/Internal/IncludeCollector.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  src/Psalm/Internal/Provider/FileReferenceProvider.php
  src/Psalm/Internal/Stubs/Generator/ClassLikeStubGenerator.php
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  src/Psalm/Internal/Type/TypeExpander.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Type/Union.php
  tests/Internal/CallMapTest.php
Labels: release:internal

#8349 Fix formatCurrency return type
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix
