Repository vimeo/psalm, pull requests merged in 2022-09, with the labels that each got.

#8451 GitHub Workflows security hardening
  .github/workflows/build-phar.yml
Labels: release:internal

#8450 Make ctype_digit and ctype_lower work as assertions
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  tests/TypeReconciliation/ConditionalTest.php
Labels: release:feature

#8466 Fix ctype_digit assertion bug
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  tests/TypeReconciliation/ConditionalTest.php
Labels: release:fix

#8465 report invalidCasing when using a class that is not user defined too
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/ClassLikeAnalyzer.php
  src/Psalm/Internal/Codebase/ClassLikes.php
  src/Psalm/Internal/PluginManager/ConfigFile.php
  tests/IntRangeTest.php
  tests/MethodCallTest.php
Labels: release:feature

#8469 preg_replace with anchor will always only have 1 replacement
  src/Psalm/Codebase.php
  src/Psalm/Config.php
  src/Psalm/Config/Creator.php
  src/Psalm/Config/FileFilter.php
  src/Psalm/Context.php
  src/Psalm/DocComment.php
  src/Psalm/Internal/Analyzer/ClassLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/NamespaceAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php
  src/Psalm/Internal/Cli/LanguageServer.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Cli/Psalter.php
  src/Psalm/Internal/Cli/Refactor.php
  src/Psalm/Internal/Codebase/Analyzer.php
  src/Psalm/Internal/Codebase/ClassLikes.php
  src/Psalm/Internal/Codebase/Properties.php
  src/Psalm/Internal/MethodIdentifier.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeDocblockParser.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php
  src/Psalm/Internal/Scanner/DocblockParser.php
Labels: release:internal

#8432 Update call maps for MongoDB extension
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:feature

#8367 partial revert nullable type for curl_multi_getcontent
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#8468 classlike_alias incorrect casing not handled correctly
  src/Psalm/Codebase.php
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Codebase/ClassLikes.php
  src/Psalm/Internal/Codebase/Scanner.php
  src/Psalm/Internal/PhpVisitor/Reflector/ExpressionScanner.php
  src/Psalm/Storage/FileStorage.php
  tests/Internal/Codebase/ClassLikesTest.php
Labels: release:fix

#8136 Update phpredis.phpstub
  stubs/phpredis.phpstub
Labels: release:fix

#8415 Consistent error logging for cache
  src/Psalm/Config.php
  src/Psalm/Internal/Provider/ClassLikeStorageCacheProvider.php
  src/Psalm/Internal/Provider/FileReferenceCacheProvider.php
  src/Psalm/Internal/Provider/FileStorageCacheProvider.php
  src/Psalm/Internal/Provider/ParserCacheProvider.php
  src/Psalm/Internal/Provider/StatementsProvider.php
  tests/Internal/Provider/FakeParserCacheProvider.php
  tests/Internal/Provider/ParserInstanceCacheProvider.php
Labels: release:internal

#8481 Fix mixed type hole when sending Foo<string> to Foo<mixed>
  composer.json
  psalm.xml.dist
  src/Psalm/Internal/LanguageServer/Client/TextDocument.php
  src/Psalm/Internal/Type/Comparator/GenericTypeComparator.php
  tests/IfThisIsTest.php
  tests/Template/ClassTemplateExtendsTest.php
  tests/Template/ClassTemplateTest.php
Labels: release:fix

#8478 `date_get_last_errors()`, `DateTime::getLastErrors()` may return false
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#8462 Add dateTimeModify return type provider
  src/Psalm/Internal/Provider/MethodReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/DateTimeModifyReturnTypeProvider.php
  tests/DateTimeTest.php
  tests/MethodCallTest.php
Labels: release:feature

#8489 Fix array_key_exists first argument false positive
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  tests/TypeReconciliation/ArrayKeyExistsTest.php
Labels: release:fix

#8493 Document the object with properties syntax
  docs/annotating_code/type_syntax/atomic_types.md
  docs/annotating_code/type_syntax/object_types.md
Labels: release:docs

#8492 Make template constraints examples in docs consistent
  docs/annotating_code/templated_annotations.md
  docs/annotating_code/type_syntax/conditional_types.md
  docs/running_psalm/issues/InvalidTemplateParam.md
  docs/running_psalm/issues/NonInvariantDocblockPropertyType.md
Labels: release:docs

#8491 Fix array_column with object and column name null
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayColumnReturnTypeProvider.php
  tests/ReturnTypeProvider/ArrayColumnTest.php
Labels: release:fix

#8490 Add null-type to several DOM-functions
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#8494 Fix type widening when `Any` assertion is used
  src/Psalm/Internal/Type/AssertionReconciler.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  tests/TypeReconciliation/IssetTest.php
  tests/TypeReconciliation/ReconcilerTest.php
Labels: release:fix

#8473 make superglobals more specific
  docs/running_psalm/issues/MixedArgument.md
  docs/running_psalm/issues/MixedArrayAccess.md
  docs/running_psalm/issues/MixedArrayAssignment.md
  docs/running_psalm/issues/MixedArrayOffset.md
  docs/running_psalm/issues/MixedAssignment.md
  docs/running_psalm/issues/MixedClone.md
  docs/running_psalm/issues/MixedFunctionCall.md
  docs/running_psalm/issues/MixedInferredReturnType.md
  docs/running_psalm/issues/MixedOperand.md
  docs/running_psalm/issues/MixedReturnStatement.md
  docs/running_psalm/issues/MixedStringOffsetAssignment.md
  src/Psalm/Codebase.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/GlobalAnalyzer.php
  src/Psalm/Internal/Type/AssertionReconciler.php
  tests/ArrayAssignmentTest.php
  tests/ArrayFunctionCallTest.php
  tests/AssertAnnotationTest.php
  tests/FileUpdates/TemporaryUpdateTest.php
  tests/FunctionCallTest.php
  tests/Internal/CliUtilsTest.php
  tests/JsonOutputTest.php
  tests/LanguageServer/SymbolLookupTest.php
  tests/ReturnTypeTest.php
  tests/TaintTest.php
  tests/Template/ClassTemplateTest.php
  tests/Template/ConditionalReturnTypeTest.php
  tests/TypeReconciliation/ConditionalTest.php
  tests/TypeReconciliation/EmptyTest.php
  tests/fixtures/DummyProjectWithErrors/src/FileWithErrors.php
  tests/fixtures/expected_taint_graph.dot
Labels: release:feature

#8480 Make Psalter add `@throws` annotation with properly namespaced exception
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  tests/FileManipulation/ThrowsBlockAdditionTest.php
Labels: release:fix, PR: Need review

#8366 Fix invalid casts int and float
  config.xsd
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/RiskyCast.md
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  src/Psalm/Internal/Cli/LanguageServer.php
  src/Psalm/Internal/Cli/Psalter.php
  src/Psalm/Internal/Cli/Refactor.php
  src/Psalm/Internal/Provider/FunctionReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/RoundReturnTypeProvider.php
  src/Psalm/Issue/RiskyCast.php
  tests/FunctionCallTest.php
  tests/ToStringTest.php
  tests/TypeReconciliation/ValueTest.php
Labels: release:feature

#8503 use cache for declared function when available before falling back to stubs
  src/Psalm/Internal/Codebase/Functions.php
Labels: release:fix

#8416 fix crash in <PHP8 with ResourceBundle
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix, PR: Need work

#8502 add hideAllErrorsExceptPassedFiles config option
  docs/running_psalm/configuration.md
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
Labels: release:feature
