Repository vimeo/psalm, pull requests merged in 2022-02, with the labels that each got.

#7554 Ensure `trait_exists()` always returns `bool`
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#7558 sealed keyed arrays
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  src/Psalm/Internal/Codebase/ConstantTypeResolver.php
Labels: release:fix

#7561 AtomicStaticCallAnalyzer: clear tmp var from context
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  tests/MagicMethodAnnotationTest.php
  tests/MixinAnnotationTest.php
Labels: release:fix

#7564 Fix documentation for <globals> config.
  docs/running_psalm/configuration.md
Labels: release:docs

#7565 Fix bullet indentation in documentation
  docs/running_psalm/configuration.md
  docs/running_psalm/issues/TaintedFile.md
  docs/running_psalm/language_server.md
Labels: documentation

#7573 improving error message for Could not resolve config path
  src/Psalm/Config/FileFilter.php
Labels: release:fix

#7574 Fix extension capitalization issue, add extensions to version message.
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  tests/EndToEnd/PsalmEndToEndTest.php
  tests/ProjectCheckerTest.php
Labels: release:internal

#7576 Added backward compatibility check
  .github/workflows/bcc.yml
  vendor-bin/bcc/composer.json
Labels: release:internal

#7583 Fix crash when assigning reference to unknown array offset
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  tests/ReferenceTest.php
Labels: release:fix

#7585 Resolve __DIR__ / __FILE__ when const/variable is used for include
  src/Psalm/Internal/Analyzer/Statements/Expression/MagicConstAnalyzer.php
Labels: release:feature

#7591 Allow mocking final classes
  composer.json
Labels: release:internal

#7594 Fixed composer branch-alias
  composer.json
Labels: release:internal

#7593 doc about property initialization
  docs/running_psalm/issues/MissingConstructor.md
  docs/running_psalm/issues/PropertyNotSetInConstructor.md
  docs/running_psalm/issues/RedundantPropertyInitializationCheck.md
Labels: release:docs

#7597 Finalize storages
  UPGRADING.md
  src/Psalm/Storage/Assertion/Any.php
  src/Psalm/Storage/Assertion/ArrayKeyDoesNotExist.php
  src/Psalm/Storage/Assertion/ArrayKeyExists.php
  src/Psalm/Storage/Assertion/DoesNotHaveAtLeastCount.php
  src/Psalm/Storage/Assertion/DoesNotHaveExactCount.php
  src/Psalm/Storage/Assertion/DoesNotHaveMethod.php
  src/Psalm/Storage/Assertion/Empty_.php
  src/Psalm/Storage/Assertion/Falsy.php
  src/Psalm/Storage/Assertion/HasArrayKey.php
  src/Psalm/Storage/Assertion/HasAtLeastCount.php
  src/Psalm/Storage/Assertion/HasExactCount.php
  src/Psalm/Storage/Assertion/HasIntOrStringArrayAccess.php
  src/Psalm/Storage/Assertion/HasMethod.php
  src/Psalm/Storage/Assertion/HasStringArrayAccess.php
  src/Psalm/Storage/Assertion/InArray.php
  src/Psalm/Storage/Assertion/IsAClass.php
  src/Psalm/Storage/Assertion/IsClassEqual.php
  src/Psalm/Storage/Assertion/IsClassNotEqual.php
  src/Psalm/Storage/Assertion/IsCountable.php
  src/Psalm/Storage/Assertion/IsEqualIsset.php
  src/Psalm/Storage/Assertion/IsGreaterThan.php
  src/Psalm/Storage/Assertion/IsGreaterThanOrEqualTo.php
  src/Psalm/Storage/Assertion/IsIdentical.php
  src/Psalm/Storage/Assertion/IsIsset.php
  src/Psalm/Storage/Assertion/IsLessThan.php
  src/Psalm/Storage/Assertion/IsLessThanOrEqualTo.php
  src/Psalm/Storage/Assertion/IsLooselyEqual.php
  src/Psalm/Storage/Assertion/IsNotAClass.php
  src/Psalm/Storage/Assertion/IsNotCountable.php
  src/Psalm/Storage/Assertion/IsNotIdentical.php
  src/Psalm/Storage/Assertion/IsNotIsset.php
  src/Psalm/Storage/Assertion/IsNotLooselyEqual.php
  src/Psalm/Storage/Assertion/IsNotType.php
  src/Psalm/Storage/Assertion/IsType.php
  src/Psalm/Storage/Assertion/NestedAssertions.php
  src/Psalm/Storage/Assertion/NonEmpty.php
  src/Psalm/Storage/Assertion/NonEmptyCountable.php
  src/Psalm/Storage/Assertion/NotInArray.php
  src/Psalm/Storage/Assertion/NotNestedAssertions.php
  src/Psalm/Storage/Assertion/NotNonEmptyCountable.php
  src/Psalm/Storage/Assertion/Truthy.php
  src/Psalm/Storage/AttributeArg.php
  src/Psalm/Storage/AttributeStorage.php
  src/Psalm/Storage/ClassConstantStorage.php
  src/Psalm/Storage/ClassLikeStorage.php
  src/Psalm/Storage/EnumCaseStorage.php
  src/Psalm/Storage/FileStorage.php
  src/Psalm/Storage/FunctionLikeParameter.php
  src/Psalm/Storage/FunctionStorage.php
  src/Psalm/Storage/MethodStorage.php
  src/Psalm/Storage/Possibilities.php
  src/Psalm/Storage/PropertyStorage.php
Labels: release:removed

#7612 No longer require declare reflection-docblock:^5 as dependency
  composer.json
Labels: release:internal

#7617 Bump up phpunit,prophecy, and introduced phpspec/prophecy-phpunit
  composer.json
Labels: release:internal

#7620 Strip colours from success message
  src/Psalm/IssueBuffer.php
  tests/IssueBufferTest.php
Labels: release:fix

#7622 consistency in AssertionFinder
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
Labels: release:internal

#7621 add ReflectionIntersectionType stub
  stubs/Php81.phpstub
Labels: release:feature

#7623 Finalize types nodes
  UPGRADING.md
  src/Psalm/Internal/Provider/ReturnTypeProvider/FilterVarReturnTypeProvider.php
  src/Psalm/Type/Atomic/TAnonymousClassInstance.php
  src/Psalm/Type/Atomic/TCallable.php
  src/Psalm/Type/Atomic/TCallableArray.php
  src/Psalm/Type/Atomic/TCallableKeyedArray.php
  src/Psalm/Type/Atomic/TCallableList.php
  src/Psalm/Type/Atomic/TCallableObject.php
  src/Psalm/Type/Atomic/TCallableString.php
  src/Psalm/Type/Atomic/TClassConstant.php
  src/Psalm/Type/Atomic/TClassStringMap.php
  src/Psalm/Type/Atomic/TClosedResource.php
  src/Psalm/Type/Atomic/TClosure.php
  src/Psalm/Type/Atomic/TConditional.php
  src/Psalm/Type/Atomic/TDependentGetClass.php
  src/Psalm/Type/Atomic/TDependentGetDebugType.php
  src/Psalm/Type/Atomic/TDependentGetType.php
  src/Psalm/Type/Atomic/TDependentListKey.php
  src/Psalm/Type/Atomic/TEmptyMixed.php
  src/Psalm/Type/Atomic/TEmptyNumeric.php
  src/Psalm/Type/Atomic/TEmptyScalar.php
  src/Psalm/Type/Atomic/TEnumCase.php
  src/Psalm/Type/Atomic/TFalse.php
  src/Psalm/Type/Atomic/TGenericObject.php
  src/Psalm/Type/Atomic/TIntMask.php
  src/Psalm/Type/Atomic/TIntMaskOf.php
  src/Psalm/Type/Atomic/TIntRange.php
  src/Psalm/Type/Atomic/TIterable.php
  src/Psalm/Type/Atomic/TKeyOfArray.php
  src/Psalm/Type/Atomic/TLiteralClassString.php
  src/Psalm/Type/Atomic/TLiteralFloat.php
  src/Psalm/Type/Atomic/TLiteralInt.php
  src/Psalm/Type/Atomic/TLowercaseString.php
  src/Psalm/Type/Atomic/TNever.php
  src/Psalm/Type/Atomic/TNonEmptyLowercaseString.php
  src/Psalm/Type/Atomic/TNonEmptyMixed.php
  src/Psalm/Type/Atomic/TNonEmptyNonspecificLiteralString.php
  src/Psalm/Type/Atomic/TNonEmptyScalar.php
  src/Psalm/Type/Atomic/TNonspecificLiteralInt.php
  src/Psalm/Type/Atomic/TNull.php
  src/Psalm/Type/Atomic/TNumericString.php
  src/Psalm/Type/Atomic/TObjectWithProperties.php
  src/Psalm/Type/Atomic/TResource.php
  src/Psalm/Type/Atomic/TSingleLetter.php
  src/Psalm/Type/Atomic/TTemplateIndexedAccess.php
  src/Psalm/Type/Atomic/TTemplateKeyOf.php
  src/Psalm/Type/Atomic/TTemplateParam.php
  src/Psalm/Type/Atomic/TTemplateParamClass.php
  src/Psalm/Type/Atomic/TTemplateValueOf.php
  src/Psalm/Type/Atomic/TTraitString.php
  src/Psalm/Type/Atomic/TTrue.php
  src/Psalm/Type/Atomic/TTypeAlias.php
  src/Psalm/Type/Atomic/TValueOfArray.php
  src/Psalm/Type/Atomic/TVoid.php
  src/Psalm/Type/TaintKind.php
  src/Psalm/Type/TaintKindGroup.php
  src/Psalm/Type/Union.php
Labels: release:removed

#7631 Fix #6683 by improving simplification of CNF
  src/Psalm/Internal/Algebra.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php
  tests/TypeReconciliation/TypeAlgebraTest.php
Labels: release:fix

#7633 Allow config to define thread count (4.x)
  docs/running_psalm/configuration.md
  src/Psalm/Config.php
  src/Psalm/Internal/Cli/Psalm.php
Labels: release:feature, PR: Need review

#7642 skip a test because we removed the feature for now
  tests/MethodSignatureTest.php
Labels: release:internal

#7632 Adjust for composer-require-checker check.
  bin/composer-require-checker-config.json
  src/Psalm/Config.php
  src/Psalm/Internal/PluginManager/ConfigFile.php
Labels: release:internal

#7614 add phpredis stubs
  src/Psalm/Config.php
  stubs/phpredis.phpstub
Labels: release:feature

#7651 remove totallyTyped
  config.xsd
  docs/annotating_code/type_syntax/atomic_types.md
  docs/running_psalm/configuration.md
  docs/running_psalm/error_levels.md
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallReturnTypeFetcher.php
Labels: release:removed

#7652 Removed .scrutinizer.yml
  .gitattributes
  .scrutinizer.yml
Labels: release:internal

#7657 Honour global function suppressions for UndefinedFunction
  src/Psalm/Config.php
  tests/Config/ConfigTest.php
Labels: release:fix

#7660 Update return type for mysqli::connect_error
  dictionaries/PropertyMap.php
Labels: release:fix

#7659 Correct name of ErrorException::__construct $line param
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#7661 Use `array_fill_keys()`
  src/Psalm/Internal/Provider/StatementsProvider.php
Labels: release:internal

#7662 Enum assertions
  src/Psalm/Internal/Provider/StatementsProvider.php
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
  tests/EnumTest.php
Labels: release:fix

#7663 Consistency for empty reconciliations
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
Labels: release:fix

#7664 Fix false positive for unused variable in try (fixes #7613).
  src/Psalm/Context.php
  src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  tests/TaintTest.php
  tests/UnusedVariableTest.php
Labels: release:fix

#7665 fix count with match on arrays
  src/Psalm/Internal/Analyzer/Statements/Expression/MatchAnalyzer.php
  tests/MatchTest.php
Labels: release:fix

#7434 Add configuration option to disable @var parsing everywhere except for properties.
  config.xsd
  docs/running_psalm/configuration.md
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/ReturnAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/StaticAnalyzer.php
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
Labels: release:feature, PR: Need review

#7677 Prevent unnecessary filter_var() warnings on primitive types
  stubs/CoreGenericFunctions.phpstub
  tests/TaintTest.php
Labels: release:fix

#7666 More class const improvements.
  config.xsd
  docs/running_psalm/issues.md
  docs/running_psalm/issues/InvalidClassConstantType.md
  docs/running_psalm/issues/OverriddenFinalConstant.md
  src/Psalm/Internal/Analyzer/Statements/Expression/ClassConstAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Issue/InvalidClassConstantType.php
  src/Psalm/Issue/OverriddenFinalConstant.php
  src/Psalm/Storage/ClassConstantStorage.php
  tests/ConstantTest.php
  tests/DocumentationTest.php
Labels: release:feature

#7683 Fixed PSR-4 warnings
  tests/Template/KeyOfTemplateTest.php
  tests/Template/ValueOfTemplateTest.php
Labels: release:internal

#7686 Add `@psalm-check-type` and `@psalm-check-type-exact`.
  config.xsd
  docs/annotating_code/supported_annotations.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/CheckType.md
  src/Psalm/DocComment.php
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  src/Psalm/Issue/CheckType.php
  tests/CheckTypeTest.php
Labels: release:feature

#7687 Fix issue documentation links.
  docs/running_psalm/issues/MissingConstructor.md
  docs/running_psalm/issues/PropertyNotSetInConstructor.md
  docs/running_psalm/issues/RedundantPropertyInitializationCheck.md
Labels: release:docs

#7690 Throw exception if file_put_contents failed
  src/Psalm/Internal/PluginManager/ConfigFile.php
Labels: release:fix

#7693 Improve documentation for InvalidGlobal to explain that it's sometimes valid
  docs/running_psalm/issues/InvalidGlobal.md
  src/Psalm/Internal/Analyzer/Statements/GlobalAnalyzer.php
Labels: release:docs

#7696 Improve bool to int casting.
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  tests/CastTest.php
Labels: release:fix

#7699 Fix issues with int range unpacking and with min/max
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/MinMaxReturnTypeProvider.php
  src/Psalm/Internal/Type/ArrayType.php
  tests/FunctionCallTest.php
  tests/IntRangeTest.php
Labels: release:fix

#7692 Analyze attribute statements instead of constructing virtual statements.
  src/Psalm/Internal/Analyzer/AttributeAnalyzer.php
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/InterfaceAnalyzer.php
  src/Psalm/Internal/Codebase/Methods.php
  src/Psalm/Internal/Provider/MethodParamsProvider.php
  src/Psalm/Storage/AttributeArg.php
  tests/AttributeTest.php
Labels: release:fix, PR: Need review

#7684 Fix some minor issues with references.
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  tests/ReferenceTest.php
  tests/UnusedVariableTest.php
Labels: release:fix, PR: Need review

#7596 chore: enable psl tests again
  .circleci/config.yml
  bin/test-with-real-projects.sh
Labels: release:internal, PR: Need review

#7708 Config threads: add to config.xsd
  config.xsd
  src/Psalm/Config.php
Labels: release:fix

#7713 Use current context when analyzing attributes
  src/Psalm/Internal/Analyzer/AttributeAnalyzer.php
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/InterfaceAnalyzer.php
  tests/AttributeTest.php
Labels: release:fix

#7715 Fix first-class callable in loop
  src/Psalm/Internal/PhpVisitor/AssignmentMapVisitor.php
  tests/ClosureTest.php
Labels: release:fix

#7719 Support for properties in interfaces extending `\UnitEnum` & `\BackedEnum`
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  stubs/Php81.phpstub
  tests/EnumTest.php
  tests/Traits/ValidCodeAnalysisTestTrait.php
Labels: release:fix, PR: Need review, PR: Need work

#7673 PDOException extends RuntimeException and can use int code errors
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  dictionaries/PropertyMap.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallReturnTypeFetcher.php
  tests/ReturnTypeProvider/ExceptionCodeTest.php
Labels: release:fix

#7732 allow SimpleTypeInferer to infer non empty lists
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  tests/ListTest.php
Labels: release:fix

#7727 Attribute analysis improvements
  src/Psalm/Internal/Analyzer/AttributeAnalyzer.php
  src/Psalm/Internal/Analyzer/AttributesAnalyzer.php
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/FileAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/InterfaceAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  src/Psalm/Internal/Analyzer/TraitAnalyzer.php
  src/Psalm/Storage/ClassLikeStorage.php
  src/Psalm/Storage/FunctionLikeParameter.php
  src/Psalm/Storage/FunctionLikeStorage.php
  src/Psalm/Storage/HasAttributesInterface.php
  src/Psalm/Storage/PropertyStorage.php
  stubs/Reflection.phpstub
  tests/AttributeTest.php
  tests/TraitTest.php
Labels: release:fix, PR: Need review

#7359 feat(types): add properties-of<T> type
  docs/annotating_code/type_syntax/atomic_types.md
  docs/annotating_code/type_syntax/utility_types.md
  docs/running_psalm/plugins/plugins_type_system.md
  src/Psalm/Internal/Type/TemplateInferredTypeReplacer.php
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  src/Psalm/Internal/Type/TypeExpander.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Internal/Type/TypeTokenizer.php
  src/Psalm/Type/Atomic/TKeyOfArray.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  src/Psalm/Type/Atomic/TPropertiesOf.php
  src/Psalm/Type/Atomic/TTemplatePropertiesOf.php
  src/Psalm/Type/Atomic/TValueOfArray.php
  tests/KeyOfArrayTest.php
  tests/PropertiesOfTest.php
  tests/Template/PropertiesOfTemplateTest.php
  tests/TypeComparatorTest.php
  tests/ValueOfArrayTest.php
Labels: release:feature, PR: Need review
