Repository vimeo/psalm, pull requests merged in 2022-12, with the labels that each got.

#8805 Update installation.md - `5` requires PHP >= 7.4
  docs/running_psalm/installation.md
Labels: release:docs

#8624 check "never" return type more strictly
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php
  src/Psalm/Internal/Analyzer/ScopeAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/TriggerErrorReturnTypeProvider.php
  src/Psalm/Internal/Type/TypeCombiner.php
  src/Psalm/Internal/Type/TypeExpander.php
  src/Psalm/Type.php
  src/Psalm/Type/MutableUnion.php
  src/Psalm/Type/Union.php
  src/Psalm/Type/UnionTrait.php
  tests/FunctionCallTest.php
Labels: release:feature

#8798 fix sealed combination
  src/Psalm/Internal/Type/TypeCombiner.php
  tests/ArrayFunctionCallTest.php
Labels: release:fix

#8809 Fix #8806
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMapReturnTypeProvider.php
  tests/ArrayFunctionCallTest.php
Labels: release:fix

#8808 Adds documentation for the `forbiddenFunctions` config option
  docs/running_psalm/configuration.md
Labels: release:docs

#8774 Report by issues grouped by level and type
  .circleci/config.yml
  docs/running_psalm/error_levels.md
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/IssueBuffer.php
  src/Psalm/Report.php
  src/Psalm/Report/ByIssueLevelAndTypeReport.php
  tests/ByIssueLevelAndTypeReportTest.php
Labels: release:feature

#8814 Fix crash when using phantom methods as first-class callable
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php
  tests/ClosureTest.php
Labels: release:fix

#8816 Don't crash when accessing immutable static property
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/InstancePropertyAssignmentAnalyzer.php
  tests/UnusedCodeTest.php
Labels: release:fix

#8817 Prevent crashes on conditional traits
  src/Psalm/Internal/Analyzer/TraitAnalyzer.php
  tests/TraitTest.php
Labels: release:fix

#8823 Update dictionaries: use more specific boolean types
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#8825 Fix return types for date functions in callmap
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#8827 Improve source autodiscovery failure message
  src/Psalm/Config/Creator.php
Labels: release:fix

#8828 fix missing break handling in loop
  src/Psalm/Internal/Analyzer/ScopeAnalyzer.php
  tests/Loop/WhileTest.php
Labels: release:fix

#8831 capitalize properties
  dictionaries/PropertyMap.php
Labels: release:fix

#8832 mysqli_execute_query accepts any type of param
  dictionaries/CallMap.php
  dictionaries/CallMap_82_delta.php
Labels: release:fix

#8834 Fix parsing of class string of unions
  src/Psalm/Internal/Type/TypeParser.php
  tests/ClassLikeStringTest.php
Labels: release:fix

#8835 Extend impure_functions list by socket functions
  src/Psalm/Internal/Codebase/Functions.php
Labels: release:fix

#8861 Precise count range
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  tests/FunctionCallTest.php
Labels: release:fix

#8869 Add missing ZipArchive methods to CallMap (PHP 8.2)
  dictionaries/CallMap.php
  dictionaries/CallMap_82_delta.php
Labels: internal stubs/callmap, release:feature

#8871 Add libxml_get_external_entity_loader to CallMap (PHP 8.2)
  dictionaries/CallMap.php
  dictionaries/CallMap_82_delta.php
  dictionaries/CallMap_historical.php
Labels: internal stubs/callmap, release:feature

#8875 Allow `true` in native types
  src/Psalm/Type/Atomic.php
  tests/ReturnTypeTest.php
Labels: release:feature

#8876 Fixed dynamic property on LanguageServer
  src/Psalm/Internal/LanguageServer/LanguageServer.php
Labels: release:fix

#8870 Add some missing sodium functions to CallMap
  dictionaries/CallMap.php
  dictionaries/CallMap_72_delta.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_82_delta.php
Labels: release:feature

#8854 remove file_get_contents that was incorrectly put in v5
  src/Psalm/Internal/Provider/ParserCacheProvider.php
  src/Psalm/Internal/Provider/ProjectCacheProvider.php
Labels: release:fix

#8833 Integrate FidryCpuCoreCounter
  composer.json
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
Labels: release:internal

#8882 Upgrade CpuCoreCounter
  composer.json
Labels: release:internal

#8890 Forbid most magic methods on enums
  config.xsd
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/InvalidEnumMethod.md
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/MethodAnalyzer.php
  src/Psalm/Issue/InvalidEnumMethod.php
  tests/DocumentationTest.php
  tests/EnumTest.php
Labels: release:feature, release:fix

#8722 Declaring more precise types and purity boundaries on `ext-reflection` symbols in `.phpstub` files
  src/Psalm/Config.php
  stubs/Php80.phpstub
  stubs/Php81.phpstub
  stubs/Php82.phpstub
  stubs/Reflection.phpstub
  tests/AttributeTest.php
Labels: release:feature

#8895 Replace unmaintained `openlss/lib-array2xml` with `spatie/array-to-xml`
  composer.json
  src/Psalm/Report/XmlReport.php
Labels: release:internal

#8826 Add validation for Class::Method names in CallMap
  dictionaries/CallMap.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:internal

#8850 Literal inferring for array_column, array_combine, array_fill_keys, array_fill
  src/Psalm/Internal/Provider/FunctionReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayColumnReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayCombineReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayFillKeysReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayFillReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/GetObjectVarsReturnTypeProvider.php
  tests/ArrayFunctionCallTest.php
Labels: release:feature

#8841 Improve parsing of list shapes
  src/Psalm/Internal/Type/TypeParser.php
  tests/FileUpdates/TemporaryUpdateTest.php
  tests/TypeParseTest.php
Labels: release:fix

#8899 Fix DOM and Reflection unreflectable methods
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#8885 Deprecation message on loading php-ext stubs without explicitly declaring them as dependency or in a config
  src/Psalm/Config.php
  stubs/extensions/apcu.phpstub
  stubs/extensions/random.phpstub
  stubs/extensions/redis.phpstub
Labels: release:internal

#8900 Fix remaining invalid unreflectable methods
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#8907 Fix array_merge edge case
  psalm-baseline.xml
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMergeReturnTypeProvider.php
  tests/ArrayFunctionCallTest.php
Labels: release:fix

#8902 fix return type never for static function calls
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php
Labels: release:fix

#8917 doc: `FilterIterator` added to list of built-in templates.
  docs/annotating_code/templated_annotations.md
Labels: release:docs

#8913 Recognize casts from object-with-properties to array
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  tests/CastTest.php
Labels: release:feature

#8918 Fix DOMDocument's propertery name preserveWhiteSpace
  dictionaries/PropertyMap.php
Labels: release:fix

#8910 Last property typehints
  bin/generate_testsuites.php
  bin/update-property-map.php
  phpcs.xml
  src/Psalm/CodeLocation.php
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php
  src/Psalm/Internal/FileManipulation/FunctionDocblockManipulator.php
  src/Psalm/Internal/Fork/ForkProcessErrorMessage.php
  src/Psalm/Report/ByIssueLevelAndTypeReport.php
  src/Psalm/Report/ConsoleReport.php
  src/Psalm/Type/MutableUnion.php
  src/Psalm/Type/Union.php
  tests/CodebaseTest.php
  tests/Config/ConfigFileTest.php
  tests/Config/ConfigTest.php
  tests/Config/Plugin/FileTypeSelfRegisteringPlugin.php
  tests/Config/PluginTest.php
  tests/DocumentationTest.php
  tests/EndToEnd/PsalmEndToEndTest.php
  tests/EndToEnd/PsalmRunnerTrait.php
  tests/FileManipulation/ClassConstantMoveTest.php
  tests/FileManipulation/ClassMoveTest.php
  tests/FileManipulation/FileManipulationTestCase.php
  tests/FileManipulation/MethodMoveTest.php
  tests/FileManipulation/NamespaceMoveTest.php
  tests/FileManipulation/PropertyMoveTest.php
  tests/FileReferenceTest.php
  tests/FunctionLikeDocblockParserTest.php
  tests/Internal/Codebase/ClassConstantByWildcardResolverTest.php
  tests/Internal/Codebase/ClassLikesTest.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
  tests/Internal/Provider/ClassLikeStorageInstanceCacheProvider.php
  tests/Internal/Provider/FakeFileReferenceCacheProvider.php
  tests/Internal/Provider/FileStorageInstanceCacheProvider.php
  tests/Internal/Provider/ParserInstanceCacheProvider.php
  tests/Internal/Provider/ProjectCacheProvider.php
  tests/ProjectCheckerTest.php
  tests/PsalmPluginTest.php
  tests/StubTest.php
  tests/TestCase.php
  tests/TestConfig.php
  tests/TypeReconciliation/ReconcilerTest.php
  tests/UnusedCodeTest.php
  tests/UnusedVariableTest.php
Labels: release:internal

#8916 Remove useless ifs
  examples/plugins/FunctionCasingChecker.php
  examples/plugins/PreventFloatAssignmentChecker.php
  examples/plugins/StringChecker.php
  examples/plugins/composer-based/echo-checker/EchoChecker.php
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/ClassLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/MethodAnalyzer.php
  src/Psalm/Internal/Analyzer/MethodComparator.php
  src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/ArrayAssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/InstancePropertyAssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ArithmeticOpAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArrayFunctionArgumentsAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallProhibitionAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/ExistingAtomicStaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ClassConstAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/InstancePropertyFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/StaticPropertyFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/MagicConstAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/YieldAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/ReturnAnalyzer.php
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  src/Psalm/Internal/Codebase/ClassLikes.php
  src/Psalm/Internal/Codebase/Populator.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/IssueBuffer.php
Labels: release:internal

#8922 Make `sprintf` return `non-empty-string` when possible
  stubs/CoreGenericFunctions.phpstub
  tests/Config/ConfigTest.php
  tests/Config/PluginTest.php
  tests/CoreStubsTest.php
Labels: release:fix

#8924 More array_merge improvements
  psalm-baseline.xml
  src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMergeReturnTypeProvider.php
  stubs/CoreGenericFunctions.phpstub
  tests/ArrayFunctionCallTest.php
Labels: release:fix

#8928 Make md5 return type more precise
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#8929 Fix #8923
  src/Psalm/Internal/Analyzer/ScopeAnalyzer.php
  tests/Loop/DoTest.php
  tests/Loop/ForTest.php
  tests/Loop/WhileTest.php
Labels: release:fix

#8926 Skip intersection of template types during inheritance check
  src/Psalm/Internal/Codebase/Methods.php
  tests/Template/ClassTemplateTest.php
Labels: release:fix

#8930 Fix ReflectionClass stub
  stubs/Reflection.phpstub
Labels: release:fix

#8931 Fix getParentClass stub
  stubs/Reflection.phpstub
Labels: release:fix

#8933 ReflectionClass stub updates
  stubs/Php80.phpstub
  stubs/Reflection.phpstub
  tests/ReflectionTest.php
  tests/Traits/ValidCodeAnalysisTestTrait.php
Labels: release:feature

#8934 Allow conditions inside loops to preserve or narrow int range
  src/Psalm/Internal/Diff/FileDiffer.php
  src/Psalm/Internal/Type/Comparator/ArrayTypeComparator.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  tests/IntRangeTest.php
Labels: release:fix

#8943 More array fixes
  UPGRADING.md
  psalm-baseline.xml
  src/Psalm/Internal/Analyzer/Statements/Block/ForAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/WhileAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/ArrayAssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/IncludeAnalyzer.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayColumnReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMergeReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayRandReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ExplodeReturnTypeProvider.php
  src/Psalm/Internal/Type/TypeCombination.php
  src/Psalm/Internal/Type/TypeCombiner.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  tests/ArrayAccessTest.php
  tests/ArrayFunctionCallTest.php
  tests/ReturnTypeTest.php
  tests/TypeCombinationTest.php
Labels: release:fix

#8955 Fix bug
  src/Psalm/Internal/Codebase/Methods.php
  tests/Template/ClassTemplateExtendsTest.php
Labels: release:fix

#8945 getopt() return type fix
  dictionaries/CallMap.php
  dictionaries/CallMap_71_delta.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#8781 Allow omitting argument offsets for map-type overrides in phpstorm.meta
  src/Psalm/Internal/Scanner/PhpStormMetaScanner.php
  tests/StubTest.php
  tests/fixtures/stubs/phpstorm.meta.php
Labels: release:fix

#8961 Add Codebase to remaining events
  src/Psalm/IssueBuffer.php
  src/Psalm/Plugin/EventHandler/Event/BeforeAddIssueEvent.php
  src/Psalm/Plugin/EventHandler/Event/StringInterpreterEvent.php
  src/Psalm/Type.php
  tests/StubTest.php
Labels: release:feature

#8966 Update BCC
  vendor-bin/bcc/composer.json
Labels: release:internal

#8971 Extend XML enum of supported PHP ext
  config.xsd
Labels: release:fix

#8972 Revert #8955
  src/Psalm/Internal/Codebase/Methods.php
  tests/Template/ClassTemplateExtendsTest.php
Labels: release:fix

#8974 (mb_)chr returns a non-empty-string
  dictionaries/CallMap.php
  dictionaries/CallMap_72_delta.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#8967 Remove occurrences from error baseline
  phpcs.xml
  psalm-baseline.xml
  src/Psalm/ErrorBaseline.php
  tests/ErrorBaselineTest.php
Labels: release:fix

#8976 Add DateTimeInterface::__serialize and __unserialize
  dictionaries/CallMap.php
  dictionaries/CallMap_82_delta.php
Labels: release:fix

#8973 Fix get_object_vars on enums
  composer.json
  src/Psalm/Internal/Codebase/Populator.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/GetObjectVarsReturnTypeProvider.php
  stubs/Php81.phpstub
  tests/ReturnTypeProvider/GetObjectVarsTest.php
Labels: release:fix

#8988 Drop symfony/polyfill-php80 dependency
  composer.json
  src/Psalm/Internal/CliUtils.php
  src/Psalm/Type/MutableUnion.php
  src/Psalm/Type/Union.php
Labels: release:internal

#8792 Fixes vimeo#8112
  src/Psalm/Internal/Type/Comparator/ObjectComparator.php
  tests/Template/ClassTemplateExtendsTest.php
  tests/Template/NestedTemplateTest.php
Labels: release:fix

#8990 Verify nullable callmap parameters
  .github/workflows/ci.yml
  .github/workflows/windows-ci.yml
  dictionaries/CallMap.php
  dictionaries/CallMap_71_delta.php
  dictionaries/CallMap_72_delta.php
  dictionaries/CallMap_74_delta.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/CallMapTest.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#8996 Improve `invalid references` message in `@psalm-type`
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
Labels: release:fix

#8997 Fix missing version in PHARs build on GA
  .github/workflows/build-phar.yml
Labels: release:fix

#9002 forbidden function bug and better get_defined_functions() signature
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NamedFunctionCallHandler.php
  tests/ForbiddenCodeTest.php
Labels: release:fix

#9000 restrictReturnTypes configuration documentation
  docs/running_psalm/configuration.md
  psalm.xml.dist
Labels: release:docs

#9007 Add imap_is_open() to PHP 8.2 dictionary
  dictionaries/CallMap.php
  dictionaries/CallMap_82_delta.php
Labels: internal stubs/callmap, release:fix

#9009 Do not require return type on destructors in interfaces
  src/Psalm/Internal/Analyzer/InterfaceAnalyzer.php
  tests/MethodSignatureTest.php
Labels: release:fix

#9011 feat: add xdebug_info (fixes #8977)
  dictionaries/CallMap.php
  dictionaries/CallMap_72_delta.php
Labels: release:fix

#9001 Make `$http_response_header` a non-empty-list
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php
  tests/SuperGlobalsTest.php
Labels: release:fix

#8999 Preserve from_docblock in TypeCombiner
  src/Psalm/Internal/Type/TypeCombiner.php
  src/Psalm/Type/Atomic.php
  tests/TypeReconciliation/RedundantConditionTest.php
Labels: release:fix

#8987 Add @psalm-api annotation
  composer.json
  docs/annotating_code/supported_annotations.md
  docs/running_psalm/issues/PossiblyUnusedMethod.md
  docs/running_psalm/issues/PossiblyUnusedProperty.md
  docs/running_psalm/issues/UnusedClass.md
  docs/running_psalm/issues/UnusedMethod.md
  docs/running_psalm/issues/UnusedProperty.md
  phpunit.xml.dist
  psalm-baseline.xml
  src/Psalm/Config.php
  src/Psalm/DocComment.php
  src/Psalm/Internal/Codebase/ClassLikes.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeDocblockParser.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/Scanner/ClassLikeDocblockComment.php
  src/Psalm/Storage/ClassLikeStorage.php
  tests/UnusedCodeTest.php
Labels: release:feature

#9014 Fix PHPCS trailing comma
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php
Labels: release:internal

#9017 Add getAtomicType to IsNotAClass for proper negation Reconciliation
  src/Psalm/Storage/Assertion/IsAClass.php
  src/Psalm/Storage/Assertion/IsNotAClass.php
  tests/TypeReconciliation/ReconcilerTest.php
Labels: release:fix

#9018 create proper TClosure instead of TNamedObject with a Closure value
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Type/Atomic.php
  src/Psalm/Type/Atomic/TNamedObject.php
  tests/ClosureTest.php
Labels: release:fix

#9019 Prevent DB escaping functions from affecting non-sql taints
  stubs/CoreGenericClasses.phpstub
  stubs/CoreGenericFunctions.phpstub
  tests/TaintTest.php
Labels: release:fix

#9020 Is containedbug
  src/Psalm/Internal/Type/Comparator/KeyedArrayComparator.php
  tests/FunctionCallTest.php
Labels: release:fix

#9016 Refined `explode()` types
  psalm-baseline.xml
  src/Psalm/Internal/Provider/FunctionReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ExplodeReturnTypeProvider.php
  stubs/CoreGenericFunctions.phpstub
  tests/AssertAnnotationTest.php
  tests/FunctionCallTest.php
  tests/TypeReconciliation/IssetTest.php
Labels: release:feature

#9022 Better type inference and type checking for large union types used in array keys/values
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  tests/ArrayFunctionCallTest.php
Labels: release:fix

#9024 fix never return for MethodCalls
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php
Labels: release:fix

#9023 Fix never return union type wrong condition
  src/Psalm/Type.php
Labels: release:fix

#9025 fixes return type issues of methods reported for the wrong file
  src/Psalm/Internal/Codebase/Methods.php
Labels: release:fix

#9021 Non empty reconciliation
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  tests/TypeReconciliation/ReconcilerTest.php
Labels: release:fix

#9033 Fix remaining markdown issues
  docs/annotating_code/type_syntax/array_types.md
  docs/annotating_code/type_syntax/intersection_types.md
  docs/annotating_code/type_syntax/scalar_types.md
  docs/annotating_code/type_syntax/top_bottom_types.md
  docs/annotating_code/type_syntax/utility_types.md
Labels: release:internal

#9030 fix @psalm-scope-this not working with FQCN with leading backslash
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  tests/TypeReconciliation/ScopeTest.php
Labels: release:fix
