Repository vimeo/psalm, pull requests merged in 2022-10, with the labels that each got.

#8537 Fixed function signatures of imap_delete and imap_undelete
  dictionaries/CallMap.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#8542 Add check for class const with reserved word 'class'
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  tests/ClassTest.php
Labels: release:feature

#8553 Update dictionaries for hash ext functions
  dictionaries/CallMap.php
  dictionaries/CallMap_71_delta.php
  dictionaries/CallMap_72_delta.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#8561 More specific superglobals feedback update
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php
Labels: release:fix

#8555 Update Phpredis stubs to return false on failure
  stubs/phpredis.phpstub
Labels: release:fix

#8566 Fix callmap for DOMNode methods
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#8567 Fix MinMaxReturnTypeProvider when handling TDependentListKeys
  src/Psalm/Internal/Provider/ReturnTypeProvider/MinMaxReturnTypeProvider.php
  tests/ReturnTypeProvider/MinMaxReturnTypeProviderTest.php
Labels: release:fix

#8571 Fix #8562
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  tests/BinaryOperationTest.php
Labels: release:fix

#8570 Fix #8569
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  tests/CloneTest.php
Labels: release:fix

#8577 fix mapped property type for DOMNode childNodes
  dictionaries/PropertyMap.php
Labels: release:typo

#8578 Fix #6983 #8564
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php
  src/Psalm/Internal/Analyzer/Statements/Expression/YieldAnalyzer.php
  src/Psalm/Internal/Codebase/Populator.php
  src/Psalm/Internal/LanguageServer/LanguageServer.php
  src/Psalm/Internal/PhpVisitor/YieldTypeCollector.php
  src/Psalm/Storage/ClassLikeStorage.php
  tests/Template/ClassTemplateExtendsTest.php
Labels: release:fix

#8579 Fix template param for SplDoublyLinkedList
  docs/annotating_code/templated_annotations.md
  stubs/SPL.phpstub
  tests/Template/ClassTemplateTest.php
Labels: release:fix

#8585 Add additional checks for concat of non-empty strings to return non-falsy
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php
  src/Psalm/Type.php
  tests/BinaryOperationTest.php
Labels: release:fix

#8583 Correct return type of DateTimeImmutable sub method stub
  stubs/CoreImmutableClasses.phpstub
  tests/MethodCallTest.php
Labels: release:fix

#8600 fix wrong php version id in $_FILES
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php
Labels: release:fix

#8584 Enhance type detection for internal php functions `key`, `current`, `end` and `reset`
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayPointerAdjustmentReturnTypeProvider.php
  stubs/CoreGenericFunctions.phpstub
  tests/ArrayFunctionCallTest.php
  tests/TypeReconciliation/EmptyTest.php
Labels: release:feature

#8592 #7810/improve reflection stubs
  stubs/Php80.phpstub
  stubs/Reflection.phpstub
Labels: release:fix

#8601 Docs: Fix minor php syntax issues in code examples
  docs/running_psalm/issues/FalsableReturnStatement.md
  docs/running_psalm/issues/TaintedLdap.md
Labels: release:docs

#8605 Fix typo
  docs/running_psalm/issues/PropertyNotSetInConstructor.md
Labels: release:typo

#8586 Fix #8560
  src/Psalm/Internal/Type/TypeExpander.php
  src/Psalm/Type/Atomic/TNamedObject.php
  tests/ClassTest.php
Labels: release:fix

#8594 ensure callbacks have the required number of params
  src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php
  tests/ArgTest.php
  tests/Template/FunctionTemplateTest.php
Labels: release:fix

#8611 Add dirname return type provider
  src/Psalm/Internal/Provider/FunctionReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/DirnameReturnTypeProvider.php
  tests/ReturnTypeProvider/DirnameTest.php
Labels: release:feature

#8614 Add stubs for ext-ffi
  src/Psalm/Config.php
  stubs/extensions/ffi.phpstub
Labels: release:feature

#8620 add basename return type provider
  src/Psalm/Internal/Provider/FunctionReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/BasenameReturnTypeProvider.php
  tests/ReturnTypeProvider/BasenameTest.php
Labels: release:feature

#8622 Update PossiblyFalseReference.md
  docs/running_psalm/issues/PossiblyFalseReference.md
Labels: release:docs

#8619 keep literal string for simple str_replace
  src/Psalm/Internal/Provider/ReturnTypeProvider/StrReplaceReturnTypeProvider.php
  tests/ReturnTypeProvider/DirnameTest.php
Labels: release:fix

#8639 Fix for issue #8631
  stubs/CoreGenericIterators.phpstub
Labels: release:fix
