Repository vimeo/psalm, pull requests merged in 2022-11, with the labels that each got.

#8641 Fix XMLReader::expand() nullable parameter $baseNode
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#8649 Add stubs for ext-random (PHP 8.2)
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Internal/Codebase/InternalCallMapHandler.php
  stubs/extensions/ext-random.phpstub
Labels: release:feature

#8650 Do not report serialize as unused
  src/Psalm/Internal/Codebase/Functions.php
  tests/UnusedCodeTest.php
Labels: release:fix

#8654 Add support for phpstan assertions
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php
Labels: release:feature

#8652 serialize is not pure for array of object
  src/Psalm/Internal/Codebase/Functions.php
  src/Psalm/Internal/TypeVisitor/CanContainObjectTypeVisitor.php
  src/Psalm/Type/Union.php
  tests/UnusedCodeTest.php
Labels: release:fix

#8644 Fix Spl file handling signatures
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#8658 Mark hash_update functions as impure
  src/Psalm/Internal/Codebase/Functions.php
Labels: release:fix

#8665 Fix #8664
  src/Psalm/Internal/Analyzer/Statements/Expression/ClassConstAnalyzer.php
  tests/ConstantTest.php
Labels: release:fix

#8666 Remove `argc` and `argv` elements from `$_ENV`
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php
  tests/SuperGlobalsTest.php
Labels: release:fix

#8670 Fix #8669
  src/Psalm/Internal/Type/AssertionReconciler.php
  tests/TypeReconciliation/TypeTest.php
Labels: release:fix

#8676 Fix assert testing callmap return types
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:internal

#8677 adding openssl_x509_verify
  dictionaries/CallMap.php
  dictionaries/CallMap_74_delta.php
  dictionaries/CallMap_80_delta.php
Labels: release:fix

#8678 Add support for phpstan-param-out
  src/Psalm/Internal/Scanner/DocblockParser.php
Labels: release:feature

#8655 Fix return type of ReflectionExtension::getVersion
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#8681 Making `json_encode()` always produce a `non-empty-string`, when successful
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  stubs/CoreGenericFunctions.phpstub
Labels: release:fix

#8684 Merge 4.x and documentation fixes
  dictionaries/CallMap.php
  dictionaries/CallMap_74_delta.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_82_delta.php
  dictionaries/CallMap_historical.php
  docs/annotating_code/type_syntax/array_types.md
  docs/annotating_code/type_syntax/object_types.md
  docs/annotating_code/type_syntax/other_types.md
  docs/annotating_code/type_syntax/scalar_types.md
  docs/annotating_code/type_syntax/top_bottom_types.md
  docs/annotating_code/type_syntax/utility_types.md
  docs/annotating_code/type_syntax/value_types.md
  src/Psalm/Internal/Clause.php
  src/Psalm/Internal/Codebase/Functions.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayPointerAdjustmentReturnTypeProvider.php
  src/Psalm/Internal/Scanner/DocblockParser.php
  src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php
  src/Psalm/Internal/TypeVisitor/CanContainObjectTypeVisitor.php
  src/Psalm/Type/TypeVisitor.php
  src/Psalm/Type/UnionTrait.php
  stubs/CoreGenericFunctions.phpstub
  stubs/CoreGenericIterators.phpstub
  stubs/Php80.phpstub
  stubs/Reflection.phpstub
  tests/ArgTest.php
  tests/ArrayFunctionCallTest.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
  tests/SuperGlobalsTest.php
  tests/Template/FunctionTemplateTest.php
  tests/TypeReconciliation/EmptyTest.php
  tests/UnusedCodeTest.php
Labels: release:internal

#8685 Last-minute docufix
  docs/annotating_code/type_syntax/array_types.md
Labels: release:docs

#8687 Emit `DeprecatedInterface` when interface is referenced in a generic
  src/Psalm/Internal/TypeVisitor/TypeChecker.php
  tests/DeprecatedAnnotationTest.php
Labels: release:fix

#8691 Prevent array{a: Foo} going cleanly into array<Foo>
  phpcs.xml
  src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/ArrayAssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ArithmeticOpAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  src/Psalm/Internal/Analyzer/Statements/UnsetAnalyzer.php
  src/Psalm/Internal/Codebase/ConstantTypeResolver.php
  src/Psalm/Internal/Codebase/Methods.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayFilterReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMapReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMergeReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayPopReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/GetObjectVarsReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ParseUrlReturnTypeProvider.php
  src/Psalm/Internal/Type/AssertionReconciler.php
  src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php
  src/Psalm/Internal/Type/Comparator/KeyedArrayComparator.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  src/Psalm/Internal/Type/TypeCombiner.php
  src/Psalm/Internal/Type/TypeExpander.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  src/Psalm/Type/Reconciler.php
  src/Psalm/Type/Union.php
  tests/ArrayAccessTest.php
  tests/PropertiesOfTest.php
  tests/ReturnTypeProvider/GetObjectVarsTest.php
  tests/Template/PropertiesOfTemplateTest.php
  tests/TypeReconciliation/ReconcilerTest.php
Labels: release:fix, release:internal

#8698 Removing list
  docs/running_psalm/issues/PossiblyNullArgument.md
Labels: release:docs

#8697 Fix PSL e2e tests
  bin/psl-psalm-plugin.diff
  bin/test-with-real-projects.sh
  src/Psalm/Type/Union.php
Labels: release:internal

#8694 Allow enum cases to reference constants
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  tests/EnumTest.php
Labels: release:fix

#8692 Mark inferred mutation-free constructor as such
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  tests/ClassTest.php
Labels: release:fix

#8688 Make `stringable-object` equivalent to `Stringable`
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/MbInternalEncodingReturnTypeProvider.php
  src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Type/Atomic/TObjectWithProperties.php
  tests/ArrayFunctionCallTest.php
  tests/FunctionCallTest.php
  tests/MethodCallTest.php
  tests/ReturnTypeTest.php
Labels: release:fix

#8693 Flag invalid enum case value types
  docs/running_psalm/issues/InvalidEnumCaseValue.md
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  tests/EnumTest.php
Labels: release:fix

#8699 Cleanup outdated comment
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
Labels: release:typo

#8700 Add extra types to Memcache::getExtendedStats and Memcached::getStats
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#8702 Cleanup documentation
  docs/annotating_code/type_syntax/atomic_types.md
  docs/annotating_code/type_syntax/intersection_types.md
  docs/annotating_code/type_syntax/object_types.md
  docs/annotating_code/type_syntax/utility_types.md
  docs/running_psalm/configuration.md
  docs/running_psalm/plugins/plugins_type_system.md
Labels: release:internal

#8705 Add support for type aliases in @psalm-assert(-*) annotations
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
  tests/TypeAnnotationTest.php
Labels: release:fix

#8710 safe delete cache directory files
  src/Psalm/Config.php
Labels: release:internal

#8709 add --no-progress to psalter
  src/Psalm/Internal/Cli/Psalter.php
Labels: release:feature

#8717 Fix DateTimeZone::listAbbreviations return type
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#8713 Reject `@psalm-consistent-constructor` in function docblocks
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php
  tests/FunctionLikeDocblockParserTest.php
Labels: release:fix

#8708 Allow using imported types in other types within the same file
  src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php
  tests/TypeAnnotationTest.php
Labels: release:fix

#8707 improve cache flush debug info and code if cache disabled
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
Labels: release:internal

#8714 Fix cache race condition due to missing repopulation of lock files cache
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Internal/Provider/FileReferenceCacheProvider.php
Labels: release:internal

#8723 Allow `new` on objects
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php
  tests/ClassTest.php
Labels: release:feature

#8724 include CLI args in PHP errors to more quickly identify run issues in CI
  src/Psalm/Internal/Cli/LanguageServer.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Cli/Psalter.php
  src/Psalm/Internal/Cli/Refactor.php
  src/Psalm/Internal/ErrorHandler.php
Labels: release:internal

#8731 Allow parameter types to be contained by a class template type
  src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php
  tests/Template/FunctionTemplateTest.php
Labels: release:fix

#8737 Enforce arrow function formatting
  phpcs.xml
  src/Psalm/Internal/Analyzer/MethodComparator.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMapReturnTypeProvider.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
Labels: release:internal

#8736 Simplify issue sorting
  src/Psalm/IssueBuffer.php
Labels: release:internal

#8729 Fix dictionary for strip_tags
  dictionaries/CallMap.php
  dictionaries/CallMap_74_delta.php
  dictionaries/CallMap_80_delta.php
Labels: release:fix

#8742 Correct `Clause::$hash` type
  src/Psalm/Internal/Clause.php
Labels: release:internal

#8739 Fix #8735: IntlDateFormatter CallMaps.
  dictionaries/CallMap.php
  dictionaries/CallMap_71_delta.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#8751 Fix #8743
  src/Psalm/Internal/Type/TypeParser.php
Labels: release:internal

#8749 Fix #8748
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallPurityAnalyzer.php
  tests/MagicPropertyTest.php
Labels: release:fix

#8753 Fix #8745
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  src/Psalm/Storage/Assertion/IsGreaterThan.php
  src/Psalm/Storage/Assertion/IsGreaterThanOrEqualTo.php
  src/Psalm/Storage/Assertion/IsLessThan.php
  src/Psalm/Storage/Assertion/IsLessThanOrEqualTo.php
  tests/TypeReconciliation/ConditionalTest.php
Labels: release:fix

#8755 Switch from `phpspec/prophecy` to `mockery/mockery`
  composer.json
  psalm.xml.dist
  src/Psalm/Config.php
  src/Psalm/Type/MutableUnion.php
  tests/Config/PluginListTest.php
  tests/ErrorBaselineTest.php
  tests/PsalmPluginTest.php
Labels: release:internal

#8752 Test CI on 8.2
  .github/workflows/shepherd.yml
  composer.json
Labels: release:internal

#8763 Simplify assertions generated by an array_key_exists check
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  tests/TypeReconciliation/ArrayKeyExistsTest.php
Labels: release:fix

#8754 improve docs and phrasing about NoValue
  docs/running_psalm/issues/NoValue.md
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/ReturnAnalyzer.php
Labels: release:docs

#8766 Suppress errors when validation regexps
  src/Psalm/Config/FileFilter.php
Labels: release:fix

#8770 Upgrade `humbug/box`
  bin/build-phar.sh
  box.json.dist
  scoper.inc.php
  src/Psalm/Internal/Cli/Plugin.php
  src/Psalm/Internal/CliUtils.php
  src/Psalm/Internal/VersionUtils.php
  vendor-bin/box/composer.json
Labels: release:fix

#8769 Move mockery plugin to require-dev
  composer.json
Labels: release:internal

#8768 bump lower dependencies
  composer.json
Labels: release:internal

#8762 Add diagnostic message when shape fields are missing
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/ReturnAnalyzer.php
  src/Psalm/Internal/Type/Comparator/KeyedArrayComparator.php
  src/Psalm/Internal/Type/Comparator/TypeComparisonResult.php
  src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php
  tests/ArgTest.php
Labels: release:internal

#8777 Move mockery to require-dev too
  composer.json
Labels: release:internal

#8780 Replace all references to static variables when moving class
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/StaticPropertyFetchAnalyzer.php
  tests/FileManipulation/ClassMoveTest.php
Labels: release:fix

#8779 Variables should outlive namespaces
  src/Psalm/Internal/Analyzer/NamespaceAnalyzer.php
  tests/Config/ConfigTest.php
  tests/NamespaceTest.php
Labels: release:fix

#8783 Bump `slevomat/coding-standard`
  composer.json
Labels: release:internal

#8782 Check runtime requirements
  src/Psalm/Internal/Cli/LanguageServer.php
  src/Psalm/Internal/Cli/Plugin.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Cli/Psalter.php
  src/Psalm/Internal/Cli/Refactor.php
  src/Psalm/Internal/CliUtils.php
Labels: release:fix

#8788 Fix crashes when XML report is used on PHP 8.1
  src/Psalm/Report/XmlReport.php
Labels: release:fix

#8790 [Docs] Conditional types - remove unfinished sentence
  docs/annotating_code/type_syntax/conditional_types.md
Labels: release:docs

#8794 Ignore non-existing classes during initial scan of intersection types
  src/Psalm/Type.php
Labels: release:fix

#8796 handle true/false reconciliation consistently, fix #8795
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
Labels: release:fix
