Repository vimeo/psalm, pull requests merged in 2022-01, with the labels that each got.

#7247 Fixes #7246, wrap getTypeContextAtPosition in try/catch
  src/Psalm/Internal/LanguageServer/Server/TextDocument.php
Labels: release:fix

#7260 forbid calling impure callable in immutable context
  src/Psalm/Context.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  tests/PureAnnotationTest.php
  tests/Template/ClassTemplateTest.php
Labels: release:fix

#7261 Improve negated reconciliation logic
  psalm-baseline.xml
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  src/Psalm/Internal/Type/TypeExpander.php
Labels: release:internal

#7263 revert #7054
  src/Psalm/Internal/Analyzer/Statements/Expression/ExpressionIdentifier.php
  src/Psalm/Type/Reconciler.php
Labels: release:fix

#7259 Template and variable types inference for methods marked with psalm-if-this-is
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php
  tests/IfThisIsTest.php
Labels: release:feature

#7255 [Feat]: Initial Support for LSP Code Actions
  src/Psalm/Internal/LanguageServer/LanguageServer.php
  src/Psalm/Internal/LanguageServer/Server/TextDocument.php
  src/Psalm/Internal/LanguageServer/Server/Workspace.php
Labels: release:feature

#7264 Increase composer timeout
  tests/EndToEnd/PsalmEndToEndTest.php
Labels: release:internal

#7256 Remove "is not in project" warnings
  src/Psalm/Internal/LanguageServer/Server/TextDocument.php
Labels: release:fix

#7252 Allow assertions on mutable object properties.
  docs/annotating_code/supported_annotations.md
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  tests/AssertAnnotationTest.php
Labels: release:feature

#7019 Disallow ksorting lists
  config.xsd
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/RedundantFunctionCall.md
  docs/running_psalm/issues/RedundantFunctionCallGivenDocblockType .md
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NamedFunctionCallHandler.php
  src/Psalm/Issue/RedundantFunctionCall.php
  src/Psalm/Issue/RedundantFunctionCallGivenDocblockType.php
  tests/ArrayAssignmentTest.php
  tests/Template/ClassTemplateTest.php
Labels: release:feature

#7265 Deprecated `Codebase::$php_major_version` and `Codebase::$php_minor_version` properties
  psalm-baseline.xml
  src/Psalm/Codebase.php
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
Labels: release:deprecation

#7266 Report missing file path properly
  src/Psalm/Config/FileFilter.php
Labels: release:fix

#7239 Move from deprecated Composer 1 to Composer 2 runtime api
  composer.json
  psalm.xml.dist
  scoper.inc.php
  src/Psalm/Internal/Cli/Plugin.php
  src/Psalm/Internal/CliUtils.php
Labels: release:internal

#6705 remove support for allowPhpstormGenerics
  config.xsd
  docs/running_psalm/configuration.md
  src/Psalm/Codebase.php
  src/Psalm/Config.php
  src/Psalm/Internal/Codebase/Populator.php
  src/Psalm/Internal/Type/TypeCombiner.php
  tests/AnnotationTest.php
Labels: release:removed

#6808 remove exitFunctions for Psalm5
  config.xsd
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/ScopeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/ElseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/ElseIfAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/IfAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/SwitchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  tests/Config/ConfigTest.php
Labels: release:removed

#7188 Use InvalidScalarArgument only when we can be sure PHP attempts coercion
  docs/running_psalm/issues/InvalidScalarArgument.md
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  src/Psalm/Internal/Type/Comparator/ScalarTypeComparator.php
  src/Psalm/Internal/Type/Comparator/TypeComparisonResult.php
  tests/AnnotationTest.php
  tests/ArgTest.php
  tests/ArrayAssignmentTest.php
  tests/CallableTest.php
  tests/DocblockInheritanceTest.php
  tests/FunctionCallTest.php
  tests/IncludeTest.php
  tests/MagicMethodAnnotationTest.php
  tests/Template/ClassTemplateExtendsTest.php
  tests/Template/ClassTemplateTest.php
  tests/Template/FunctionTemplateTest.php
Labels: release:fix

#7269 Disable PSL (not yet compatible with Psalm 5)
  .circleci/config.yml
Labels: release:internal

#7270 Drop legacy procedural files
  composer.json
  psalm
  psalm-baseline.xml
  psalm-language-server
  psalm-plugin
  psalm-refactor
  psalm.xml.dist
  psalter
  src/command_functions.php
  src/functions.php
  src/psalm-language-server.php
  src/psalm-refactor.php
  src/psalm.php
  src/psalm_plugin.php
  src/psalter.php
Labels: release:removed

#7272 Dropped removed config entries
  config.xsd
  src/Psalm/Config.php
Labels: release:removed

#7271 uniqid() returns a non-empty-string
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#7275 Dropped legacy plugin API
  UPGRADING.md
  psalm.xml.dist
  src/Psalm/Internal/EventDispatcher.php
  src/Psalm/Internal/Provider/FunctionExistenceProvider.php
  src/Psalm/Internal/Provider/FunctionParamsProvider.php
  src/Psalm/Internal/Provider/FunctionReturnTypeProvider.php
  src/Psalm/Internal/Provider/MethodExistenceProvider.php
  src/Psalm/Internal/Provider/MethodParamsProvider.php
  src/Psalm/Internal/Provider/MethodReturnTypeProvider.php
  src/Psalm/Internal/Provider/MethodVisibilityProvider.php
  src/Psalm/Internal/Provider/PropertyExistenceProvider.php
  src/Psalm/Internal/Provider/PropertyTypeProvider.php
  src/Psalm/Internal/Provider/PropertyVisibilityProvider.php
  src/Psalm/IssueBuffer.php
  src/Psalm/Plugin/Hook/AfterAnalysisInterface.php
  src/Psalm/Plugin/Hook/AfterClassLikeAnalysisInterface.php
  src/Psalm/Plugin/Hook/AfterClassLikeExistenceCheckInterface.php
  src/Psalm/Plugin/Hook/AfterClassLikeVisitInterface.php
  src/Psalm/Plugin/Hook/AfterCodebasePopulatedInterface.php
  src/Psalm/Plugin/Hook/AfterEveryFunctionCallAnalysisInterface.php
  src/Psalm/Plugin/Hook/AfterExpressionAnalysisInterface.php
  src/Psalm/Plugin/Hook/AfterFileAnalysisInterface.php
  src/Psalm/Plugin/Hook/AfterFunctionCallAnalysisInterface.php
  src/Psalm/Plugin/Hook/AfterFunctionLikeAnalysisInterface.php
  src/Psalm/Plugin/Hook/AfterMethodCallAnalysisInterface.php
  src/Psalm/Plugin/Hook/AfterStatementAnalysisInterface.php
  src/Psalm/Plugin/Hook/BeforeFileAnalysisInterface.php
  src/Psalm/Plugin/Hook/FunctionExistenceProviderInterface.php
  src/Psalm/Plugin/Hook/FunctionParamsProviderInterface.php
  src/Psalm/Plugin/Hook/FunctionReturnTypeProviderInterface.php
  src/Psalm/Plugin/Hook/MethodExistenceProviderInterface.php
  src/Psalm/Plugin/Hook/MethodParamsProviderInterface.php
  src/Psalm/Plugin/Hook/MethodReturnTypeProviderInterface.php
  src/Psalm/Plugin/Hook/MethodVisibilityProviderInterface.php
  src/Psalm/Plugin/Hook/PropertyExistenceProviderInterface.php
  src/Psalm/Plugin/Hook/PropertyTypeProviderInterface.php
  src/Psalm/Plugin/Hook/PropertyVisibilityProviderInterface.php
  src/Psalm/Plugin/Hook/StringInterpreterInterface.php
  src/Psalm/PluginRegistrationSocket.php
  tests/Config/PluginTest.php
Labels: release:removed

#7274 pdo: more precise generic type
  stubs/pdo.phpstub
Labels: release:fix

#7276 Dropped deprecated `CodeIssue` methods
  UPGRADING.md
  src/Psalm/Issue/CodeIssue.php
Labels: release:removed

#7277 Dropped deprecated `TypeAnalyzer` methods
  src/Psalm/Internal/Analyzer/TypeAnalyzer.php
Labels: release:internal

#7278 Dropped deprecated `DocComment` methods
  UPGRADING.md
  src/Psalm/DocComment.php
Labels: release:removed

#7279 Trim baseline selection
  src/Psalm/ErrorBaseline.php
Labels: release:fix

#7280 Moved `getPsalmHelpText()` to `Cli\Psalm`
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/CliUtils.php
Labels: release:internal

#7281 Dropped `html-escaped-string` docs
  docs/annotating_code/type_syntax/scalar_types.md
Labels: release:docs

#7284 Deprecated `THtmlEscapedString`
  psalm-baseline.xml
  src/Psalm/Type/Atomic/THtmlEscapedString.php
Labels: release:deprecation

#7285 Dropped `THtmlEscapedString`
  UPGRADING.md
  docs/running_psalm/plugins/plugins_type_system.md
  examples/plugins/composer-based/echo-checker/EchoChecker.php
  psalm-baseline.xml
  src/Psalm/Internal/Type/Comparator/ScalarTypeComparator.php
  src/Psalm/Internal/Type/TypeTokenizer.php
  src/Psalm/Type/Atomic.php
  src/Psalm/Type/Atomic/THtmlEscapedString.php
  tests/Config/PluginTest.php
Labels: release:removed

#7286 resolve ClassConstant for both sides in isContainedBy
  src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php
Labels: release:fix

#7287 Identify ints from TClassConstant when checking for LiteralEquality
  src/Psalm/Internal/Type/AssertionReconciler.php
Labels: release:fix

#7288 resolve type alias and class const on UnionTypeComparator
  src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php
  tests/ConstantTest.php
Labels: release:fix

#7290 Drop orphaned token
  src/Psalm/Internal/Type/TypeTokenizer.php
  tests/TypeComparatorTest.php
Labels: release:removed

#7291 Bump PHP version to 7.4
  .github/workflows/ci.yml
  composer.json
  psalm.xml.dist
  src/spl_object_id.php
  tests/ClosureTest.php
  tests/FunctionCallTest.php
  tests/Traits/InvalidCodeAnalysisTestTrait.php
  tests/Traits/ValidCodeAnalysisTestTrait.php
  tests/TypeReconciliation/ConditionalTest.php
Labels: release:removed

#7292 Replaced deprecated `webmozart/path-util`
  composer.json
  src/Psalm/Config.php
  src/Psalm/Internal/Cli/Psalm.php
Labels: release:internal

#7293 Fix parse_url() return type
  src/Psalm/Internal/Provider/ReturnTypeProvider/ParseUrlReturnTypeProvider.php
  tests/FunctionCallTest.php
Labels: release:fix

#7294 Indent heredoc
  src/Psalm/Internal/Cli/LanguageServer.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Cli/Psalter.php
  src/Psalm/Internal/Cli/Refactor.php
Labels: release:internal

#7300 Dropped dead code based on PHP_VERSION_ID
  tests/EndToEnd/PsalmEndToEndTest.php
Labels: release:internal

#7299 Apply literal number separator rector
  examples/TemplateScanner.php
  phpcs.xml
  src/Psalm/Codebase.php
  src/Psalm/Config.php
  src/Psalm/Internal/Algebra.php
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/MethodComparator.php
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/ElseIfAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php
  src/Psalm/Internal/Cli/LanguageServer.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Cli/Psalter.php
  src/Psalm/Internal/CliUtils.php
  src/Psalm/Internal/Fork/Pool.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php
  src/Psalm/Internal/Provider/StatementsProvider.php
  src/Psalm/Internal/Stubs/Generator/StubsGenerator.php
  src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php
  src/Psalm/IssueBuffer.php
  src/Psalm/PluginRegistrationSocket.php
  src/Psalm/Progress/DefaultProgress.php
  src/Psalm/Type/Atomic.php
  src/Psalm/Type/Atomic/TAnonymousClassInstance.php
  src/Psalm/Type/Atomic/TBool.php
  src/Psalm/Type/Atomic/TCallableObject.php
  src/Psalm/Type/Atomic/TFloat.php
  src/Psalm/Type/Atomic/TGenericObject.php
  src/Psalm/Type/Atomic/TInt.php
  src/Psalm/Type/Atomic/TIterable.php
  src/Psalm/Type/Atomic/TMixed.php
  src/Psalm/Type/Atomic/TNamedObject.php
  src/Psalm/Type/Atomic/TObject.php
  src/Psalm/Type/Atomic/TString.php
  src/Psalm/Type/Atomic/TVoid.php
  src/Psalm/Type/Union.php
  tests/AlgebraTest.php
  tests/CommandFunctions/GetMemoryLimitInBytesTest.php
  tests/Config/ConfigTest.php
  tests/FileDiffTest.php
Labels: release:internal

#7302 Applied NullCoalescingOperatorRector
  phpcs.xml
  src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/ExistingAtomicStaticCallAnalyzer.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMergeReturnTypeProvider.php
Labels: release:internal

#7303 Applied JsonThrowOnErrorRector
  src/Psalm/Config.php
  src/Psalm/Config/Creator.php
  src/Psalm/Context.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Clause.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/CliUtils.php
  src/Psalm/Internal/Codebase/TaintFlowGraph.php
  src/Psalm/Internal/ExecutionEnvironment/BuildInfoCollector.php
  src/Psalm/Internal/PluginManager/PluginListFactory.php
  src/Psalm/Internal/Provider/ParserCacheProvider.php
  src/Psalm/Plugin/Shepherd.php
  src/Psalm/Type/Reconciler.php
  tests/ComposerLockTest.php
  tests/ReportOutputTest.php
Labels: release:internal

#7310 Applied ListToArrayDestructRector
  phpcs.xml
  src/Psalm/Internal/PhpTraverser/CustomTraverser.php
Labels: release:internal

#7313 replace `array<never, never>` as a way to detect empty arrays by a dedicated method
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  src/Psalm/Type/Atomic.php
  src/Psalm/Type/Union.php
Labels: release:internal

#7311 don't crash when pushing a template to in_array
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  tests/AssertAnnotationTest.php
Labels: release:fix

#7317 Issue #6618: All reflection classes should implement Reflector.
  stubs/Reflection.phpstub
Labels: release:fix

#7312 Support PHPStan notation for empty-arrays
  src/Psalm/Internal/Type/ParseTreeCreator.php
  src/Psalm/Internal/Type/TypeParser.php
  tests/AnnotationTest.php
  tests/TypeParseTest.php
Labels: release:feature

#7309 fix empty string not quoted in keyed array offset
  src/Psalm/Type/Atomic/TKeyedArray.php
  tests/AssertAnnotationTest.php
Labels: release:fix

#7321 Prevented crashes on `array_map(...)`
  src/Psalm/Internal/PhpVisitor/Reflector/ExpressionScanner.php
  tests/ClosureTest.php
Labels: release:fix

#7325 Fix analysis when __invoke() exists
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  tests/CallableTest.php
Labels: release:fix

#7324 Issue #7243: Do not throw exception on xinclude with fallbacks
  src/Psalm/Config.php
  tests/Config/ConfigTest.php
Labels: release:fix

#7331 Update return type of iterator_count and iterator_apply functions to 0|positive-int
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#7335 Errors on superior/inferior reconciliation
  psalm-baseline.xml
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  src/Psalm/Type/Atomic/TIntRange.php
  src/Psalm/Type/Reconciler.php
  src/Psalm/Type/Union.php
  tests/IntRangeTest.php
  tests/PureAnnotationTest.php
Labels: release:feature, release:fix

#7336 replace empty checks on Union with dedicated method
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayFilterReturnTypeProvider.php
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  src/Psalm/Type/Reconciler.php
Labels: release:internal

#7337 replace class name by full FQN for scoper
  src/Psalm/Internal/Cli/Plugin.php
  src/Psalm/Internal/CliUtils.php
Labels: release:fix

#7340 Simplify object comparison
  src/Psalm/Internal/Type/Comparator/ObjectComparator.php
  src/Psalm/Type.php
  tests/Template/FunctionTemplateTest.php
Labels: release:internal

#7349 Seal the array inferred for hrtime
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
Labels: release:fix

#7350 set the is_list flag for the array inferred for hrtime
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
  tests/FunctionCallTest.php
Labels: release:fix

#7347 Fix dir Callmap
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#7348 refactor the TooFewArguments check to start checking with named arguments
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  tests/ArgTest.php
  tests/FunctionCallTest.php
Labels: release:fix

#7355 Fix faulty Config tests
  tests/Config/ConfigTest.php
Labels: release:internal

#7326 allow short closure to return never
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/ScopeAnalyzer.php
  tests/ClosureTest.php
Labels: release:fix

#7356 keep class-strings through array_merge
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMergeReturnTypeProvider.php
  tests/ArrayFunctionCallTest.php
Labels: release:fix

#7358 Rename was_static property to is_static to be more accurate
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/ClosureAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ClassConstFetchAnalyzer.php
  src/Psalm/Internal/Type/AssertionReconciler.php
  src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php
  src/Psalm/Internal/Type/Comparator/GenericTypeComparator.php
  src/Psalm/Internal/Type/Comparator/ObjectComparator.php
  src/Psalm/Internal/Type/TypeCombiner.php
  src/Psalm/Internal/Type/TypeExpander.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Type.php
  src/Psalm/Type/Atomic/GenericTrait.php
  src/Psalm/Type/Atomic/TAnonymousClassInstance.php
  src/Psalm/Type/Atomic/TNamedObject.php
  src/Psalm/Type/Union.php
Labels: release:internal

#7360 Document BC breaks in #7358
  UPGRADING.md
Labels: release:docs

#7366 fix: pass static class name to ReturnTypeAnalyzer
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  tests/ReturnTypeTest.php
Labels: release:fix

#7354 Support multiple <issueHandlers> elements
  src/Psalm/Config.php
  tests/Config/ConfigTest.php
Labels: release:fix

#7242 PHP 8.2: seal all properties configuration
  config.xsd
  docs/running_psalm/configuration.md
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  tests/MagicPropertyTest.php
Labels: release:feature

#7163 Add explicit `resolveSymlinks` option for project directories
  config.xsd
  src/Psalm/Config/FileFilter.php
  tests/Config/ConfigTest.php
Labels: release:internal

#7368 Fix closure to have storage bug in codeAction
  src/Psalm/Internal/LanguageServer/LanguageServer.php
  src/Psalm/Internal/LanguageServer/Server/TextDocument.php
Labels: release:fix

#7373 Fix typo in documentation filename
  docs/running_psalm/issues/RedundantFunctionCallGivenDocblockType.md
Labels: release:docs

#7374 Fix @covers annotation.
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:internal

#7383 Add test for issues.md to ensure all documented issues are listed.
  bin/generate_issues_list_doc.php
  docs/running_psalm/issues.md
  docs/running_psalm/issues/ComplexFunction.md
  docs/running_psalm/issues/ComplexMethod.md
  tests/DocumentationTest.php
Labels: release:internal

#7304 Refactor Reconciler::handleLiteralEquality
  src/Psalm/Internal/Type/AssertionReconciler.php
  tests/IntRangeTest.php
Labels: release:fix, release:internal

#7397 remove psl analysis from CI
  .circleci/config.yml
Labels: release:internal

#6902 deprecate forbidEcho
  config.xsd
  docs/running_psalm/issues/ForbiddenEcho.md
  src/Psalm/Config.php
Labels: release:deprecation

#6521 TCallableString is non-falsy (0 can't be a functionlike name)
  src/Psalm/Type/Atomic/TCallableString.php
Labels: release:internal

#7398 use Reconciler::RECONCILIATION_*
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Type/AssertionReconciler.php
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
Labels: release:internal

#7399 Prevent NoValue when there is no phpdoc
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
Labels: release:fix

#7391 Handle inherited docblock method
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MissingMethodCallHandler.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  tests/MagicMethodAnnotationTest.php
Labels: release:fix

#7385 Add support of template for docblock methods
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MissingMethodCallHandler.php
  tests/Template/ClassTemplateTest.php
Labels: release:feature

#7384 Catch additional InvalidArgumentException
  src/Psalm/Internal/LanguageServer/Server/TextDocument.php
Labels: release:fix

#7400 Combine positive int and range
  src/Psalm/Internal/Type/TypeCombiner.php
  tests/IntRangeTest.php
Labels: release:fix

#7401 Psalm can't be sure get_object_vars will return an empty array unless object is known AND final
  src/Psalm/Internal/Provider/ReturnTypeProvider/GetObjectVarsReturnTypeProvider.php
  tests/ReturnTypeProvider/GetObjectVarsTest.php
Labels: release:fix

#7403 support @readonly for promoted properties
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  tests/ReadonlyPropertyTest.php
Labels: release:fix

#7405 Fix `self` parsing for `psalm-if-this-is` and `psalm-self-out`
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
  tests/IfThisIsTest.php
Labels: release:fix

#7406 Improve signature of random_bytes()
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#7071 Try to provide literal int types when possible (fixes #6966)
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  src/Psalm/Internal/Provider/FunctionReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/RoundReturnTypeProvider.php
  tests/FunctionCallTest.php
  tests/TypeReconciliation/ValueTest.php
Labels: release:feature

#7407 Improve signature of DOMDocument::loadXML()
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  src/Psalm/Config.php
  src/Psalm/Config/Creator.php
  src/Psalm/Internal/PluginManager/ConfigFile.php
  tests/Config/ConfigTest.php
  tests/Config/PluginTest.php
  tests/MethodCallTest.php
Labels: release:fix

#7426 Fix kafka stubs
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#7432 Fix Incomplete return type for mb_split() function
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#7430 Resolve generics of inherited pseudo methods
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MissingMethodCallHandler.php
  src/Psalm/Internal/Codebase/Populator.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Storage/ClassLikeStorage.php
  tests/MagicMethodAnnotationTest.php
Labels: release:feature

#7429 Added documentation for baseline files
  docs/running_psalm/dealing_with_code_issues.md
Labels: release:docs

#7363 PHP 8.1: Report missing typehints in overridden native methods
  config.xsd
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/MethodSignatureMustProvideReturnType.md
  src/Psalm/Internal/Analyzer/MethodComparator.php
  src/Psalm/Issue/MethodSignatureMustProvideReturnType.php
  tests/DocumentationTest.php
  tests/MethodSignatureTest.php
Labels: release:feature

#7420 Remove forbidEcho
  UPGRADING.md
  config.xsd
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/ForbiddenEcho.md
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/Statements/EchoAnalyzer.php
  src/Psalm/Issue/ForbiddenEcho.php
  tests/DocumentationTest.php
  tests/ForbiddenCodeTest.php
Labels: release:removed

#7435 drop phpunit compatibility aliases
  tests/Config/PluginListTest.php
  tests/Config/PluginTest.php
  tests/DocumentationTest.php
  tests/FileUpdates/ErrorAfterUpdateTest.php
  tests/IncludeTest.php
  tests/PsalmPluginTest.php
  tests/TaintTest.php
  tests/TestCase.php
  tests/Traits/InvalidCodeAnalysisTestTrait.php
  tests/UnusedCodeTest.php
  tests/UnusedVariableTest.php
Labels: release:internal

#7442 Allow config to define thread count
  docs/running_psalm/configuration.md
  src/Psalm/Config.php
  src/Psalm/Internal/Cli/Psalm.php
Labels: release:feature

#7437 create a return type provider for mb_internal_encoding
  src/Psalm/Internal/Provider/FunctionReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/MbInternalEncodingReturnTypeProvider.php
Labels: release:fix

#7417 Contextual type inference for high order function arg
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/ExistingAtomicStaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php
  src/Psalm/Internal/Type/Comparator/CallableTypeComparator.php
  tests/CallableTest.php
Labels: release:feature

#7446 fix tests
  tests/CallableTest.php
Labels: release:internal

#7448 Nitpicks
  examples/plugins/FunctionCasingChecker.php
  examples/plugins/PreventFloatAssignmentChecker.php
  examples/plugins/StringChecker.php
  src/Psalm/Codebase.php
  src/Psalm/Internal/Analyzer/AttributeAnalyzer.php
  src/Psalm/Internal/Analyzer/ClosureAnalyzer.php
  src/Psalm/Internal/Analyzer/MethodComparator.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/CliUtils.php
  src/Psalm/Internal/Codebase/ClassLikes.php
  src/Psalm/Internal/Codebase/Methods.php
  src/Psalm/Internal/Codebase/Reflection.php
  src/Psalm/Internal/Codebase/Scanner.php
  src/Psalm/Internal/PhpVisitor/PartialParserVisitor.php
  src/Psalm/Internal/Stubs/Generator/StubsGenerator.php
  src/Psalm/Internal/Type/AssertionReconciler.php
  src/Psalm/Internal/Type/Comparator/ScalarTypeComparator.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/TemplateInferredTypeReplacer.php
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  src/Psalm/Internal/Type/TypeExpander.php
  src/Psalm/IssueBuffer.php
  src/Psalm/Type.php
  src/Psalm/Type/Atomic.php
  src/Psalm/Type/Atomic/CallableTrait.php
  src/Psalm/Type/Atomic/GenericTrait.php
  src/Psalm/Type/Atomic/TClassStringMap.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  src/Psalm/Type/Atomic/TList.php
  src/Psalm/Type/Atomic/TObjectWithProperties.php
  src/Psalm/Type/Reconciler.php
  tests/ClassLikeDocblockParserTest.php
  tests/Template/FunctionClassStringTemplateTest.php
Labels: release:internal

#7449 Array key exists assert both ways
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Codebase/Scanner.php
  tests/TypeReconciliation/ArrayKeyExistsTest.php
Labels: release:fix

#7394 [TypeProvider] Provide argument types during FunctionParamsProviderEvent
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
Labels: release:fix

#7454 feat: Handle native intersection types
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  src/Psalm/Internal/PhpVisitor/Reflector/TypeHintResolver.php
  src/Psalm/Type.php
  tests/BinaryOperationTest.php
  tests/InterfaceTest.php
  tests/NativeIntersectionsTest.php
  tests/NativeUnionsTest.php
  tests/PropertyTypeTest.php
  tests/Template/ClassTemplateExtendsTest.php
  tests/Template/ClassTemplateTest.php
  tests/TypeReconciliation/AssignmentInConditionalTest.php
  tests/TypeReconciliation/RedundantConditionTest.php
  tests/TypeReconciliation/TypeAlgebraTest.php
  tests/UnusedVariableTest.php
Labels: release:feature, PR: Need review

#7301 change nullable for array signature to be equal to param signature
  dictionaries/CallMap.php
  dictionaries/CallMap_73_delta.php
Labels: release:fix, PR: Need work

#7460 handle two more cases of firstClassCallable
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  tests/ClosureTest.php
Labels: release:fix

#7404 improve support for enum_exists
  dictionaries/CallMap.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_historical.php
  docs/annotating_code/type_syntax/atomic_types.md
  docs/annotating_code/type_syntax/scalar_types.md
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NamedFunctionCallHandler.php
  src/Psalm/Internal/Codebase/Functions.php
  src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Internal/Type/TypeTokenizer.php
  src/Psalm/Type/Atomic.php
  src/Psalm/Type/Atomic/TClassString.php
  stubs/Reflection.phpstub
  tests/FunctionCallTest.php
Labels: release:feature, PR: Need work

#7455 !!! Deprecate \Psalm\Plugin\RegistrationInterface methods
  psalm-baseline.xml
  src/Psalm/Plugin/RegistrationInterface.php
  src/Psalm/PluginRegistrationSocket.php
Labels: PR: Need review

#7110 Fix stub parent class not loaded.
  UPGRADING.md
  src/Psalm/Internal/Analyzer/ClassLikeAnalyzer.php
  src/Psalm/Internal/Codebase/Populator.php
  src/Psalm/Storage/ClassLikeStorage.php
  tests/StubTest.php
  tests/fixtures/stubs/CircularReference.phpstub
Labels: release:fix, PR: Need review

#7463 fix code where the offset was wrong
  src/Psalm/Internal/Codebase/Properties.php
  src/Psalm/Internal/Codebase/Reflection.php
Labels: release:fix

#7466 Mark loadXdebugStub as deprecated (removed in #7107).
  config.xsd
  psalm-baseline.xml
  src/Psalm/Config.php
Labels: release:deprecation

#7467 fix internal properties on interfaces
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  tests/EnumTest.php
Labels: release:fix

#7470 reconcile two arrays by intersecting them
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
Labels: release:fix

#7472 remove TPositiveInt usage for TIntRange
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArrayFunctionArgumentsAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ConstFetchAnalyzer.php
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Storage/Assertion/IsNotPositiveNumeric.php
  src/Psalm/Storage/Assertion/IsPositiveNumeric.php
  src/Psalm/Type/Atomic.php
  tests/ClosureTest.php
  tests/FunctionCallTest.php
  tests/IntRangeTest.php
  tests/Template/ClassTemplateExtendsTest.php
  tests/TypeCombinationTest.php
  tests/TypeReconciliation/ConditionalTest.php
Labels: release:internal

#7474 deprecate TPositiveInt
  psalm-baseline.xml
  src/Psalm/Type.php
  src/Psalm/Type/Atomic/TPositiveInt.php
Labels: release:deprecation

#7473 remove TPositiveInt
  UPGRADING.md
  docs/running_psalm/plugins/plugins_type_system.md
  psalm-baseline.xml
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ArithmeticOpAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/UnaryPlusMinusAnalyzer.php
  src/Psalm/Internal/Diff/AstDiffer.php
  src/Psalm/Internal/Diff/FileDiffer.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayFillReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/MinMaxReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/RandReturnTypeProvider.php
  src/Psalm/Internal/Type/AssertionReconciler.php
  src/Psalm/Internal/Type/Comparator/IntegerRangeComparator.php
  src/Psalm/Internal/Type/Comparator/ScalarTypeComparator.php
  src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  src/Psalm/Internal/Type/TypeCombiner.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Type.php
  src/Psalm/Type/Atomic.php
  src/Psalm/Type/Atomic/TIntRange.php
  src/Psalm/Type/Atomic/TPositiveInt.php
  src/Psalm/Type/Union.php
  tests/ArrayAccessTest.php
  tests/Loop/ForTest.php
Labels: release:removed

#7431 Add configuration option to disable `@psalm-suppress all`
  config.xsd
  docs/running_psalm/configuration.md
  src/Psalm/Config.php
  src/Psalm/IssueBuffer.php
Labels: release:feature

#7390 Add Exception->getCode() return type provider
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallReturnTypeFetcher.php
  tests/ReturnTypeProvider/ExceptionCodeTest.php
Labels: release:fix, PR: Need work

#7414 Add support of docblock method using parent keyword
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  tests/MagicMethodAnnotationTest.php
  tests/MethodCallTest.php
Labels: release:feature

#7483 Fix `array_replace` type
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMergeReturnTypeProvider.php
  tests/ArrayFunctionCallTest.php
Labels: release:fix

#7123 Support type annotations for class consts (fixes #942).
  config.xsd
  docs/running_psalm/issues.md
  docs/running_psalm/issues/InvalidConstantAssignmentValue.md
  docs/running_psalm/issues/UnresolvableConstant.md
  src/Psalm/Config.php
  src/Psalm/Config/FileFilter.php
  src/Psalm/Config/IssueHandler.php
  src/Psalm/Exception/UnresolvableConstantException.php
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ClassConstFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/TernaryAnalyzer.php
  src/Psalm/Internal/Codebase/ClassLikes.php
  src/Psalm/Internal/Codebase/ConstantTypeResolver.php
  src/Psalm/Internal/Codebase/Reflection.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/TypeExpander.php
  src/Psalm/Issue/ClassConstantIssue.php
  src/Psalm/Issue/CodeIssue.php
  src/Psalm/Issue/InvalidConstantAssignmentValue.php
  src/Psalm/Issue/UnresolvableConstant.php
  src/Psalm/Storage/ClassConstantStorage.php
  tests/ArrayAssignmentTest.php
  tests/Config/ConfigTest.php
  tests/ConstantTest.php
  tests/Template/ClassTemplateExtendsTest.php
  tests/TypeReconciliation/ArrayKeyExistsTest.php
Labels: release:feature, PR: Need review

#7486 Add missing parameter to Phar::getMetadata()
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
Labels: release:fix

#7490 Fix crash due to unresolvable constant.
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Type/TypeExpander.php
Labels: release:fix

#7491 Lock event classes
  UPGRADING.md
  src/Psalm/Plugin/EventHandler/Event/AddRemoveTaintsEvent.php
  src/Psalm/Plugin/EventHandler/Event/AfterAnalysisEvent.php
  src/Psalm/Plugin/EventHandler/Event/AfterClassLikeAnalysisEvent.php
  src/Psalm/Plugin/EventHandler/Event/AfterClassLikeExistenceCheckEvent.php
  src/Psalm/Plugin/EventHandler/Event/AfterClassLikeVisitEvent.php
  src/Psalm/Plugin/EventHandler/Event/AfterCodebasePopulatedEvent.php
  src/Psalm/Plugin/EventHandler/Event/AfterEveryFunctionCallAnalysisEvent.php
  src/Psalm/Plugin/EventHandler/Event/AfterExpressionAnalysisEvent.php
  src/Psalm/Plugin/EventHandler/Event/AfterFileAnalysisEvent.php
  src/Psalm/Plugin/EventHandler/Event/AfterFunctionCallAnalysisEvent.php
  src/Psalm/Plugin/EventHandler/Event/AfterFunctionLikeAnalysisEvent.php
  src/Psalm/Plugin/EventHandler/Event/AfterMethodCallAnalysisEvent.php
  src/Psalm/Plugin/EventHandler/Event/AfterStatementAnalysisEvent.php
  src/Psalm/Plugin/EventHandler/Event/BeforeFileAnalysisEvent.php
  src/Psalm/Plugin/EventHandler/Event/FunctionExistenceProviderEvent.php
  src/Psalm/Plugin/EventHandler/Event/FunctionParamsProviderEvent.php
  src/Psalm/Plugin/EventHandler/Event/FunctionReturnTypeProviderEvent.php
  src/Psalm/Plugin/EventHandler/Event/MethodExistenceProviderEvent.php
  src/Psalm/Plugin/EventHandler/Event/MethodParamsProviderEvent.php
  src/Psalm/Plugin/EventHandler/Event/MethodReturnTypeProviderEvent.php
  src/Psalm/Plugin/EventHandler/Event/MethodVisibilityProviderEvent.php
  src/Psalm/Plugin/EventHandler/Event/PropertyExistenceProviderEvent.php
  src/Psalm/Plugin/EventHandler/Event/PropertyTypeProviderEvent.php
  src/Psalm/Plugin/EventHandler/Event/PropertyVisibilityProviderEvent.php
  src/Psalm/Plugin/EventHandler/Event/StringInterpreterEvent.php
Labels: release:removed

#7154 Improve class constant static analysis
  config.xsd
  docs/running_psalm/issues.md
  docs/running_psalm/issues/AmbiguousConstantInheritance.md
  docs/running_psalm/issues/LessSpecificClassConstantType.md
  docs/running_psalm/issues/OverriddenInterfaceConstant.md
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/InterfaceAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ClassConstAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  src/Psalm/Issue/AmbiguousConstantInheritance.php
  src/Psalm/Issue/LessSpecificClassConstantType.php
  src/Psalm/Issue/OverriddenInterfaceConstant.php
  src/Psalm/Issue/TaintedInput.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  src/Psalm/Type/Atomic/TList.php
  src/Psalm/Type/Atomic/TNonEmptyList.php
  tests/ConstantTest.php
  tests/DocumentationTest.php
Labels: release:feature, PR: Need review

#7339 Add support for references and improve UnusedVariable checks (fixes #7254).
  UPGRADING.md
  config.xsd
  docs/running_psalm/issues.md
  docs/running_psalm/issues/ReferenceReusedFromConfusingScope.md
  src/Psalm/Codebase.php
  src/Psalm/Context.php
  src/Psalm/Internal/Analyzer/ClosureAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/DoAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfConditionalAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/ElseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/ElseIfAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/IfAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/SwitchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/SwitchCaseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/ArrayAssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/InstancePropertyAssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/AndAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/OrAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NamedFunctionCallHandler.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/MatchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/TernaryAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/GlobalAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/UnsetAnalyzer.php
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  src/Psalm/Internal/Diff/FileStatementsDiffer.php
  src/Psalm/Internal/Diff/NamespaceStatementsDiffer.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayFilterReturnTypeProvider.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  src/Psalm/Internal/Type/TypeExpander.php
  src/Psalm/Issue/ReferenceReusedFromConfusingScope.php
  src/Psalm/Type/Reconciler.php
  src/Psalm/Type/Union.php
  tests/AnnotationTest.php
  tests/AssertAnnotationTest.php
  tests/FileManipulation/UnusedVariableManipulationTest.php
  tests/ReferenceConstraintTest.php
  tests/ReferenceTest.php
  tests/TypeReconciliation/ConditionalTest.php
  tests/UnusedVariableTest.php
Labels: release:feature, PR: Need review

#7494 Deprecate template_extended_count
  psalm-baseline.xml
  src/Psalm/Storage/ClassLikeStorage.php
Labels: release:deprecation

#7489 Bugfix/#6151 typedoesnotcontainnull on return value from dom import simplexml
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#7501 BugFix: Made DOMNode::nodeValue nullable
  dictionaries/PropertyMap.php
Labels: release:fix

#7503 Fix failing case for const analyzer.
  .github/workflows/ci.yml
  .github/workflows/windows-ci.yml
  src/Psalm/Internal/Analyzer/Statements/Expression/ClassConstAnalyzer.php
  tests/ConstantTest.php
Labels: release:fix

#7504 InternalTaintSinkMap: Add `getimagesize` as SSRF sink
  dictionaries/InternalTaintSinkMap.php
Labels: release:feature

#7506 Fix side effect when loading config
  src/Psalm/Config.php
  tests/Config/ConfigTest.php
Labels: release:fix

#7107 Enable extensions based on composer.json instead of those loaded at runtime (fixes #5482).
  .github/workflows/ci.yml
  .github/workflows/windows-ci.yml
  UPGRADING.md
  config.xsd
  dictionaries/InternalTaintSinkMap.php
  docs/running_psalm/configuration.md
  psalm-baseline.xml
  src/Psalm/Config.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/PdoStatementReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/PdoStatementSetFetchMode.php
  stubs/extensions/decimal.phpstub
  stubs/extensions/dom.phpstub
  stubs/extensions/ds.phpstub
  stubs/extensions/geos.phpstub
  stubs/extensions/gmp.phpstub
  stubs/extensions/mongodb.phpstub
  stubs/extensions/mysqli.phpstub
  stubs/extensions/pdo.phpstub
  stubs/extensions/soap.phpstub
  stubs/extensions/xdebug.phpstub
  stubs/pdo.phpstub
  tests/BinaryOperationTest.php
  tests/ClassTest.php
  tests/Config/ConfigFileTest.php
  tests/MethodCallTest.php
  tests/MethodSignatureTest.php
  tests/TestConfig.php
Labels: release:feature, PR: Need review

#7471 Function dynamic storage provider
  docs/running_psalm/plugins/authoring_plugins.md
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  src/Psalm/Internal/Codebase/Functions.php
  src/Psalm/Internal/Provider/DynamicFunctionStorageProvider.php
  src/Psalm/Plugin/ArgTypeInferer.php
  src/Psalm/Plugin/DynamicFunctionStorage.php
  src/Psalm/Plugin/DynamicTemplateProvider.php
  src/Psalm/Plugin/EventHandler/DynamicFunctionStorageProviderInterface.php
  src/Psalm/Plugin/EventHandler/Event/DynamicFunctionStorageProviderEvent.php
  src/Psalm/PluginRegistrationSocket.php
  tests/Config/Plugin/Hook/CustomArrayMapFunctionStorageProvider.php
  tests/Config/Plugin/StoragePlugin.php
  tests/Config/PluginTest.php
Labels: release:feature, PR: Need review

#7511 improve literal inequality with ranges and rework GreaterThan/LessThan assertions
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArrayFunctionArgumentsAnalyzer.php
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  src/Psalm/Storage/Assertion/IsGreaterThan.php
  src/Psalm/Storage/Assertion/IsGreaterThanOrEqualTo.php
  src/Psalm/Storage/Assertion/IsLessThan.php
  src/Psalm/Storage/Assertion/IsLessThanOrEqualTo.php
  tests/BinaryOperationTest.php
  tests/IntRangeTest.php
Labels: release:fix

#7484 Remove mic-drop hack from if analysis
  src/Psalm/Context.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfConditionalAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/ElseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/IfAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/AndAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/OrAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/IncDecExpressionAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php
  src/Psalm/Internal/Codebase/VariableUseGraph.php
  src/Psalm/Internal/Scope/IfScope.php
  tests/Loop/DoTest.php
  tests/TypeReconciliation/ConditionalTest.php
  tests/TypeReconciliation/RedundantConditionTest.php
  tests/TypeReconciliation/TypeAlgebraTest.php
  tests/UnusedVariableTest.php
Labels: release:fix, release:internal

#7522 Update .gitattributes
  .gitattributes
Labels: release:internal

#6970 fix some iterator stubs
  stubs/CoreGenericIterators.phpstub
  tests/GeneratorTest.php
  tests/Template/ClassTemplateExtendsTest.php
Labels: release:fix, PR: Need review

#6789 ❗Allow plugins to modify Config::$fileExtensions early
  UPGRADING.md
  docs/running_psalm/checking_non_php_files.md
  docs/running_psalm/plugins/authoring_plugins.md
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Plugin/FileExtensionsInterface.php
  src/Psalm/Plugin/PluginEntryPointInterface.php
  src/Psalm/Plugin/PluginFileExtensionsInterface.php
  src/Psalm/Plugin/PluginInterface.php
  src/Psalm/Plugin/RegistrationInterface.php
  src/Psalm/PluginFileExtensionsSocket.php
  src/Psalm/PluginRegistrationSocket.php
  tests/Config/ConfigTest.php
  tests/Config/Plugin/FileTypeSelfRegisteringPlugin.php
Labels: release:feature, PR: Need review

#7525 Fix for Exception->getCode return type provider
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallReturnTypeFetcher.php
  tests/ReturnTypeProvider/ExceptionCodeTest.php
Labels: release:fix

#7517 Fix empty array
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  src/Psalm/Internal/Type/TypeCombiner.php
  tests/ArrayAssignmentTest.php
Labels: release:fix

#7532 [TASK] Add AfterFunctionLikeAnalysisEvent::getFunctionlikeStorage
  src/Psalm/Internal/EventDispatcher.php
  src/Psalm/Plugin/EventHandler/Event/AfterFunctionLikeAnalysisEvent.php
Labels: release:deprecation, release:fix

#7533 add back empty keyword
  src/Psalm/Type/Atomic.php
Labels: release:fix

#7538 Fix ExceptionCodeTest provider shape
  tests/ReturnTypeProvider/ExceptionCodeTest.php
Labels: release:internal

#7526 [TASK] Add AfterFunctionLikeAnalysisEvent::getFunctionlikeStorage
  UPGRADING.md
  src/Psalm/Plugin/EventHandler/Event/AfterFunctionLikeAnalysisEvent.php
Labels: release:removed

#7535 [FEATURE] Introduce BeforeStatementAnalysisEvent
  docs/running_psalm/plugins/authoring_plugins.md
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  src/Psalm/Internal/EventDispatcher.php
  src/Psalm/Plugin/EventHandler/BeforeStatementAnalysisInterface.php
  src/Psalm/Plugin/EventHandler/Event/BeforeStatementAnalysisEvent.php
Labels: release:feature, PR: Need review

#7530 [FEATURE] Allow to intercept adding issue in IssueBuffer
  docs/running_psalm/plugins/authoring_plugins.md
  src/Psalm/Internal/EventDispatcher.php
  src/Psalm/IssueBuffer.php
  src/Psalm/Plugin/EventHandler/BeforeAddIssueInterface.php
  src/Psalm/Plugin/EventHandler/Event/BeforeAddIssueEvent.php
  tests/CodebaseTest.php
Labels: release:feature, PR: Need review

#7492 Ensure all template parameters are specified in all extended|used classlikes
  UPGRADING.md
  docs/running_psalm/issues/InvalidTraversableImplementation.md
  psalm-baseline.xml
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/ClassLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/InterfaceAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Storage/ClassLikeStorage.php
  tests/ArrayAccessTest.php
  tests/ArrayAssignmentTest.php
  tests/AttributeTest.php
  tests/ClassTest.php
  tests/FunctionCallTest.php
  tests/InterfaceTest.php
  tests/Loop/ForeachTest.php
  tests/MagicMethodAnnotationTest.php
  tests/MethodSignatureTest.php
  tests/MixinAnnotationTest.php
  tests/Php71Test.php
  tests/PropertyTypeInvarianceTest.php
  tests/StubTest.php
  tests/Template/ClassTemplateExtendsTest.php
  tests/Template/ClassTemplateTest.php
  tests/Template/FunctionTemplateTest.php
  tests/Template/TraitTemplateTest.php
  tests/UnusedCodeTest.php
  tests/UnusedVariableTest.php
Labels: release:feature, PR: Need review

#7545 fix wrong detection of purity
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  tests/FileManipulation/PureAnnotationAdditionTest.php
Labels: release:fix

#7542 Fix object constant inference
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  tests/ConstantTest.php
Labels: release:fix
