Repository vimeo/psalm, pull requests merged in 2022-03, with the labels that each got.

#7746 Register openssl_sign function to impure functions
  src/Psalm/Internal/Codebase/Functions.php
Labels: release:fix

#7752 update phpredis stubs
  stubs/phpredis.phpstub
Labels: release:fix

#7758 DateInterval::createFromDateString can be false
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  tests/TypeReconciliation/ValueTest.php
Labels: release:fix

#7759 Allow null to ArrayAccess::offsetSet $offset param
  stubs/CoreGenericClasses.phpstub
  tests/ArrayAssignmentTest.php
Labels: release:fix

#7760 Fix #7750: array_column type inference
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayColumnReturnTypeProvider.php
  tests/ArrayFunctionCallTest.php
Labels: release:fix

#7775 Improve int range parsing
  src/Psalm/Internal/Type/TypeParser.php
  tests/IntRangeTest.php
Labels: release:fix

#7718 Fix #3036: make argument $read of internal PHP function stream_socket nullable.
  stubs/CoreGenericFunctions.phpstub
Labels: release:fix

#7787 restore callable-string Id
  src/Psalm/Type/Atomic/TCallableString.php
Labels: release:fix

#7785 PDOStatement::fetchAll() has incorrect type
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
Labels: release:fix

#7788 More attribute fixes.
  src/Psalm/Internal/Analyzer/AttributesAnalyzer.php
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/InterfaceAnalyzer.php
  src/Psalm/Internal/Analyzer/TraitAnalyzer.php
  src/Psalm/Storage/AttributeStorage.php
  src/Psalm/Storage/HasAttributesInterface.php
  tests/AttributeTest.php
  tests/TestCase.php
Labels: release:fix

#7433 Add configuration for maximum size of shaped array
  config.xsd
  docs/running_psalm/configuration.md
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
Labels: release:feature

#7791 Avoid json_encode when serializing non-UTF8 literals
  src/Psalm/Internal/Clause.php
  tests/TypeReconciliation/ConditionalTest.php
Labels: release:fix

#7798 Add return shape for Throwable::getTrace
  dictionaries/CallMap.php
  dictionaries/CallMap_73_delta.php
  dictionaries/CallMap_historical.php
  stubs/CoreImmutableClasses.phpstub
Labels: release:fix

#7801 Fix disabling of appveyor auto build
  .appveyor.yml
Labels: release:internal

#7812 Fix int-mask-of doc example
  docs/running_psalm/plugins/plugins_type_system.md
  src/Psalm/Type/Atomic/TIntMaskOf.php
Labels: release:docs

#7824 Fix ftp_fget/_fput/_nb_fget/_nb_fput stream arg type
  dictionaries/CallMap.php
  dictionaries/CallMap_81_delta.php
Labels: release:fix

#7829 Fix namespaced min/max int range keyword issue introduced in #7775
  src/Psalm/Internal/Type/TypeParser.php
  tests/IntRangeTest.php
Labels: release:fix
