Repository vimeo/psalm, pull requests merged in 2023-01, with the labels that each got.

#9035 Fix iterator and exception callmaps
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9043 fix DateTime::modify() and DateTimeImmutable::modify() return types
  src/Psalm/Internal/Provider/ReturnTypeProvider/DateTimeModifyReturnTypeProvider.php
  tests/DateTimeTest.php
  tests/MethodCallTest.php
Labels: release:fix

#9047 Fix `ReflectionClass::getModifiers()` stub
  stubs/Reflection.phpstub
Labels: release:fix

#9048 Fix `ReflectionClass::getReflectionConstants()` stub
  stubs/Reflection.phpstub
Labels: release:fix

#9046 Fix `ReflectionClass::getTraitAliases()` stub
  stubs/Reflection.phpstub
Labels: release:fix

#9053 Fix `ReflectionFunctionAbstract::getExtensionName()` stub
  stubs/Php80.phpstub
  stubs/Reflection.phpstub
Labels: release:fix

#9052 Fix `ReflectionMethod::getModifiers()` stub
  stubs/Reflection.phpstub
Labels: release:fix

#9051 Fix `ReflectionClass::getTraitNames()` stub
  stubs/Reflection.phpstub
Labels: release:fix

#9055 Fix `ReflectionClass` stub
  stubs/Reflection.phpstub
Labels: release:fix

#9044 fix autoloader not working with absolute path
  src/Psalm/Config.php
Labels: release:fix

#9063 Internal: use more specific types
  src/Psalm/Internal/Provider/MethodReturnTypeProvider.php
  src/Psalm/Plugin/EventHandler/Event/MethodReturnTypeProviderEvent.php
Labels: release:internal

#9072 Narrow down the return type of DOMXPath::query()
  stubs/extensions/dom.phpstub
Labels: release:fix

#9067 fix `I::cases()` where `interface I extends BackedEnum`
  stubs/Php81.phpstub
  tests/EnumTest.php
Labels: release:fix

#9026 fix implicit return type
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php
  src/Psalm/Internal/Codebase/Methods.php
  src/Psalm/Internal/Type/TypeCombiner.php
  tests/FileManipulation/ReturnTypeManipulationTest.php
  tests/FunctionCallTest.php
  tests/MagicMethodAnnotationTest.php
  tests/StubTest.php
  tests/Template/ClassTemplateExtendsTest.php
  tests/TypeReconciliation/ConditionalTest.php
Labels: release:fix

#9061 Make it more clear what do we test from Psalm output
  tests/ProjectCheckerTest.php
Labels: release:internal

#9088 Internal cleanup: Unify syntax for redis.phpstub
  stubs/extensions/redis.phpstub
Labels: release:internal

#9073 Update Call Maps and Signature for get_headers
  dictionaries/CallMap.php
  dictionaries/CallMap_71_delta.php
  dictionaries/CallMap_80_delta.php
  stubs/CoreGenericFunctions.phpstub
  stubs/Php80.phpstub
  tests/FunctionCallTest.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9012 dont report MissingFile error when file_exists is validated beforehand
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NamedFunctionCallHandler.php
  src/Psalm/Internal/Analyzer/Statements/Expression/IncludeAnalyzer.php
Labels: release:fix

#9092 Handle template type on promoted property
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  tests/Template/ClassTemplateTest.php
Labels: release:fix

#9089 Cleanup unsupported extensions message
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
Labels: release:internal

#9095 Additional test and fix when comparing nested templates
  src/Psalm/Internal/Type/Comparator/ObjectComparator.php
  tests/Template/NestedTemplateTest.php
Labels: release:fix

#9105 Update ForbiddenCode.md
  docs/running_psalm/issues/ForbiddenCode.md
Labels: release:docs

#9107 Add missing `int-range` aliases into the list of psalm reserved words
  src/Psalm/Internal/Type/TypeTokenizer.php
  tests/IntRangeTest.php
Labels: release:fix

#9113 Clean up more callmap return types
  dictionaries/CallMap.php
  dictionaries/CallMap_72_delta.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
  tests/TypeReconciliation/ConditionalTest.php
Labels: release:fix

#9115 Infer getDefaultValueConstantName() type when isDefaultValueConstant() is true
  stubs/Reflection.phpstub
Labels: release:fix

#9118 Fix libxml_get_errors() return type
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9126 Support constants in traits
  composer.json
  config.xsd
  docs/running_psalm/issues.md
  docs/running_psalm/issues/ConstantDeclarationInTrait.md
  psalm-baseline.xml
  src/Psalm/Internal/Codebase/Populator.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Issue/ConstantDeclarationInTrait.php
  src/Psalm/Storage/ClassLikeStorage.php
  tests/TraitTest.php
Labels: release:feature

#9117 Allow sebastian/diff 5
  composer.json
Labels: release:internal

#9122 Fix remaining ignored CallMap return types that can be updated
  dictionaries/CallMap.php
  dictionaries/CallMap_74_delta.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9130 Report unused baseline entries
  config.xsd
  docs/running_psalm/configuration.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/UnusedBaselineEntry.md
  psalm-baseline.xml
  psalm.xml.dist
  src/Psalm/Config.php
  src/Psalm/Config/Creator.php
  src/Psalm/Issue/UnusedBaselineEntry.php
  src/Psalm/IssueBuffer.php
  tests/Config/CreatorTest.php
  tests/DocumentationTest.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:feature

#9134 Enhance error output for shepherd
  src/Psalm/Plugin/Shepherd.php
Labels: release:internal

#9139 Fix dom_import_simplexml()
  stubs/extensions/dom.phpstub
  tests/ExtLibxmlStubTest.php
  tests/Traits/InvalidCodeAnalysisTestTrait.php
Labels: release:fix

#9141 Add information on pure-callables to documentation
  docs/annotating_code/type_syntax/callable_types.md
Labels: release:docs

#9085 Fix ReflectionClass::newInstanceArgs() with named parameters
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  stubs/Php80.phpstub
  stubs/Reflection.phpstub
Labels: release:fix

#9156 Indent docblocks in DocComment test
  tests/DocCommentTest.php
Labels: release:internal

#9157 Narrow ->value of enum case(s) to only the possible values
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  tests/EnumTest.php
Labels: release:feature

#9136 Fix shepherd for default domain
  src/Psalm/Internal/Cli/Psalm.php
Labels: release:fix

#9162 Suppress warnings when `--no-output` is specified
  src/Psalm/Config.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Progress/Progress.php
  tests/EndToEnd/PsalmEndToEndTest.php
Labels: release:fix

#9163 HEAD in all caps
  src/Psalm/SourceControl/Git/GitInfo.php
Labels: release:typo

#9164 Check `$this` in static closures
  src/Psalm/Internal/Analyzer/ClosureAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/LanguageServer/Client/TextDocument.php
  src/Psalm/Internal/LanguageServer/ClientHandler.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  src/Psalm/Storage/FunctionStorage.php
  tests/ClosureTest.php
Labels: release:feature

#9184 cdata in baseline
  psalm-baseline.xml
  src/Psalm/ErrorBaseline.php
Labels: release:fix

#9177 Detect duplicate keys in array shapes
  src/Psalm/Internal/Analyzer/CommentAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/Type/TypeParser.php
  tests/TypeParseTest.php
Labels: release:fix

#9135 Unify warning messages for deprecated config variables
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Internal/Cli/Psalm.php
  tests/EndToEnd/PsalmEndToEndTest.php
Labels: release:internal

#8761 #7387 Add asserting non-empty-string by strlen
  psalm-baseline.xml
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  tests/TypeReconciliation/EmptyTest.php
Labels: release:feature
