Repository vimeo/psalm, pull requests merged in 2023-03, with the labels that each got.

#9435 Revert "`array_pop` is impure"
  src/Psalm/Internal/Codebase/Functions.php
  tests/PureAnnotationTest.php
Labels: release:fix

#9438 Update pack() stub
  stubs/Php80.phpstub
Labels: release:fix

#9441 Merge param descriptions when adding or updating types
  src/Psalm/Internal/FileManipulation/FunctionDocblockManipulator.php
  tests/FileManipulation/ParamTypeManipulationTest.php
Labels: release:fix

#9442 Forbid private final methods
  config.xsd
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/PrivateFinalMethod.md
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  src/Psalm/Issue/PrivateFinalMethod.php
  tests/ClassTest.php
Labels: release:feature

#9443 Require `<?php` tag in tests
  tests/Traits/InvalidCodeAnalysisTestTrait.php
  tests/Traits/ValidCodeAnalysisTestTrait.php
Labels: release:internal

#9444 Support for `readonly` classes
  composer.json
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Storage/ClassLikeStorage.php
  tests/ClassTest.php
Labels: release:feature

#9445 PHP 8.2 attributes moved to 8.2 stub
  stubs/CoreGenericClasses.phpstub
  stubs/Php82.phpstub
  tests/AttributeTest.php
  tests/TraitTest.php
Labels: release:fix

#9457 Improce enum case reconciliation
  src/Psalm/Internal/Type/AssertionReconciler.php
  tests/EnumTest.php
Labels: release:fix

#9458 Do not strip the last `)` bracket when parsing phpdoc type aliases.
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  tests/TypeAnnotationTest.php
Labels: release:fix

#9459 Replace package-versions with Composer 2 APIs
  composer.json
  src/Psalm/Internal/VersionUtils.php
Labels: release:fix

#9460 Fix DOM callmaps
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_historical.php
  tests/DateTimeTest.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9466 Don't crash on unary minus overflow
  src/Psalm/Internal/Analyzer/Statements/Expression/UnaryPlusMinusAnalyzer.php
  tests/BinaryOperationTest.php
Labels: release:fix

#9471 Consider new HTML entity en/decode function defaults since PHP 8.1
  src/Psalm/Internal/Provider/AddRemoveTaints/HtmlFunctionTainter.php
Labels: release:feature

#9473 Fix remaining intl callmaps
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9487 Compare list generic params
  src/Psalm/Internal/Analyzer/NamespaceAnalyzer.php
  src/Psalm/Internal/Type/Comparator/KeyedArrayComparator.php
  tests/ReturnTypeTest.php
  tests/TypeComparatorTest.php
Labels: release:fix

#9479 `json_encode()` returns a non-empty-string with `JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE`
  stubs/CoreGenericFunctions.phpstub
  tests/CoreStubsTest.php
Labels: release:feature

#9486 Add `truthy-string` to reserved word list.
  src/Psalm/Internal/Type/TypeTokenizer.php
Labels: release:fix

#9493 Optimize composer caching
  .github/workflows/bcc.yml
  .github/workflows/build-phar.yml
  .github/workflows/ci.yml
  .github/workflows/windows-ci.yml
Labels: CI, release:internal

#9494 Update phar-build to large resource class in config.yml
  .circleci/config.yml
Labels: CI, release:internal

#9492 Refuse to use PHP versions we did not request
  .github/workflows/bcc.yml
  .github/workflows/build-phar.yml
  .github/workflows/ci.yml
  .github/workflows/shepherd.yml
  .github/workflows/windows-ci.yml
Labels: CI, release:internal

#9439 Fix #9433
  src/Psalm/Internal/Type/TypeCombiner.php
  src/Psalm/Type/Reconciler.php
  tests/TypeReconciliation/IssetTest.php
Labels: release:fix

#9474 Add missing array, float, int and bool types to callmaps
  dictionaries/CallMap.php
  dictionaries/CallMap_71_delta.php
  dictionaries/CallMap_72_delta.php
  dictionaries/CallMap_73_delta.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_82_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9406 Make Atomic subclasses consistently call their parent constructors
  src/Psalm/Type/Atomic/CallableTrait.php
  src/Psalm/Type/Atomic/TArray.php
  src/Psalm/Type/Atomic/TCallable.php
  src/Psalm/Type/Atomic/TClassConstant.php
  src/Psalm/Type/Atomic/TClassString.php
  src/Psalm/Type/Atomic/TClassStringMap.php
  src/Psalm/Type/Atomic/TClosure.php
  src/Psalm/Type/Atomic/TConditional.php
  src/Psalm/Type/Atomic/TDependentGetClass.php
  src/Psalm/Type/Atomic/TDependentGetDebugType.php
  src/Psalm/Type/Atomic/TDependentGetType.php
  src/Psalm/Type/Atomic/TDependentListKey.php
  src/Psalm/Type/Atomic/TGenericObject.php
  src/Psalm/Type/Atomic/TIntMask.php
  src/Psalm/Type/Atomic/TIntMaskOf.php
  src/Psalm/Type/Atomic/TIntRange.php
  src/Psalm/Type/Atomic/TIterable.php
  src/Psalm/Type/Atomic/TKeyOf.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  src/Psalm/Type/Atomic/TList.php
  src/Psalm/Type/Atomic/TLiteralFloat.php
  src/Psalm/Type/Atomic/TLiteralInt.php
  src/Psalm/Type/Atomic/TLiteralString.php
  src/Psalm/Type/Atomic/TMixed.php
  src/Psalm/Type/Atomic/TNamedObject.php
  src/Psalm/Type/Atomic/TNonEmptyArray.php
  src/Psalm/Type/Atomic/TNonEmptyList.php
  src/Psalm/Type/Atomic/TObjectWithProperties.php
  src/Psalm/Type/Atomic/TPropertiesOf.php
  src/Psalm/Type/Atomic/TTemplateIndexedAccess.php
  src/Psalm/Type/Atomic/TTemplateKeyOf.php
  src/Psalm/Type/Atomic/TTemplateParam.php
  src/Psalm/Type/Atomic/TTemplateParamClass.php
  src/Psalm/Type/Atomic/TTemplatePropertiesOf.php
  src/Psalm/Type/Atomic/TTemplateValueOf.php
  src/Psalm/Type/Atomic/TTypeAlias.php
  src/Psalm/Type/Atomic/TValueOf.php
Labels: release:internal

#9507 Fix asserted property mangling
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
  tests/AssertAnnotationTest.php
Labels: release:fix

#9504 Fix return type of str_split()
  dictionaries/CallMap.php
  dictionaries/CallMap_82_delta.php
  src/Psalm/Internal/Type/TypeTokenizer.php
  stubs/CoreGenericFunctions.phpstub
  stubs/Php82.phpstub
Labels: release:fix

#9491 Support int separators in docblocks
  src/Psalm/Internal/Type/TypeParser.php
  tests/TypeParseTest.php
Labels: release:feature

#9499 Fix integer overflow in array keys
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayCreationInfo.php
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  tests/ConstantTest.php
  tests/ExpressionTest.php
Labels: release:fix

#9519 Set inside_call for eval expressions
  src/Psalm/Internal/Analyzer/Statements/Expression/EvalAnalyzer.php
  tests/UnusedCodeTest.php
  tests/UnusedVariableTest.php
Labels: release:fix

#9525 Improve json_encode/json_decode functions signatures
  stubs/CoreGenericFunctions.phpstub
  tests/CoreStubsTest.php
Labels: release:fix

#9528 Fix MissingThrowsDocblock when documented interface is extended by thrown exception interface
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  tests/ThrowsAnnotationTest.php
Labels: release:fix

#9497 Fixed #9496
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  tests/TypeAnnotationTest.php
Labels: release:fix

#9538 Prevent assertion leaks from `else`
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/ElseAnalyzer.php
  tests/TypeReconciliation/ConditionalTest.php
Labels: release:fix

#9541 Fixed coercion of mixed into non-empty-mixed
  src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php
  src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php
  tests/TypeComparatorTest.php
Labels: release:fix

#9544 Doc/psalm api on methods
  docs/annotating_code/supported_annotations.md
  tests/UnusedCodeTest.php
Labels: release:docs

#9526 Clean up unreflectable callmap methods
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9555 Add better return type to mysqli fetch_field*
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9568 @property annotations: allow *not* implying @psalm-seal-properties
  config.xsd
  docs/running_psalm/configuration.md
  src/Psalm/Config.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
Labels: release:feature

#9534 Improve PHP8 str_* function signatures
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  stubs/CoreGenericFunctions.phpstub
  tests/CoreStubsTest.php
Labels: release:feature

#9547 [mysql] Add stubs for `mysqli`, `mysqli_result` and `mysqli_stmt` classes
  stubs/extensions/mysqli.phpstub
Labels: release:fix

#9576 Skip gnupg extension in callmap tests
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:internal

#9323 Fix array_unique callmap
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  src/Psalm/Internal/Provider/FunctionReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayUniqueReturnTypeProvider.php
  stubs/CoreGenericFunctions.phpstub
  tests/ArrayFunctionCallTest.php
Labels: release:fix

#9570 Contextual inference for first-class-callable
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  tests/CallableTest.php
Labels: release:feature

#9577 Improve types for range()
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9566 Handle different line endings from baseline.
  src/Psalm/ErrorBaseline.php
  src/Psalm/Internal/LanguageServer/LanguageServer.php
  src/Psalm/IssueBuffer.php
  tests/ErrorBaselineTest.php
  tests/IssueBufferTest.php
Labels: release:fix

#9590 Add CLI help for the error-level option
  src/Psalm/Internal/Cli/Psalm.php
Labels: release:docs
