Repository vimeo/psalm, pull requests merged in 2023-04, with the labels that each got.

#9595 Fix remaining intl, reflection. xml and zip callmaps
  dictionaries/CallMap.php
  dictionaries/CallMap_71_delta.php
  dictionaries/CallMap_72_delta.php
  dictionaries/CallMap_73_delta.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9586 Introduce `value-of` with backed enum cases in assertions
  src/Psalm/Internal/Codebase/ClassConstantByWildcardResolver.php
  src/Psalm/Internal/Codebase/ClassLikes.php
  src/Psalm/Internal/Codebase/StorageByPatternResolver.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/TypeExpander.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Type/Atomic/TValueOf.php
  tests/AssertAnnotationTest.php
  tests/ConstantTest.php
  tests/EnumTest.php
  tests/Internal/Codebase/ClassConstantByWildcardResolverTest.php
Labels: release:feature

#9606 fix coercion detection between two keyed arrays
  src/Psalm/Internal/Type/Comparator/KeyedArrayComparator.php
  tests/FunctionCallTest.php
  tests/ReturnTypeTest.php
  tests/Template/ClassTemplateTest.php
Labels: release:fix

#9608 fix: treat includes starting with '.' and '..' correct
  src/Psalm/Internal/Analyzer/Statements/Expression/IncludeAnalyzer.php
  tests/IncludeTest.php
Labels: release:fix

#9626 Allow enabling mixed issues reporting for error levels > 2.
  src/Psalm/Config.php
  tests/Config/ConfigTest.php
Labels: release:fix

#9599 Introduce callable object intersection
  src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php
  src/Psalm/Internal/Type/Comparator/ObjectComparator.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Type/Atomic/HasIntersectionTrait.php
  src/Psalm/Type/Atomic/TCallableObject.php
  src/Psalm/Type/Atomic/TClosure.php
  src/Psalm/Type/Atomic/TGenericObject.php
  src/Psalm/Type/Atomic/TIterable.php
  src/Psalm/Type/Atomic/TNamedObject.php
  src/Psalm/Type/Atomic/TObjectWithProperties.php
  src/Psalm/Type/Atomic/TUnknownClassString.php
  tests/IntersectionTypeTest.php
  tests/Traits/InvalidCodeAnalysisTestTrait.php
Labels: release:feature

#9630 Preserve `non-empty-string` type when combining literal and numeric strings
  src/Psalm/Internal/Type/TypeCombiner.php
  tests/ArrayAssignmentTest.php
Labels: release:fix

#9629 Do not report required closure arguments as unused
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  tests/Traits/InvalidCodeAnalysisTestTrait.php
  tests/Traits/ValidCodeAnalysisTestTrait.php
  tests/UnusedVariableTest.php
Labels: release:fix

#9632 Fix various db callmaps
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9646 fix: add missing constructor parameter to IteratorIterator
  stubs/CoreGenericIterators.phpstub
Labels: release:fix

#9647 Flatten `match` arm conditions to check conditions independently
  src/Psalm/Internal/Analyzer/Statements/Expression/MatchAnalyzer.php
  tests/MatchTest.php
Labels: release:fix

#9643 Fixed non empty arg issue in array_splice function
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArrayFunctionArgumentsAnalyzer.php
  src/Psalm/Internal/Type/ArrayType.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  tests/ArrayFunctionCallTest.php
Labels: release:fix

#9651 Fix `array_flip` to preserve non-empty array type
  stubs/CoreGenericFunctions.phpstub
  tests/ArrayFunctionCallTest.php
Labels: release:fix

#9623 Contextual inference for const callable
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/HighOrderFunctionArgHandler.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/HighOrderFunctionArgInfo.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php
  tests/CallableTest.php
  tests/Template/ClassTemplateTest.php
Labels: release:feature

#9658 Fix list<T> template replacement
  psalm-baseline.xml
  src/Psalm/Type/Atomic/TKeyedArray.php
  tests/FunctionCallTest.php
Labels: release:fix

#9638 Allow to intersect type alias with non-type-aliases
  psalm-baseline.xml
  src/Psalm/Internal/Type/TypeExpander.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Type/Atomic/CallableTrait.php
  src/Psalm/Type/Atomic/TCallableObject.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  src/Psalm/Type/Atomic/TTypeAlias.php
  tests/IntersectionTypeTest.php
Labels: release:feature

#9655 Provide support for templated `value-of` enum values
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/ExistingAtomicStaticCallAnalyzer.php
  src/Psalm/Internal/Codebase/Methods.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php
  src/Psalm/Type/Atomic/TValueOf.php
  tests/ValueOfTest.php
Labels: release:feature

#9656 (re-)implement object-shape assertions
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Type.php
  tests/Template/FunctionTemplateAssertTest.php
Labels: release:feature

#9660 Fix iterable template replacement
  psalm-baseline.xml
  src/Psalm/Internal/Provider/ClassLikeStorageProvider.php
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  tests/FunctionCallTest.php
Labels: release:fix

#9393 Fix/9373 using enum property as const array key
  src/Psalm/Internal/Codebase/ConstantTypeResolver.php
  src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php
  src/Psalm/Internal/Scanner/UnresolvedConstant/EnumNameFetch.php
  src/Psalm/Internal/Scanner/UnresolvedConstant/EnumPropertyFetch.php
  src/Psalm/Internal/Scanner/UnresolvedConstant/EnumValueFetch.php
  tests/ConstantTest.php
Labels: release:fix

#9663 Specify array share for `stream_context_get_params` return value
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9664 Support anonymous object template replacement
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  src/Psalm/Internal/Type/Comparator/KeyedArrayComparator.php
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  src/Psalm/Type/Atomic/TObjectWithProperties.php
  tests/FunctionCallTest.php
Labels: release:feature

#9673 Fixed crash issue when using multiple literals for array_splice
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArrayFunctionArgumentsAnalyzer.php
  tests/ArrayFunctionCallTest.php
Labels: release:fix

#9670 Avoid verbose opcache logging
  src/Psalm/Internal/Fork/PsalmRestarter.php
Labels: release:internal

#9676 Fix comparison of unions of multiple callables
  src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php
  tests/ArgTest.php
  tests/TypeComparatorTest.php
Labels: release:fix

#9675 Valid array access on a non-empty-string yields a non-empty-string
  src/Psalm/Type/Atomic/TSingleLetter.php
  tests/ArrayAccessTest.php
Labels: release:internal

#9682 Add stub for DateInterval
  stubs/CoreGenericClasses.phpstub
Labels: release:fix

#9678 Return a non-empty-(lowercase-)string from mb_strtolower
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
  src/Psalm/Type/UnionTrait.php
  tests/FunctionCallTest.php
Labels: release:fix

#9679 Don't throw UnnecesseryVarAnnotation when hinting a mixed template var
  src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  src/Psalm/Type/UnionTrait.php
  tests/Template/ClassTemplateTest.php
Labels: release:fix

#9686 Fix is_object assertions on final classes
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  tests/TypeReconciliation/TypeTest.php
Labels: release:fix

#9691 Add return type provider for date/gmdate
  src/Psalm/Internal/Provider/FunctionReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/DateReturnTypeProvider.php
  stubs/CoreGenericFunctions.phpstub
  tests/FunctionCallTest.php
Labels: release:fix

#9685 Avoid wrong assertions when working with objects returned by methods
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php
  tests/AssertAnnotationTest.php
Labels: release:fix

#9701 Handle included directory paths without crashing
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/IncludeAnalyzer.php
  src/Psalm/Internal/Codebase/Scanner.php
  src/Psalm/Internal/Provider/FakeFileProvider.php
  src/Psalm/Internal/Provider/FileProvider.php
  tests/IncludeTest.php
Labels: release:fix

#9700 Contextual closure arg inference for class methods
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  tests/CallableTest.php
Labels: release:fix

#9693 Fix #9692
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  tests/PropertyTypeTest.php
Labels: release:fix

#9694 Implement unsealed array generic syntax
  psalm-baseline.xml
  src/Psalm/Internal/Type/ParseTreeCreator.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Type.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  tests/ArrayAssignmentTest.php
  tests/ArrayFunctionCallTest.php
  tests/FunctionCallTest.php
  tests/ReturnTypeTest.php
  tests/TypeCombinationTest.php
  tests/TypeParseTest.php
Labels: release:feature

#9704 Allow running new on template objects
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php
  tests/ReturnTypeTest.php
Labels: release:fix

#9690 Replace `@template T as X` with `@template T of X` in documentation
  docs/annotating_code/type_syntax/atomic_types.md
  docs/annotating_code/type_syntax/utility_types.md
Labels: release:docs

#9711 Fix date return type provider
  src/Psalm/Internal/Provider/ReturnTypeProvider/DateReturnTypeProvider.php
  tests/FunctionCallTest.php
Labels: release:fix

#9709 Remove clone leftovers from immutable refactoring
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php
Labels: release:internal

#9717 Make it easier to find how to promote Trace
  docs/annotating_code/supported_annotations.md
  docs/running_psalm/issues/Trace.md
Labels: release:docs

#9706 Document @mixin
  docs/annotating_code/supported_annotations.md
Labels: release:docs

#9719 Fix UnevaluatedCode false positive at declare(strict_types=1)
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
Labels: release:fix

#9720 Fix ambiguous constant inheritance false positive
  src/Psalm/Internal/Analyzer/Statements/Expression/ClassConstAnalyzer.php
  tests/ConstantTest.php
Labels: release:fix

#9725 Introduce BeforeExpressionAnalysisEvent
  src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php
  src/Psalm/Internal/EventDispatcher.php
  src/Psalm/Plugin/EventHandler/BeforeExpressionAnalysisInterface.php
  src/Psalm/Plugin/EventHandler/Event/BeforeExpressionAnalysisEvent.php
Labels: release:feature
