Repository vimeo/psalm, pull requests merged in 2023-05, with the labels that each got.

#9681 Add support for @psalm-no-seal-properties and @psalm-no-seal-methods
  docs/annotating_code/supported_annotations.md
  src/Psalm/DocComment.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/InstancePropertyAssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MissingMethodCallHandler.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  src/Psalm/Internal/Codebase/Populator.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeDocblockParser.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/Scanner/ClassLikeDocblockComment.php
  src/Psalm/Storage/ClassLikeStorage.php
  tests/MagicMethodAnnotationTest.php
  tests/MagicPropertyTest.php
Labels: release:feature

#9736 SplDoublyLinkedList's index is always int
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9743 Fix string negation to never
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
  tests/AssertAnnotationTest.php
Labels: release:fix

#9739 Fix ParadoxicalCondition with complex match expression
  src/Psalm/Internal/Analyzer/Statements/Expression/MatchAnalyzer.php
  tests/MatchTest.php
Labels: release:fix

#9735 Fix missing global class type when scanning cached files
  src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php
  tests/Internal/Scanner/FileScannerTest.php
Labels: release:fix

#9750 Fix union argument type check against templated param
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  tests/FunctionCallTest.php
Labels: release:fix

#9742 Allow dynamic properties from PHPDoc
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  src/Psalm/Storage/ClassLikeStorage.php
  tests/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzerTest.php
Labels: release:fix

#9752 improve glob stubs
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  src/Psalm/Config/FileFilter.php
  tests/CallableTest.php
Labels: release:fix

#9687 WIP - Limit inheritance to a subset of classes #1450
  config.xsd
  docs/annotating_code/supported_annotations.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/InheritorViolation.md
  docs/running_psalm/issues/InvalidExtendClass.md
  src/Psalm/DocComment.php
  src/Psalm/Internal/Analyzer/ClassLikeAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeDocblockParser.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/Scanner/ClassLikeDocblockComment.php
  src/Psalm/Issue/InheritorViolation.php
  src/Psalm/Storage/ClassLikeStorage.php
  tests/ClassTest.php
Labels: release:feature

#9779 Enable opcache if it is installed
  src/Psalm/Internal/Cli/Psalm.php
Labels: release:internal

#9780 Documented suggestions for HTML user input
  docs/running_psalm/issues/TaintedHtml.md
  docs/running_psalm/issues/TaintedTextWithQuotes.md
  docs/security_analysis/avoiding_false_positives.md
Labels: release:docs

#9769 UnsupportedPropertyReferenceUsage
  config.xsd
  docs/running_psalm/issues.md
  docs/running_psalm/issues/UnsupportedPropertyReferenceUsage.md
  psalm-baseline.xml
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  src/Psalm/Issue/UnsupportedPropertyReferenceUsage.php
  tests/AssertAnnotationTest.php
  tests/ReferenceTest.php
  tests/UnsupportedPropertyReferenceUsage.php
  tests/UnusedVariableTest.php
Labels: release:feature

#9784 Document array shape unsealing syntax
  docs/annotating_code/type_syntax/array_types.md
Labels: release:docs

#9795 Improve return types of pow()
  src/Psalm/Internal/Provider/FunctionReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/PowReturnTypeProvider.php
  tests/ReturnTypeProvider/PowReturnTypeProviderTest.php
Labels: release:feature

#9796 methods and vars cannot be falsy
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9788 Narrow the type of $haystack when strpos(...) !== false
  stubs/CoreGenericFunctions.phpstub
  tests/CoreStubsTest.php
  tests/FunctionCallTest.php
Labels: release:feature

#9803 fix offset for type param changes
  bin/update-property-map.php
  src/Psalm/Internal/FileManipulation/FunctionDocblockManipulator.php
  tests/FileManipulation/ParamTypeManipulationTest.php
Labels: release:fix

#9805 allow using more than 8G of memory in psalter
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Cli/Psalter.php
  src/Psalm/Internal/CliUtils.php
  tests/CommandFunctions/GetMemoryLimitInBytesTest.php
Labels: release:feature

#9814 glob: allow empty string for pattern
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9813 Add a support for multilevel glob wildcards
  src/Psalm/Config/FileFilter.php
  tests/Config/ConfigTest.php
Labels: release:feature

#9828 GH-9825
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  tests/UnsupportedPropertyReferenceUsage.php
Labels: release:fix

#9833 Fix #9824 const enum self reference
  src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php
  tests/ConstantTest.php
Labels: release:fix

#9829 Mapping closed inheritance to union during assertion
  src/Psalm/Internal/Type/ClosedInheritanceToUnion.php
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
  tests/AssertAnnotationTest.php
Labels: release:feature

#9837 Dirname return type non empty string
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  src/Psalm/Internal/Analyzer/Statements/Expression/IncludeAnalyzer.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/DirnameReturnTypeProvider.php
  tests/ReturnTypeProvider/DirnameTest.php
Labels: release:fix

#9835 Fixed typo in ConstantTest
  tests/ConstantTest.php
Labels: release:typo

#9842 uniqid return type non-empty-string inconsistent
  stubs/CoreGenericFunctions.phpstub
Labels: release:fix

#9848 Use PHPStorm output format by default on JetBrains terminals
  src/Psalm/Internal/Cli/Psalm.php
Labels: release:feature

#9846 Introduce and use `IssueData` constants for severity levels
  src/Psalm/Internal/Analyzer/IssueData.php
  src/Psalm/Internal/Codebase/Analyzer.php
  src/Psalm/Internal/LanguageServer/LanguageServer.php
  src/Psalm/Issue/CodeIssue.php
  src/Psalm/IssueBuffer.php
  src/Psalm/Plugin/Shepherd.php
  src/Psalm/Report.php
  src/Psalm/Report/CompactReport.php
  src/Psalm/Report/EmacsReport.php
  src/Psalm/Report/GithubActionsReport.php
  src/Psalm/Report/JunitReport.php
  src/Psalm/Report/TextReport.php
  tests/ByIssueLevelAndTypeReportTest.php
  tests/ErrorBaselineTest.php
  tests/IssueBufferTest.php
  tests/ReportOutputTest.php
Labels: release:internal
