Repository vimeo/psalm, pull requests merged in 2023-10, with the labels that each got.

#10241 Remove duplicate namespace in InternalMethod error message
  src/Psalm/Issue/InternalClass.php
Labels: release:fix

#10244 Add stream_socket_shutdown socket_shutdown to impure function list
  dictionaries/ImpureFunctionsList.php
Labels: release:fix

#10248 Emit `MethodSignatureMismatch` when descendant does not return by reference
  src/Psalm/Internal/Analyzer/MethodComparator.php
  tests/MethodSignatureTest.php
Labels: release:fix

#10264 Add alias support to psalm-check-type
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  tests/CheckTypeTest.php
Labels: release:feature

#10261 Allow parameter names in callable docblocks with templates
  src/Psalm/Internal/Type/ParseTreeCreator.php
  tests/TypeAnnotationTest.php
Labels: release:feature

#10262 Negated class_exist check on class-string converts to string instead of mixed
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
  tests/ClassLikeStringTest.php
Labels: release:fix

#10268 Hotfix Shepard build
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ArithmeticOpAnalyzer.php
Labels: release:fix

#10266 Disallow `never` type for parameters
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  tests/FunctionCallTest.php
Labels: release:feature

#10254 Fix error message for implicitly returning functions with `never` return type
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php
  tests/ReturnTypeTest.php
Labels: release:fix

#10271 Type check nested templates
  src/Psalm/Internal/TypeVisitor/TypeChecker.php
  tests/CallableTest.php
  tests/Template/FunctionTemplateTest.php
Labels: release:fix

#10270 Fix return of BadSqlTainter::afterExpressionAnalysis()
  docs/security_analysis/custom_taint_sources.md
Labels: release:fix

#10265 Introduce `DuplicateProperty` issue
  config.xsd
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/DuplicateProperty.md
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Issue/DuplicateProperty.php
  tests/ClassTest.php
  tests/TraitTest.php
Labels: release:feature

#10242 Allow tainted numerics except for 'html' and 'has_quotes'
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOpAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  tests/TaintTest.php
Labels: release:fix

#10274 Fix inferring enum case value from a class constant
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  tests/EnumTest.php
Labels: release:fix

#10228 fix: #10080
  src/Psalm/Internal/Diff/ClassStatementsDiffer.php
  tests/Cache/CacheTest.php
Labels: release:fix

#10290 Fix memory explosion with calls to method_exists
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalysisResult.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MissingMethodCallHandler.php
  tests/MethodCallTest.php
Labels: release:fix

#10289 Additional caching fixes
  src/Psalm/Internal/Diff/FileStatementsDiffer.php
  tests/Cache/CacheTest.php
Labels: release:fix

#10277 str_replace / substr_replace signature improvements
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9794 Improved type of callable-array
  UPGRADING.md
  docs/running_psalm/plugins/plugins_type_system.md
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/HighOrderFunctionArgHandler.php
  src/Psalm/Internal/Type/Comparator/CallableTypeComparator.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  src/Psalm/Internal/Type/TypeCombiner.php
  src/Psalm/Type/Atomic.php
  src/Psalm/Type/Atomic/TCallableArray.php
  src/Psalm/Type/Atomic/TCallableKeyedArray.php
  tests/CallableTest.php
  tests/TypeParseTest.php
  tests/TypeReconciliation/ReconcilerTest.php
Labels: release:feature

#10295 Fix method calls and property accesses after extension_loaded
  src/Psalm/Internal/Analyzer/ClassLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/StaticPropertyFetchAnalyzer.php
  tests/UnusedCodeTest.php
Labels: release:fix

#10306 Backport rector fixes to 5.x
  dictionaries/scripts/update_signaturemap_from_other_tool.php
  examples/plugins/ClassUnqualifier.php
  src/Psalm/Codebase.php
  src/Psalm/Internal/Analyzer/ClassLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/CommentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  src/Psalm/Internal/Codebase/Populator.php
  src/Psalm/Internal/FileManipulation/FunctionDocblockManipulator.php
  src/Psalm/Internal/LanguageServer/LanguageServer.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMapReturnTypeProvider.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/TemplateInferredTypeReplacer.php
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/IssueBuffer.php
  src/Psalm/Plugin/EventHandler/Event/AfterMethodCallAnalysisEvent.php
  src/Psalm/Report/ByIssueLevelAndTypeReport.php
  src/Psalm/Report/CountReport.php
  src/Psalm/Storage/FunctionLikeStorage.php
  src/Psalm/Type/Atomic/TClosure.php
  src/Psalm/Type/Atomic/TGenericObject.php
  src/Psalm/Type/Atomic/TValueOf.php
  src/Psalm/Type/UnionTrait.php
  tests/AsyncTestCase.php
  tests/CodebaseTest.php
  tests/Config/ConfigTest.php
  tests/Config/Plugin/Hook/CustomArrayMapFunctionStorageProvider.php
  tests/DocumentationTest.php
  tests/FileDiffTest.php
  tests/TaintTest.php
  tests/TestCase.php
  tests/TypeComparatorTest.php
  tests/fixtures/DestructiveAutoloader/autoloader.php
  tests/fixtures/SuicidalAutoloader/autoloader.php
Labels: release:internal

#10314 Narrow down `get_browser` returning array or object
  stubs/CoreGenericFunctions.phpstub
Labels: release:fix

#10335 Allow Symfony 7
  composer.json
Labels: release:internal
