Repository vimeo/psalm, pull requests merged in 2023-11, with the labels that each got.

#10343 Hotfix shepard build
  src/Psalm/Internal/PluginManager/ComposerLock.php
Labels: release:fix

#10333 Add constants from SOAP extension to stub
  stubs/extensions/soap.phpstub
Labels: release:fix

#10345 Add progress for scanning stage
  src/Psalm/Internal/Codebase/Scanner.php
  src/Psalm/Progress/DefaultProgress.php
  src/Psalm/Progress/LongProgress.php
  src/Psalm/Progress/Progress.php
Labels: release:feature

#10320 Fix auto completion by partial property or method
  src/Psalm/Codebase.php
  src/Psalm/Internal/LanguageServer/Server/TextDocument.php
  tests/LanguageServer/CompletionTest.php
Labels: release:feature

#9787 Incorrectly asserting non-empty-list after combining with empty list
  src/Psalm/Internal/Type/TypeCombiner.php
  tests/ArrayAssignmentTest.php
Labels: release:fix

#10319 Get rid of legacy 7.3 logic
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Fork/Pool.php
Labels: release:internal

#10339 Allow enum cases to be global constants
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  tests/EnumTest.php
Labels: release:feature

#10326 Consistent type docblock parsing
  src/Psalm/Internal/Analyzer/CommentAnalyzer.php
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeDocblockParser.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php
  src/Psalm/Internal/Type/ParseTreeCreator.php
  src/Psalm/Internal/Type/TypeTokenizer.php
  stubs/CoreGenericIterators.phpstub
  stubs/Reflection.phpstub
  tests/AnnotationTest.php
  tests/MethodSignatureTest.php
  tests/Template/TraitTemplateTest.php
  tests/TypeAnnotationTest.php
  tests/TypeParseTest.php
Labels: release:fix

#10340 Fix stub for RecursiveArrayIterator::getChildren
  stubs/CoreGenericIterators.phpstub
Labels: release:fix

#10341 Report unused issue handler suppressions
  config.xsd
  docs/running_psalm/configuration.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/UnusedIssueHandlerSuppression.md
  psalm.xml.dist
  src/Psalm/Config.php
  src/Psalm/Config/ErrorLevelFileFilter.php
  src/Psalm/Config/IssueHandler.php
  src/Psalm/Internal/Codebase/Analyzer.php
  src/Psalm/Issue/UnusedIssueHandlerSuppression.php
  src/Psalm/IssueBuffer.php
  tests/DocumentationTest.php
Labels: release:feature

#10344 Support @(no-)seal-(properties|methods) annotations without prefix
  docs/annotating_code/supported_annotations.md
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeDocblockParser.php
  tests/MagicMethodAnnotationTest.php
  tests/MagicPropertyTest.php
Labels: release:feature

#10263 Maintain loop start val after increment/decrement
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ArithmeticOpAnalyzer.php
  tests/BinaryOperationTest.php
  tests/Loop/ForTest.php
  tests/TypeReconciliation/RedundantConditionTest.php
Labels: release:fix

#10332 Stub constants for ZipArchive from ext-zip
  stubs/extensions/zip.phpstub
Labels: release:feature

#10349 Add documentation for @psalm-flow
  docs/security_analysis/annotations.md
  docs/security_analysis/taint_flow.md
Labels: release:docs

#10355 Allow int keys when calling Redis methods
  stubs/extensions/redis.phpstub
Labels: release:fix

#10351 Add stubs for rdKafka
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  src/Psalm/Config.php
  stubs/extensions/rdkafka.phpstub
Labels: release:feature

#10303 Suppressing NoValue should not treat subsequent code as unevaluated
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  tests/IntRangeTest.php
  tests/UnusedCodeTest.php
Labels: release:feature

#10362 Allow type aliases for static variables
  src/Psalm/Internal/Analyzer/CommentAnalyzer.php
  tests/AnnotationTest.php
Labels: release:feature

#9783 Remove MixedInferredReturnType
  UPGRADING.md
  config.xsd
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/MixedInferredReturnType.md
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php
  src/Psalm/Issue/MixedInferredReturnType.php
  tests/ArrayAssignmentTest.php
  tests/Cache/CacheTest.php
  tests/CallableTest.php
  tests/ClassTest.php
  tests/DocumentationTest.php
  tests/FunctionCallTest.php
  tests/JsonOutputTest.php
  tests/MagicPropertyTest.php
  tests/MethodCallTest.php
  tests/ReferenceConstraintTest.php
  tests/ReportOutputTest.php
  tests/ReturnTypeTest.php
  tests/Template/FunctionClassStringTemplateTest.php
  tests/Template/FunctionTemplateTest.php
  tests/TypeReconciliation/ArrayKeyExistsTest.php
  tests/TypeReconciliation/AssignmentInConditionalTest.php
  tests/TypeReconciliation/ConditionalTest.php
  tests/TypeReconciliation/TypeAlgebraTest.php
  tests/UnusedVariableTest.php
Labels: release:internal

#10356 Inherit magic methods from @mixin
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MissingMethodCallHandler.php
  tests/MixinAnnotationTest.php
Labels: release:feature

#10361 Method annotation fixes
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/InterfaceAnalyzer.php
  src/Psalm/Internal/Analyzer/MethodComparator.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php
  src/Psalm/Internal/Codebase/Methods.php
  src/Psalm/Internal/Codebase/Populator.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  tests/ArrayAssignmentTest.php
  tests/DocblockInheritanceTest.php
  tests/MagicMethodAnnotationTest.php
  tests/MethodSignatureTest.php
Labels: release:fix

#10360 A segment of progress was being output early as the startScanningFile…
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Progress/LongProgress.php
Labels: release:fix

#10385 Finding methods and properties for auto completion feature
  src/Psalm/Codebase.php
  src/Psalm/Internal/Codebase/Populator.php
  tests/Internal/Codebase/MethodGetCompletionItemsForClassishThingTest.php
Labels: release:fix

#10379 update decimal stubs from documented URL
  stubs/extensions/decimal.phpstub
Labels: release:fix

#10389 fix CI "split" unevenly splits the number of tests
  bin/tests-github-actions.sh
Labels: release:internal

#10391 Fix Phar build failure
  .circleci/config.yml
Labels: release:fix

#10393 Doc typo
  docs/running_psalm/issues/TaintedEval.md
  docs/running_psalm/issues/TaintedHtml.md
  docs/running_psalm/issues/TaintedInclude.md
  docs/running_psalm/issues/TaintedShell.md
  docs/running_psalm/issues/TaintedSql.md
  docs/running_psalm/issues/TaintedTextWithQuotes.md
  docs/running_psalm/issues/TaintedXpath.md
Labels: release:docs

#10370 Fix misc callable bugs
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/MethodComparator.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  src/Psalm/Internal/CliUtils.php
  src/Psalm/Internal/LanguageServer/Provider/ClassLikeStorageCacheProvider.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php
  src/Psalm/Internal/Provider/ClassLikeStorageCacheProvider.php
  src/Psalm/Internal/Provider/FileStorageCacheProvider.php
  src/Psalm/Internal/Provider/FunctionParamsProvider.php
  src/Psalm/Internal/Provider/ParamsProvider/ArrayFilterParamsProvider.php
  src/Psalm/Internal/Provider/ParamsProvider/ArrayMultisortParamsProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayFilterReturnTypeProvider.php
  src/Psalm/Internal/Type/Comparator/CallableTypeComparator.php
  src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  src/Psalm/Plugin/EventHandler/Event/FunctionParamsProviderEvent.php
  tests/ArgTest.php
  tests/ArrayAccessTest.php
  tests/ArrayAssignmentTest.php
  tests/ArrayFunctionCallTest.php
  tests/AttributeTest.php
  tests/CallableTest.php
  tests/Internal/Provider/ClassLikeStorageInstanceCacheProvider.php
  tests/MethodSignatureTest.php
  tests/StubTest.php
  tests/Template/ClassTemplateTest.php
  tests/TestCase.php
  tests/Traits/ValidCodeAnalysisTestTrait.php
Labels: release:feature

#10399 Fix #10398: add missing methods of ReflectionProperty class in CallMap and CallMap deltas.
  dictionaries/CallMap.php
  dictionaries/CallMap_74_delta.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_81_delta.php
Labels: release:fix

#10396 Fix circleci builds
  .circleci/config.yml
  bin/test-with-real-projects.sh
Labels: release:internal

#10402 Update MongoDB stubs for 1.17
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#10409 Fix backtick analysis
  dictionaries/PropertyMap.php
  src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php
  tests/ExpressionTest.php
  tests/TaintTest.php
Labels: release:fix

#10408 Declare we do not support document highlighting
  src/Psalm/Internal/LanguageServer/LanguageServer.php
Labels: release:fix

#10415 Improve scan progress
  src/Psalm/Progress/DebugProgress.php
  src/Psalm/Progress/LongProgress.php
Labels: release:internal

#10423 update define types to be correct
  dictionaries/CallMap.php
  dictionaries/CallMap_73_delta.php
  dictionaries/CallMap_historical.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NamedFunctionCallHandler.php
Labels: release:fix

#10424 use branch name to randomize tests to ensure test dependencies will error
  .github/workflows/ci.yml
  bin/tests-github-actions.sh
Labels: release:internal

#10426 Fix at in array keys
  src/Psalm/Internal/Type/ParseTreeCreator.php
  tests/TypeAnnotationTest.php
Labels: release:fix

#10357 Inherit conditional returns
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallReturnTypeFetcher.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/ExistingAtomicStaticCallAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
  tests/Template/ConditionalReturnTypeTest.php
Labels: release:fix
