Repository vimeo/psalm, pull requests merged in 2023-09, with the labels that each got.

#10176 Flag invalid declares
  src/Psalm/Internal/Analyzer/Statements/DeclareAnalyzer.php
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  tests/Internal/Analyzer/DeclareAnalyzerTest.php
Labels: release:feature

#10161 `composer.json` tweaks
  composer.json
Labels: release:internal

#10186 Restore support for namespaced functions in referencedFunction config
  src/Psalm/Config/FileFilter.php
  tests/Config/ConfigTest.php
Labels: release:fix

#10187 `DateTimeZone::getName()` always returns `non-empty-string`
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  stubs/CoreImmutableClasses.phpstub
  tests/PureAnnotationTest.php
Labels: internal stubs/callmap, release:fix

#10190 Narrow `ArrayObject` `TKey` template
  stubs/CoreGenericClasses.phpstub
  tests/ArrayAssignmentTest.php
  tests/ClassTest.php
  tests/Template/ClassTemplateExtendsTest.php
Labels: release:feature

#10209 Only the binary op 'plus' works with two arrays
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ArithmeticOpAnalyzer.php
  tests/BinaryOperationTest.php
Labels: release:fix

#10210 Add openssl_*_export_to_file to impure functions
  dictionaries/ImpureFunctionsList.php
Labels: release:fix

#10214 add FILTER_SANITIZE_URL filter to filter_var
  src/Psalm/Internal/Provider/ReturnTypeProvider/FilterVarReturnTypeProvider.php
Labels: release:fix

#10194 Allow class-string<T> where T is a union
  src/Psalm/Internal/Type/TypeParser.php
  tests/ClassLikeStringTest.php
Labels: release:fix

#10207 Allow object assertions for `mixed` values
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  tests/AssertAnnotationTest.php
Labels: release:feature

#10202 Issue handlers priority
  src/Psalm/Config.php
  tests/Config/ConfigTest.php
Labels: release:feature

#10227 Introduce NonVariableReferenceReturn issue
  config.xsd
  docs/contributing/adding_issues.md
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/NonVariableReferenceReturn.md
  src/Psalm/Internal/Analyzer/Statements/ReturnAnalyzer.php
  src/Psalm/Issue/NonVariableReferenceReturn.php
  tests/ClosureTest.php
  tests/ReturnTypeTest.php
Labels: release:feature

#10234 Check for declare strict_types in block mode
  src/Psalm/Internal/Analyzer/Statements/DeclareAnalyzer.php
  tests/Internal/Analyzer/DeclareAnalyzerTest.php
Labels: release:feature

#10237 Loop over PDOStatement::fetch() arguments
  src/Psalm/Internal/Provider/ReturnTypeProvider/PdoStatementReturnTypeProvider.php
Labels: release:fix

#10189 Inherited assertions v2
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ClassTemplateParamCollector.php
  src/Psalm/Internal/Codebase/AssertionsFromInheritanceResolver.php
  tests/AssertAnnotationTest.php
Labels: release:fix

#10191 Resolve inherited conditional return types
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallReturnTypeFetcher.php
  src/Psalm/Internal/Codebase/Methods.php
  src/Psalm/Internal/Type/TemplateResult.php
  tests/Template/ConditionalReturnTypeTest.php
Labels: release:fix

#10230 feat(LSP): Improve the autocomplete for nested array shape
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  tests/LanguageServer/CompletionTest.php
Labels: release:feature

#10231 Allow stringable objects in `sprintf()` values
  stubs/CoreGenericFunctions.phpstub
  tests/CoreStubsTest.php
  tests/ToStringTest.php
Labels: release:fix

#10183 Detect DoS by sleep vimeo#10178
  UPGRADING.md
  config.xsd
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/TaintedSleep.md
  src/Psalm/Internal/Codebase/TaintFlowGraph.php
  src/Psalm/Issue/TaintedSleep.php
  src/Psalm/Type/TaintKind.php
  src/Psalm/Type/TaintKindGroup.php
  stubs/CoreGenericFunctions.phpstub
  tests/TaintTest.php
Labels: release:feature

#10240 fix: #10239
  src/Psalm/Internal/Diff/FileStatementsDiffer.php
  tests/Cache/CacheTest.php
Labels: release:fix
