Repository vimeo/psalm, pull requests merged in 2023-02, with the labels that each got.

#9210 Fix newly discovered CS issues
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  tests/Internal/CliUtilsTest.php
  tests/ReturnTypeProvider/GetObjectVarsTest.php
  tests/Traits/ValidCodeAnalysisTestTrait.php
  tests/TypeReconciliation/EmptyTest.php
Labels: release:internal

#9212 Fix xmlrpc callmap functions that were dropped in PHP 8.0
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9207 fix `didChange` event in LSP
  src/Psalm/Internal/LanguageServer/Server/TextDocument.php
Labels: release:fix

#9170 Added @psalm-pure to filter_var()
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
  stubs/CoreGenericFunctions.phpstub
  tests/TaintTest.php
Labels: release:fix

#9220 Add DatePeriod::INCLUDE_END_DATE option
  stubs/Php80.phpstub
  stubs/Php82.phpstub
Labels: release:fix

#9228 Add more specific return for class-implements
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9227 Convert callmaps resource types
  dictionaries/CallMap.php
  dictionaries/CallMap_72_delta.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9226 Use "numeric-string" type for some MySQLi properties
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  dictionaries/PropertyMap.php
Labels: release:fix

#9235 find_unused_code CLI arg should not be overwritten by config file
  src/Psalm/Internal/Cli/Psalm.php
Labels: release:fix

#9236 Fixed more CS issues
  src/Psalm/Internal/Algebra.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/AndAnalyzer.php
  tests/TypeReconciliation/TypeAlgebraTest.php
Labels: release:internal

#9237 Always enable JIT
  src/Psalm/Internal/Fork/PsalmRestarter.php
Labels: release:internal

#9234 Allow fidry/cpu-core-counter:v0.5
  composer.json
Labels: release:internal

#9247 Fix divide by a floating point zero
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ArithmeticOpAnalyzer.php
Labels: release:fix

#9250 Don't crash on unknown exceptions in `@throws` docblock
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  tests/ThrowsAnnotationTest.php
Labels: release:fix

#9252 Documentation: Add BackedEnum compatibility to value-of docs
  docs/annotating_code/type_syntax/utility_types.md
Labels: release:docs

#9256 Fix Spoofchecker callmaps
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9257 Fix crashes with invalid `@psalm-check-type` syntax
  psalm-baseline.xml
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  tests/CheckTypeTest.php
Labels: release:fix

#9260 Fix crash when int range boundary is overflown
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  tests/IntRangeTest.php
Labels: release:fix

#9251 Update workflows to use non-deprecated method of setting step output
  .github/workflows/bcc.yml
  .github/workflows/build-phar.yml
  .github/workflows/ci.yml
  .github/workflows/windows-ci.yml
Labels: CI, release:internal

#9266 Drop abandoned mcve m_ functions
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9264 Fix several callmap fuction signatures
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9253 fix lstat bug cache directory race condition
  src/Psalm/Config.php
Labels: release:fix

#9269 Drop removed xsl callmap functions
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9270 Drop abandoned maxdb callmap functions
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9271 Drop abandoned newt callmap functions
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9273 Update callmap types for php 8.2
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_82_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9272 Forbid implementing some interfaces
  config.xsd
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/InvalidInterfaceImplementation.md
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Issue/InvalidInterfaceImplementation.php
  tests/ClassTest.php
  tests/DocumentationTest.php
  tests/EnumTest.php
Labels: release:feature

#9265 Fix opcache being loaded twice
  src/Psalm/Internal/Fork/PsalmRestarter.php
Labels: release:fix

#9280 Forbid overriding built-in enum methods
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/MethodAnalyzer.php
  tests/EnumTest.php
Labels: release:fix

#9278 Fix remaining callmap functions
  dictionaries/CallMap.php
  dictionaries/CallMap_71_delta.php
  dictionaries/CallMap_72_delta.php
  dictionaries/CallMap_73_delta.php
  dictionaries/CallMap_74_delta.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9283 Add curl stubs to prevent crashes
  stubs/Php80.phpstub
Labels: release:fix

#9240 Emit warning if opcache cannot be enabled
  src/Psalm/Internal/Cli/Psalm.php
Labels: release:internal

#9286 Compare enum cases thoroughly
  src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php
  tests/EnumTest.php
Labels: release:fix

#9293 Drop abandoned ncurses extension
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9292 Drop abandoned cairo extension
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9287 Emit issues for calls to `is_a(string, class-string, false)`
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NamedFunctionCallHandler.php
  tests/FunctionCallTest.php
Labels: release:fix

#9297 Made `WeakReference` mutable
  stubs/CoreGenericClasses.phpstub
Labels: release:fix

#9299 Added issue type and psalm.dev link to Emacs report
  src/Psalm/Report/EmacsReport.php
  tests/ReportOutputTest.php
Labels: release:feature

#9300 Add option to skip callmap test
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:internal

#9301 Allow `@var` annotations on global vars
  src/Psalm/Internal/Analyzer/CommentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/GlobalAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/StaticAnalyzer.php
  tests/AnnotationTest.php
Labels: release:feature

#9302 Flag class constant references where LHS is ordinary string
  src/Psalm/Internal/Analyzer/Statements/Expression/ClassConstAnalyzer.php
  tests/ConstantTest.php
  tests/DocumentationTest.php
Labels: release:fix

#9303 Allow suppressing `MissingThrowsDocblock` for individual exceptions
  config.xsd
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Issue/MissingThrowsDocblock.php
Labels: release:feature

#9304 Fixed issue message for missing `@psalm-external-mutation-free`
  src/Psalm/Internal/Analyzer/MethodComparator.php
Labels: release:fix

#9308 Suggest Psalm to be installed in require-dev section
  composer.json
Labels: release:internal

#9311 Flag direct constructor calls
  config.xsd
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/DirectConstructorCall.md
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php
  src/Psalm/Issue/DirectConstructorCall.php
  tests/ClassTest.php
Labels: release:feature

#9312 Deprecate `FunctionLikeStorage::$unused_docblock_params`
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
  src/Psalm/Storage/FunctionLikeStorage.php
Labels: release:deprecation

#9313 Skip verifying callmaps based on name pattern
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:internal

#9309 Fix memcached extension callmap
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9314 Flag docblock parameters that have no counterparts in function signature
  config.xsd
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/UnusedDocblockParam.md
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Issue/UnusedDocblockParam.php
  src/Psalm/Type.php
  tests/UnusedCodeTest.php
Labels: release:feature

#9316 Forbid non-null defaults for callable parameters
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  tests/FunctionCallTest.php
  tests/MethodCallTest.php
Labels: release:feature

#9315 Added a page explaining how to add a new issue type
  docs/contributing/adding_issues.md
  docs/contributing/index.md
Labels: release:docs

#9322 Fix strpos stub return type
  stubs/CoreGenericFunctions.phpstub
Labels: release:fix

#9325 Skip verifying memcache extension callmap
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:internal

#9318 Run assertions on CI
  .github/workflows/shepherd.yml
Labels: release:internal

#9329 Propagate phantom classes to closure context
  src/Psalm/Internal/Analyzer/ClosureAnalyzer.php
  tests/ClosureTest.php
Labels: release:fix

#9331 Allow spatie/array-to-xml v3
  composer.json
  src/Psalm/Report/XmlReport.php
Labels: release:internal

#9326 Disable JIT-incompatible extensions to prevent warnings
  src/Psalm/Internal/Cli/LanguageServer.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Cli/Psalter.php
  src/Psalm/Internal/Fork/PsalmRestarter.php
Labels: release:internal

#9336 Fix language server first-class callable crashes
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  tests/Traits/InvalidCodeAnalysisTestTrait.php
  tests/Traits/ValidCodeAnalysisTestTrait.php
Labels: release:fix

#9338 Forbid first-class callables in `new`
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php
  tests/ClosureTest.php
Labels: release:fix

#9337 Added the test to validate test environment itself
  tests/TestEnvironmentTest.php
Labels: release:internal

#9339 Negated is_numeric narrows scalar type
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  tests/TypeReconciliation/ConditionalTest.php
Labels: release:fix

#9342 Always use 0x7FFEBFFF opcache optimization level (fixes #9340)
  src/Psalm/Internal/Fork/PsalmRestarter.php
Labels: release:fix

#9347 Fix `PsalmRestarter::restart()` signature
  src/Psalm/Internal/Fork/PsalmRestarter.php
Labels: release:fix

#9172 fix (DateTime|DateTimeImmutable)::modify() return types
  src/Psalm/Internal/Provider/ReturnTypeProvider/DateTimeModifyReturnTypeProvider.php
  tests/DateTimeTest.php
  tests/MethodCallTest.php
Labels: release:fix

#9351 Workaround arm64 opcache bug (fixes #9350)
  .github/workflows/ci.yml
  .github/workflows/windows-ci.yml
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php
Labels: release:fix

#9354 Replace use of DOMParentNode::append() with appendChild()
  src/Psalm/ErrorBaseline.php
Labels: release:fix

#9356 Include setrawcookie as an impure function
  src/Psalm/Internal/Codebase/Functions.php
  tests/UnusedCodeTest.php
Labels: release:fix

#9360 Fix several spl callmap methods
  dictionaries/CallMap.php
  dictionaries/CallMap_71_delta.php
  dictionaries/CallMap_73_delta.php
  dictionaries/CallMap_74_delta.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9358 Revert "#7387 Add asserting non-empty-string by strlen"
  psalm-baseline.xml
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  tests/TypeReconciliation/EmptyTest.php
Labels: release:fix

#9364 Workaround opcache issue (fixes #9363)
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php
Labels: release:fix

#9368 FFI stubs improvement
  stubs/extensions/ffi.phpstub
  tests/FFITest.php
Labels: release:feature

#9369 Instances of `object` returned by `db2_*()` functions are always instances of `stdClass`
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9296 [READY] Simplify and fix Shepherd to support custom endpoints for reporting
  psalm-baseline.xml
  src/Psalm/Plugin/Shepherd.php
Labels: release:fix

#9375 Support sizeof alias of count
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
  src/Psalm/Internal/Analyzer/Statements/Expression/MatchAnalyzer.php
  src/Psalm/Internal/Codebase/Functions.php
  tests/ArrayAccessTest.php
Labels: release:feature

#9380 Iterated array in `foreach` body is never empty
  psalm-baseline.xml
  psalm.xml.dist
  src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
  tests/Loop/ForeachTest.php
Labels: release:feature

#9383 Process `@psalm-api` tags on methods
  src/Psalm/Internal/Codebase/ClassLikes.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
  src/Psalm/Internal/Scanner/FunctionDocblockComment.php
  src/Psalm/Storage/FunctionLikeStorage.php
  tests/UnusedCodeTest.php
Labels: release:feature

#9385 Fixes #9384 (Wrong type for variable checked with is_long)
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  tests/TypeReconciliation/TypeTest.php
Labels: release:fix

#9362 Convert callmap associative-array types into proper array types
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9381 Enforce literal string length limit
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/ArrayAssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BitwiseNotAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NamedFunctionCallHandler.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/EncapsulatedStringAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  src/Psalm/Internal/Codebase/ConstantTypeResolver.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/GetObjectVarsReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/VersionCompareReturnTypeProvider.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  src/Psalm/Internal/Type/TypeCombiner.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Type.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  src/Psalm/Type/Atomic/TLiteralString.php
  tests/ConstantTest.php
Labels: release:feature

#9389 Update Phar callmaps
  composer.json
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9390 Correctly process use aliases in `@psalm-scope-this`
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  tests/TypeReconciliation/ScopeTest.php
Labels: release:fix

#9391 Allow `array` as magic method name
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeDocblockParser.php
  src/Psalm/Internal/Type/ParseTreeCreator.php
  tests/MagicMethodAnnotationTest.php
Labels: release:fix

#9392 Consistently report docblock issues on all classlikes
  src/Psalm/Internal/Analyzer/InterfaceAnalyzer.php
  src/Psalm/Internal/Analyzer/TraitAnalyzer.php
  tests/TypeAnnotationTest.php
Labels: release:fix

#9388 Disable `opcache.preload` if it's enabled
  src/Psalm/Internal/Fork/PsalmRestarter.php
Labels: release:fix

#9387 [ibm_db2] Update some return types in callmaps
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9397 Don't crash on empty `jit_buffer_size`
  src/Psalm/Internal/Fork/PsalmRestarter.php
Labels: release:fix

#9310 [ibm_db2] Improve return type inference for `db2_autocommit()`
  config.xsd
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  src/Psalm/Config.php
  stubs/extensions/ibm_db2.phpstub
Labels: internal stubs/callmap, release:feature

#9398 Only disable grpc extension if it is not properly configured
  src/Psalm/Internal/Cli/Psalm.php
Labels: release:feature

#9400 Preserve PossiblyUndefinedVariable when fixing UnusedVariable
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php
  tests/FileManipulation/UnusedVariableManipulationTest.php
Labels: release:fix

#9366 PHP 8.3 dictionary
  dictionaries/CallMap.php
  dictionaries/CallMap_83_delta.php
  src/Psalm/Internal/Codebase/InternalCallMapHandler.php
Labels: release:feature

#9405 Callmap is always non-empty
  dictionaries/InternalTaintSinkMap.php
  psalm-baseline.xml
  src/Psalm/Internal/Codebase/InternalCallMapHandler.php
Labels: release:internal

#9404 [ibm_db2] Update callmaps
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9399 Reorganize pushes to `psalm/phar`
  bin/github-deploy-phar.sh
Labels: CI, release:internal

#9418 Fix #9401
  src/Psalm/Internal/TypeVisitor/TypeChecker.php
  tests/Template/ClassStringMapTest.php
Labels: release:fix

#9422 concat should never remove non empty non falsy from string #9411
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php
  tests/BinaryOperationTest.php
Labels: release:feature

#9420 Fix remaining spl and iterator callmaps
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:fix

#9415 An attempt to fix #4460
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/ArrayAssignmentAnalyzer.php
  tests/Template/ClassStringMapTest.php
Labels: release:fix

#9434 `array_pop` is impure
  src/Psalm/Internal/Codebase/Functions.php
  tests/PureAnnotationTest.php
Labels: release:fix, pure/immutable

#9291 Do not display ext deprecation note when `disableExtensions` used
  src/Psalm/Config.php
  tests/Config/ConfigTest.php
Labels: release:internal
