Repository vimeo/psalm, pull requests merged in 2023-06, with the labels that each got.

#9844 PropertyNotSetInConstructor should not report for abstract constructors
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  tests/PropertyTypeTest.php
Labels: release:fix

#9845 Shepherd: send a list of issues (instead of array with int keys)
  src/Psalm/Plugin/EventHandler/Event/AfterAnalysisEvent.php
  src/Psalm/Plugin/Shepherd.php
Labels: release:internal

#9856 Extend Shepherd payload by information about package versions
  src/Psalm/Plugin/Shepherd.php
Labels: release:feature

#9853 Allow if/false assert for same variable to allow array/list distinction
  src/Psalm/Internal/Algebra.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  tests/AssertAnnotationTest.php
Labels: release:feature

#9865 Intersect template types during inheritance check
  src/Psalm/Internal/Codebase/Methods.php
  src/Psalm/Type.php
  tests/MethodCallTest.php
  tests/ReturnTypeTest.php
Labels: release:fix

#9866 Fix generic type params mapping
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  tests/Template/ClassTemplateTest.php
Labels: release:fix

#9867 Document classAndDescendants configuration tag
  docs/running_psalm/configuration.md
Labels: release:docs

#9880 fix failing mock tests
  .circleci/config.yml
  src/Psalm/Internal/Algebra.php
  src/Psalm/Internal/Fork/Pool.php
  src/Psalm/Internal/Provider/FileReferenceCacheProvider.php
  src/Psalm/Internal/Provider/FileReferenceProvider.php
  src/Psalm/Type/Atomic/TCallableList.php
  src/Psalm/Type/Atomic/TDependentListKey.php
  src/Psalm/Type/Atomic/TList.php
  src/Psalm/Type/Atomic/TNonEmptyList.php
  tests/EndToEnd/SuicidalAutoloaderTest.php
  tests/Template/FunctionClassStringTemplateTest.php
  tests/fixtures/SuicidalAutoloader/autoloader.php
Labels: release:internal

#9868 Update the signature of debug_backtrace
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9878 Glob return type stub
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  stubs/CoreGenericFunctions.phpstub
  tests/CoreStubsTest.php
Labels: release:fix

#9887 readonly does not have write access, therefore is safe as long as the…
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  tests/PropertyTypeInvarianceTest.php
Labels: release:feature

#9877 Sprintf improve return param type validation
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/SprintfReturnTypeProvider.php
  stubs/CoreGenericFunctions.phpstub
  tests/ReturnTypeProvider/SprintfTest.php
Labels: release:feature

#9895 Unmark DateInterval::$invert as read-only
  stubs/CoreGenericClasses.phpstub
Labels: release:fix

#9889 feat: cache.gz
  src/Psalm/Config.php
  src/Psalm/Internal/Cache.php
  src/Psalm/Internal/LanguageServer/Provider/FileReferenceCacheProvider.php
  src/Psalm/Internal/Provider/ClassLikeStorageCacheProvider.php
  src/Psalm/Internal/Provider/FileReferenceCacheProvider.php
  src/Psalm/Internal/Provider/FileStorageCacheProvider.php
  src/Psalm/Internal/Provider/ParserCacheProvider.php
  tests/Internal/Provider/FakeFileReferenceCacheProvider.php
Labels: release:feature

#9904 Sprintf additional validations and bugfix
  src/Psalm/Internal/Provider/ReturnTypeProvider/SprintfReturnTypeProvider.php
  tests/ReturnTypeProvider/SprintfTest.php
Labels: release:fix

#9915 fix CI warnings for findUnusedCode in psalm 6
  src/Psalm/Config.php
  tests/EndToEnd/PsalmEndToEndTest.php
  tests/fixtures/DestructiveAutoloader/psalm.xml
  tests/fixtures/DummyProject/psalm.xml
  tests/fixtures/ModularConfig/psalm.xml
  tests/fixtures/SuicidalAutoloader/psalm.xml
Labels: release:internal

#9916 docblock parser minor performance gain
  src/Psalm/Internal/Analyzer/CommentAnalyzer.php
  src/Psalm/Internal/Scanner/DocblockParser.php
  tests/TypeReconciliation/ConditionalTest.php
Labels: release:internal

#9903 Fixes #9827
  src/Psalm/Internal/Type/TypeCombiner.php
  tests/TypeCombinationTest.php
Labels: release:fix

#9921 set type of __LINE__ to positive int
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ArithmeticOpAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ConstFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/MagicConstAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  src/Psalm/Internal/Analyzer/Statements/UnsetAnalyzer.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayFillReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ImagickPixelColorReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/MinMaxReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/RandReturnTypeProvider.php
  src/Psalm/Type.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  tests/ConstantTest.php
Labels: release:fix

#9920 Add a stub file for Attributes defined by PHP
  src/Psalm/Config.php
  stubs/CoreGenericAttributes.phpstub
  stubs/Php82.phpstub
Labels: release:fix

#9922 Don't update types of the outer scope when in an elseif conditional
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/ElseIfAnalyzer.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
  tests/TypeReconciliation/ConditionalTest.php
Labels: release:fix

#9924 make compressor configurable v2
  config.xsd
  docs/running_psalm/configuration.md
  src/Psalm/Config.php
  src/Psalm/Internal/Cache.php
Labels: release:feature

#9929 improve perfs for switch by not creating reverse assertions against constants
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
Labels: release:internal

#9930 remove StementsVolatileCache for perf reasons
  src/Psalm/Internal/Provider/StatementsProvider.php
  src/Psalm/Internal/Provider/StatementsVolatileCache.php
  src/Psalm/Internal/RuntimeCaches.php
Labels: release:internal

#9857 put config to true to prevent deprecations for new config files
  src/Psalm/Config/Creator.php
  tests/Config/CreatorTest.php
  tests/EndToEnd/PsalmEndToEndTest.php
  tests/fixtures/DummyProjectWithErrors/src/FileWithErrors.php
  tests/fixtures/expected_taint_graph.dot
Labels: release:internal

#9933 Update callmap for ext-mongodb 1.16
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9934 Add call map entries for MongoDB functions
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#9931 Invalidate cached methods when referenced files are deleted
  src/Psalm/Internal/Codebase/Analyzer.php
  src/Psalm/Internal/Provider/FakeFileProvider.php
  tests/Cache/CacheTest.php
  tests/Cache/test_base_dir/src/.gitkeep
Labels: release:feature

#9932 Fix/cache fail silent
  src/Psalm/Internal/Cache.php
  src/Psalm/Internal/Provider/FileReferenceCacheProvider.php
  src/Psalm/Internal/Provider/ParserCacheProvider.php
Labels: release:internal

#9953 `non-empty-list` assertion for iterable
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  tests/AssertAnnotationTest.php
Labels: release:fix

#9955 Invalidate cached methods when referenced class property types change
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Internal/Diff/ClassStatementsDiffer.php
  src/Psalm/Internal/LanguageServer/Provider/FileStorageCacheProvider.php
  src/Psalm/Internal/Provider/FileReferenceProvider.php
  src/Psalm/Internal/Provider/FileStorageCacheProvider.php
  src/Psalm/Internal/Provider/Providers.php
  src/Psalm/IssueBuffer.php
  tests/Cache/CacheTest.php
  tests/FileDiffTest.php
  tests/Internal/Provider/FakeFileReferenceCacheProvider.php
  tests/Internal/Provider/FileStorageInstanceCacheProvider.php
  tests/ProjectCheckerTest.php
Labels: release:feature

#9943 fix PHP 7 sprintf too many arguments false positive
  src/Psalm/Internal/Provider/ReturnTypeProvider/SprintfReturnTypeProvider.php
  stubs/CoreGenericFunctions.phpstub
  tests/ReturnTypeProvider/SprintfTest.php
Labels: release:fix

#9967 Fix the link reference in the doc
  docs/annotating_code/type_syntax/atomic_types.md
Labels: release:docs

#9942 Fix glob CallMap and stub to prevent crash on alpine
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php
  stubs/CoreGenericFunctions.phpstub
  tests/CoreStubsTest.php
Labels: release:fix
