Repository vimeo/psalm, pull requests merged in 2023-07, with the labels that each got.

#9975 Fix sprintf single arg splat array
  src/Psalm/Internal/Provider/ReturnTypeProvider/SprintfReturnTypeProvider.php
  tests/ReturnTypeProvider/SprintfTest.php
Labels: release:fix

#9981 fix mixed replace return types for arrays
  src/Psalm/Config/Creator.php
  src/Psalm/Config/FileFilter.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/StrReplaceReturnTypeProvider.php
  stubs/CoreGenericFunctions.phpstub
  tests/FunctionCallTest.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:feature

#9990 Fixed psalm self test
  src/Psalm/Internal/Cli/Psalm.php
Labels: release:internal

#9964 Fix/phpparser deprecation name parts
  composer.json
  examples/plugins/FunctionCasingChecker.php
  examples/plugins/StringChecker.php
  psalm.xml.dist
  src/Psalm/Internal/Analyzer/CanAlias.php
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/ClassLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/FileAnalyzer.php
  src/Psalm/Internal/Analyzer/NamespaceAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfConditionalAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/SwitchCaseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/WhileAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOpAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/ExistingAtomicStaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ClassConstAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ExpressionIdentifier.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ConstFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/StaticPropertyFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/IncludeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/InstanceofAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/MatchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  src/Psalm/Internal/Diff/FileStatementsDiffer.php
  src/Psalm/Internal/Diff/NamespaceStatementsDiffer.php
  src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php
  src/Psalm/Internal/PhpVisitor/Reflector/ExpressionScanner.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  src/Psalm/Internal/PhpVisitor/Reflector/TypeHintResolver.php
  src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php
  src/Psalm/Internal/Provider/AddRemoveTaints/HtmlFunctionTainter.php
  src/Psalm/Internal/Scanner/PhpStormMetaScanner.php
  stubs/phpparser.phpstub
Labels: release:internal

#9988 Fixed exhuming enums as enums, not as classes
  src/Psalm/Codebase.php
Labels: release:fix

#9970 Missing composer lock should not invalidate cache created with missing composer lock
  src/Psalm/Codebase.php
  src/Psalm/Internal/Cache.php
  src/Psalm/Internal/Provider/ClassLikeStorageCacheProvider.php
  src/Psalm/Internal/Provider/ParserCacheProvider.php
  src/Psalm/Internal/Provider/ProjectCacheProvider.php
Labels: release:fix

#9992 make stubbed constant types configurable with comment
  src/Psalm/Internal/PhpVisitor/Reflector/ExpressionScanner.php
  tests/StubTest.php
  tests/fixtures/stubs/constant_var_comment.phpstub
Labels: release:feature

#9993 no error for printf with only 1 arg
  src/Psalm/Internal/Provider/ReturnTypeProvider/SprintfReturnTypeProvider.php
  tests/ReturnTypeProvider/SprintfTest.php
Labels: release:fix

#9999 offsetExists/Get/Set/Unset types were too generic
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#10014 Fix inference high order function when closure param is omitted
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  tests/CallableTest.php
Labels: release:fix

#10016 Add generic stubs for MongoDB BSON classes
  stubs/extensions/mongodb.phpstub
Labels: release:feature

#10004 Allow comments in types (e.g. in array shapes)
  docs/annotating_code/type_syntax/array_types.md
  src/Psalm/Internal/Analyzer/CommentAnalyzer.php
  tests/AnnotationTest.php
  tests/CommentAnalyzerTest.php
Labels: release:feature

#10034 Fix incorrect positions set in code action edits
  src/Psalm/Internal/LanguageServer/Server/TextDocument.php
Labels: language server, release:fix

#10032 #10030 Fix missing TaintedSql
  stubs/extensions/pdo.phpstub
Labels: release:feature

#10012 Always report UnusedBaseline issues
  src/Psalm/IssueBuffer.php
Labels: release:fix

#10037 Simplify conditions with deep object access
  src/Psalm/Internal/LanguageServer/LanguageClient.php
  src/Psalm/Internal/LanguageServer/LanguageServer.php
  src/Psalm/Internal/LanguageServer/Server/TextDocument.php
Labels: release:internal

#10046 Map special RPC paths
  src/Psalm/Internal/LanguageServer/LanguageServer.php
Labels: language server, release:internal

#10033 Automatic LSP container path mapping
  docs/running_psalm/language_server.md
  src/Psalm/Internal/Cli/LanguageServer.php
  src/Psalm/Internal/LanguageServer/LanguageServer.php
  src/Psalm/Internal/LanguageServer/PathMapper.php
  src/Psalm/Internal/LanguageServer/Server/TextDocument.php
  src/Psalm/Internal/LanguageServer/Server/Workspace.php
  tests/LanguageServer/DiagnosticTest.php
  tests/LanguageServer/PathMapperTest.php
Labels: language server, release:feature

#10028 added GitHub CI for unit tests with PHP 8.2 and 8.3
  .circleci/config.yml
  .github/workflows/ci.yml
  composer.json
  dictionaries/CallMap.php
  dictionaries/CallMap_83_delta.php
  tests/AnnotationTest.php
  tests/DateTimeTest.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
  tests/Traits/ValidCodeAnalysisTestTrait.php
Labels: release:feature

#10050 Modernize LSP progress reporting
  src/Psalm/Internal/LanguageServer/Client/Progress/LegacyProgress.php
  src/Psalm/Internal/LanguageServer/Client/Progress/Progress.php
  src/Psalm/Internal/LanguageServer/Client/Progress/ProgressInterface.php
  src/Psalm/Internal/LanguageServer/LanguageClient.php
  src/Psalm/Internal/LanguageServer/LanguageServer.php
  src/Psalm/Internal/LanguageServer/Server/TextDocument.php
  src/Psalm/Internal/LanguageServer/Server/Workspace.php
  tests/LanguageServer/DiagnosticTest.php
Labels: language server, release:feature

#10055 Add type detection for PDOStatement::fetchAll(PDO::FETCH_CLASS, SomeClass::class)
  src/Psalm/Internal/Provider/ReturnTypeProvider/PdoStatementReturnTypeProvider.php
  tests/MethodCallTest.php
Labels: release:feature

#10024 Switch to amp v3
  .circleci/config.yml
  .github/workflows/build-phar.yml
  .github/workflows/ci.yml
  .github/workflows/windows-ci.yml
  UPGRADING.md
  composer.json
  psalm-baseline.xml
  src/Psalm/Internal/Algebra/FormulaGenerator.php
  src/Psalm/Internal/Analyzer/NamespaceAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php
  src/Psalm/Internal/Codebase/Reflection.php
  src/Psalm/Internal/LanguageServer/Client/Workspace.php
  src/Psalm/Internal/LanguageServer/ClientHandler.php
  src/Psalm/Internal/LanguageServer/LanguageClient.php
  src/Psalm/Internal/LanguageServer/LanguageServer.php
  src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php
  src/Psalm/Internal/LanguageServer/ProtocolStreamWriter.php
  src/Psalm/Internal/LanguageServer/ProtocolWriter.php
  src/Psalm/Internal/LanguageServer/Server/TextDocument.php
  src/Psalm/Internal/LanguageServer/Server/Workspace.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayCombineReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/SprintfReturnTypeProvider.php
  src/Psalm/Type/Reconciler.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
  tests/LanguageServer/DiagnosticTest.php
  tests/LanguageServer/MockProtocolStream.php
  tests/fixtures/DummyProjectWithErrors/composer.json
Labels: release:internal

#10043 Fix scanning of intersection types
  src/Psalm/Internal/Codebase/ClassLikes.php
Labels: release:fix

#10040 Psalm v6
  UPGRADING.md
  psalm-baseline.xml
  src/Psalm/Codebase.php
  src/Psalm/Config.php
  src/Psalm/ErrorBaseline.php
  src/Psalm/Internal/Algebra.php
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php
  src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/ArrayAssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ArithmeticOpAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArrayFunctionArgumentsAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  src/Psalm/Internal/Analyzer/Statements/UnsetAnalyzer.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMapReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMergeReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayPointerAdjustmentReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayReduceReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArraySliceReturnTypeProvider.php
  src/Psalm/Internal/Type/AssertionReconciler.php
  src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php
  src/Psalm/Internal/Type/Comparator/CallableTypeComparator.php
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  src/Psalm/Internal/Type/TypeCombiner.php
  src/Psalm/Internal/Type/TypeExpander.php
  src/Psalm/Plugin/Shepherd.php
  src/Psalm/Storage/FunctionLikeStorage.php
  src/Psalm/Storage/FunctionStorage.php
  src/Psalm/Type/Atomic.php
  src/Psalm/Type/Atomic/GenericTrait.php
  src/Psalm/Type/Atomic/TCallableList.php
  src/Psalm/Type/Atomic/TClassStringMap.php
  src/Psalm/Type/Atomic/TDependentListKey.php
  src/Psalm/Type/Atomic/TKeyOf.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  src/Psalm/Type/Atomic/TList.php
  src/Psalm/Type/Atomic/TNonEmptyList.php
  src/Psalm/Type/Atomic/TValueOf.php
  src/Psalm/Type/Reconciler.php
  src/Psalm/Type/UnionTrait.php
  tests/ErrorBaselineTest.php
  tests/TypeCombinationTest.php
Labels: release:internal

#10039 Fix combination of non-falsy-string and falsy literal
  src/Psalm/Internal/Type/TypeCombiner.php
  tests/TypeCombinationTest.php
Labels: release:fix

#10066 Fix variadic callable type check
  src/Psalm/Internal/Type/Comparator/CallableTypeComparator.php
  tests/CallableTest.php
Labels: release:fix
