Repository vimeo/psalm, pull requests merged in 2023-08, with the labels that each got.

#10071 Allow method-like strings in `referencedFunction`
  src/Psalm/Config/FileFilter.php
  tests/Config/ConfigTest.php
Labels: release:fix

#10068 Check if argument passed to isset() is not a variable
  src/Psalm/Internal/Analyzer/Statements/Expression/IssetAnalyzer.php
Labels: release:feature

#10073 Fixed `DOMDocument::load*` signatures
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
  stubs/extensions/dom.phpstub
Labels: release:fix

#10088 make (s)printf error reporting more correct/literal
  src/Psalm/Internal/Provider/ReturnTypeProvider/SprintfReturnTypeProvider.php
  tests/ReturnTypeProvider/SprintfTest.php
Labels: release:fix

#10049 Fix #9997 dynamic properties on SimpleXmlElement
  psalm-baseline.xml
  src/Psalm/Codebase.php
  src/Psalm/Config.php
  src/Psalm/Config/FileFilter.php
  src/Psalm/Config/IssueHandler.php
  src/Psalm/Config/ProjectFileFilter.php
  src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  src/Psalm/Internal/Codebase/ClassLikes.php
  src/Psalm/Internal/Provider/MethodReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/SimpleXmlElementAsXml.php
  src/Psalm/Type/Atomic.php
  stubs/extensions/simplexml.phpstub
  tests/ArrayAccessTest.php
  tests/PropertyTypeTest.php
  tests/TypeReconciliation/ConditionalTest.php
Labels: release:feature

#10048 Fix #100047
  stubs/extensions/pdo.phpstub
Labels: release:fix

#10104 Fix parameter having `object` type in PHPDoc and only `&` in the method's definition, used with code having an object calling it's method with itself as an argument for mentioned parameter
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php
  tests/MethodCallTest.php
Labels: causes crash, release:fix

#10107 mysqli_field_seek returns true
  dictionaries/CallMap.php
  dictionaries/CallMap_80_delta.php
  dictionaries/CallMap_historical.php
Labels: internal stubs/callmap, release:fix

#10106 Fix bcdiv nullable scale stub
  stubs/CoreGenericFunctions.phpstub
Labels: internal stubs/callmap, release:fix

#10108 Cleanup `test` command and `fixAll` action
  src/Psalm/Internal/LanguageServer/LanguageServer.php
  src/Psalm/Internal/LanguageServer/Server/TextDocument.php
Labels: release:fix

#10109 Correct type for `$enum->name`
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  tests/EnumTest.php
Labels: release:fix, enum

#10093 argv and argc were inconsistent in Context with VariableFetchAnalyzer
  src/Psalm/Context.php
Labels: release:fix

#10110 Fix `hash_pbkdf2` `$options` parameter
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_83_delta.php
Labels: internal stubs/callmap, release:fix

#10112 Forbid faulty `nikic/php-parser` version
  composer.json
Labels: CI, release:fix

#10092 Respect stubs in all cases
  src/Psalm/Internal/Codebase/Functions.php
  tests/StubTest.php
  tests/fixtures/stubs/custom_taint_source.php
  tests/fixtures/stubs/custom_taint_source.phpstub
  tests/fixtures/stubs/define_custom_require_path.php
Labels: release:fix

#10122 `strip_tags()/$allowed_tags` can accept arrays since 7.4
  src/Psalm/Config.php
  stubs/Php74.phpstub
Labels: internal stubs/callmap, release:fix

#10123 Fix crash when assertion array is not a list
  psalm-baseline.xml
  src/Psalm/Type/Reconciler.php
Labels: release:fix

#10129 Nicer PHP version checking
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Internal/CliUtils.php
Labels: release:feature

#9517 Make `TLiteralFloat::$value` and `TLiteralInt::$value` typed
  UPGRADING.md
  src/Psalm/Type/Atomic/TLiteralFloat.php
  src/Psalm/Type/Atomic/TLiteralInt.php
Labels: release:internal

#10134 Fix crash on array access to undefined class
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  tests/ArrayAccessTest.php
Labels: release:fix

#10135 Correct exit code for invalid version format
  src/Psalm/Internal/CliUtils.php
Labels: release:fix

#10138 Added more gc_status return fields
  dictionaries/CallMap.php
  dictionaries/CallMap_83_delta.php
Labels: internal stubs/callmap, release:fix

#10136 Extract the list of impure functions into its own dictionary
  dictionaries/ImpureFunctionsList.php
  src/Psalm/Internal/Codebase/Functions.php
  src/Psalm/Internal/Codebase/ImpureFunctionsList.php
Labels: release:internal

#10145 Show success message and type stats with GHA formatter
  src/Psalm/IssueBuffer.php
Labels: release:feature

#10149 docs: A semicolon expected
  docs/annotating_code/type_syntax/array_types.md
Labels: release:docs

#10150 Assertion enhancements regarding `value-of` in combination with backed enums
  src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Type.php
  tests/AssertAnnotationTest.php
  tests/EnumTest.php
Labels: release:fix

#10151 `strrchr()`: `$before_needle` parameter
  dictionaries/CallMap.php
  dictionaries/CallMap_83_delta.php
Labels: internal stubs/callmap, release:fix

#10155 Update `mysqli` stub
  stubs/extensions/mysqli.phpstub
Labels: internal stubs/callmap, release:fix

#10154 New sinks for TaintedCallable #10117
  stubs/Reflection.phpstub
  tests/TaintTest.php
Labels: release:feature

#10159 Fix crash on property access to undefined property on a class with a missing dependncy
  src/Psalm/Storage/ClassLikeStorage.php
  tests/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzerTest.php
Labels: release:fix

#10157 Properly inherit assertions from parents or implemented faces
  src/Psalm/Codebase.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/ExistingAtomicStaticCallAnalyzer.php
  src/Psalm/Internal/Codebase/AssertionsFromInheritanceResolver.php
  tests/AssertAnnotationTest.php
Labels: release:feature

#10156 Prevent infinite-loop when resolving type-aliases
  src/Psalm/Internal/Type/TypeParser.php
Labels: release:fix

#10163 Xpath injection #10162
  UPGRADING.md
  config.xsd
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/TaintedXpath.md
  src/Psalm/Internal/Codebase/TaintFlowGraph.php
  src/Psalm/Issue/TaintedXpath.php
  src/Psalm/Type/TaintKind.php
  src/Psalm/Type/TaintKindGroup.php
  stubs/extensions/dom.phpstub
  stubs/extensions/simplexml.phpstub
  tests/TaintTest.php
Labels: release:feature

#10165 Backed enum value changed to Atomic instead of scalar int or strings
  UPGRADING.md
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  src/Psalm/Internal/Codebase/ConstantTypeResolver.php
  src/Psalm/Internal/Codebase/Methods.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/GetObjectVarsReturnTypeProvider.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Storage/EnumCaseStorage.php
  src/Psalm/Type.php
  src/Psalm/Type/Atomic/TValueOf.php
  tests/EnumTest.php
Labels: release:feature

#10169 InheritorViolation was only being triggered on grand-childen classes
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/ClassLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/InterfaceAnalyzer.php
  tests/ClassTest.php
Labels: release:fix
