Repository vimeo/psalm, pull requests merged in 2023-12, with the labels that each got.

#10443 Fix return type of DOMXPath::query
  stubs/extensions/dom.phpstub
Labels: release:fix

#10434 Use correct file path while adding unused suppressions for virtual __…
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
Labels: release:fix

#10422 Restore support for null coalesce on match expressions
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/CoalesceAnalyzer.php
  tests/MatchTest.php
Labels: release:fix

#10429 Fix static magic method pureness not being inherited from traits
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  tests/PureAnnotationTest.php
Labels: release:fix

#10441 Fix POSIX only detection of absolute paths
  src/Psalm/Config/FileFilter.php
Labels: release:fix

#10431 Emit UnusedPsalmSuppress issues for suppressed issues already removed
  psalm-baseline.xml
  psalm.xml.dist
  src/Psalm/IssueBuffer.php
  tests/CodebaseTest.php
Labels: release:fix

#10419 Implement by-ref closure use analysis
  psalm-baseline.xml
  src/Psalm/Internal/Analyzer/ClosureAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  src/Psalm/Internal/Diff/ClassStatementsDiffer.php
  src/Psalm/Internal/LanguageServer/LanguageServer.php
  tests/CallableTest.php
  tests/ClosureTest.php
  tests/ReferenceConstraintTest.php
  tests/UnusedVariableTest.php
Labels: release:feature

#10450 Fix shaped array class string key combination
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/ArrayAssignmentAnalyzer.php
  src/Psalm/Internal/Type/TypeCombination.php
  src/Psalm/Internal/Type/TypeCombiner.php
  src/Psalm/Type/Reconciler.php
  tests/ArrayAssignmentTest.php
Labels: release:fix

#10463 fix composer scripts running with inconsistent php versions
  composer.json
Labels: release:internal

#10452 Fix remaining POSIX-only absolute path detection
  src/Psalm/Config.php
  src/Psalm/Config/FileFilter.php
  src/Psalm/Internal/Analyzer/Statements/Expression/IncludeAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/ExpressionScanner.php
Labels: release:fix

#10459 dont combine empty string with numeric-string
  src/Psalm/Internal/Type/TypeCombiner.php
  tests/TypeCombinationTest.php
Labels: release:fix

#10472 Fix iteration over weakmaps
  stubs/CoreGenericClasses.phpstub
Labels: release:fix

#10467 Fixed docblock spacing in `@psalm-internal` documentation example
  docs/annotating_code/supported_annotations.md
Labels: documentation

#10456 update fidry/cpu-core-counter dependency
  composer.json
Labels: release:internal

#10417 TaintedExtract
  UPGRADING.md
  config.xsd
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/TaintedExtract.md
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  src/Psalm/Internal/Codebase/TaintFlowGraph.php
  src/Psalm/Issue/TaintedExtract.php
  src/Psalm/Type/TaintKind.php
  src/Psalm/Type/TaintKindGroup.php
  stubs/CoreGenericFunctions.phpstub
  tests/TaintTest.php
Labels: release:feature

#10475 fix psalm v4 hardcoded in tests
  tests/Config/ConfigTest.php
  tests/Config/PluginTest.php
  tests/ProjectCheckerTest.php
  tests/ReportOutputTest.php
  tests/StubTest.php
  tests/TestCase.php
Labels: release:internal

#10477 Fix type not equal when parent
  src/Psalm/Type/Atomic/TArray.php
  src/Psalm/Type/Atomic/TClassStringMap.php
  src/Psalm/Type/Atomic/TGenericObject.php
  src/Psalm/Type/Atomic/TIterable.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  src/Psalm/Type/Atomic/TList.php
  src/Psalm/Type/Atomic/TObjectWithProperties.php
Labels: release:fix

#10480 Use same parameter names in stubs
  stubs/CoreGenericClasses.phpstub
  stubs/CoreGenericIterators.phpstub
  stubs/SPL.phpstub
Labels: release:fix

#10454 fix false positive ArgumentTypeCoercion for callback param
  src/Psalm/Internal/Type/Comparator/ArrayTypeComparator.php
  tests/CallableTest.php
Labels: release:fix

#10481 report error for invalid array key type
  src/Psalm/Internal/Type/TypeParser.php
  tests/AnnotationTest.php
  tests/ArrayAssignmentTest.php
  tests/ArrayKeysTest.php
  tests/KeyOfArrayTest.php
Labels: release:fix

#10489 Fix Uncaught RuntimeException: PHP Error: Uninitialized string offset 0 when $pattern is empty
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
Labels: release:fix

#10493 Add support for Override attribute
  stubs/CoreGenericAttributes.phpstub
  tests/AttributeTest.php
Labels: release:feature

#10497 strtok always returns a non-empty-string when it does not return false
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix
