Repository vimeo/psalm, pull requests merged in 2024-03, with the labels that each got.

#10764 Fix version comparison for `@since`
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
Labels: release:fix

#10769 Since annotations outside phpstub should not infer php version
  src/Psalm/Config.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php
  tests/AnnotationTest.php
Labels: release:fix

#10765 Avoid duplicating code for RiskyTruthyFalsyComparison
  src/Psalm/Internal/Analyzer/Statements/Block/IfConditionalAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BooleanNotAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/EmptyAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php
Labels: release:internal

#10772 Initial support for named parameters for callables
  src/Psalm/Internal/Type/ParseTree/CallableParamTree.php
  src/Psalm/Internal/Type/ParseTreeCreator.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Storage/FunctionLikeParameter.php
  tests/CallableTest.php
Labels: release:feature

#10775 Update `master` from `5.x`
  psalm-baseline.xml
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfConditionalAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BooleanNotAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ClassConstAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/EmptyAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  src/Psalm/Internal/Type/ParseTree/CallableParamTree.php
  src/Psalm/Internal/Type/ParseTreeCreator.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Storage/FunctionLikeParameter.php
  tests/AnnotationTest.php
  tests/ArrayAccessTest.php
  tests/CallableTest.php
  tests/ConstantTest.php
  tests/FunctionCallTest.php
  tests/GeneratorTest.php
  tests/Loop/ForeachTest.php
Labels: release:internal

#10778 Backport `WeakMap` iterator fix from `master`
  stubs/CoreGenericClasses.phpstub
Labels: internal stubs/callmap, CI, release:fix

#10776 fix PHP 8 tests running with wrong --php-version=/phpVersion= if not explicitly specified
  tests/CoreStubsTest.php
  tests/Traits/InvalidCodeAnalysisTestTrait.php
  tests/Traits/ValidCodeAnalysisTestTrait.php
Labels: release:internal

#10779 Namespace anonymous classes
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  tests/InternalAnnotationTest.php
Labels: release:fix

#10781 Update CallMap for sqlsrv_connect and sqlsrv_errors to match reflection
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#10801 CS fix
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfConditionalAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/ElseIfAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/AndAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/OrAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/TernaryAnalyzer.php
  src/Psalm/Internal/Cli/LanguageServer.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Cli/Psalter.php
  src/Psalm/Internal/Cli/Refactor.php
  src/Psalm/Internal/CliUtils.php
  src/Psalm/Internal/Codebase/ClassLikes.php
  src/Psalm/Internal/Fork/PsalmRestarter.php
  src/Psalm/Internal/LanguageServer/LanguageClient.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
  src/Psalm/Internal/Provider/FileReferenceProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayFilterReturnTypeProvider.php
  src/Psalm/Internal/Type/TypeExpander.php
  src/Psalm/IssueBuffer.php
  src/Psalm/Type/Atomic.php
  src/Psalm/Type/UnionTrait.php
  tests/DocumentationTest.php
  tests/LanguageServer/Message.php
Labels: release:internal

#10802 `$resource` parameter of `mkdir()` is nullable since PHP 7.3
  dictionaries/CallMap.php
  dictionaries/CallMap_73_delta.php
Labels: internal stubs/callmap, release:fix

#10803 Update `master` from `5.x`
  dictionaries/CallMap.php
  dictionaries/CallMap_73_delta.php
  dictionaries/CallMap_historical.php
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfConditionalAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElse/ElseIfAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/AndAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/OrAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/TernaryAnalyzer.php
  src/Psalm/Internal/Cli/LanguageServer.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Cli/Psalter.php
  src/Psalm/Internal/Cli/Refactor.php
  src/Psalm/Internal/CliUtils.php
  src/Psalm/Internal/Codebase/ClassLikes.php
  src/Psalm/Internal/Fork/PsalmRestarter.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
  src/Psalm/Internal/Provider/FileReferenceProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayFilterReturnTypeProvider.php
  src/Psalm/Internal/Type/TypeExpander.php
  src/Psalm/IssueBuffer.php
  src/Psalm/Type/Atomic.php
  src/Psalm/Type/UnionTrait.php
  stubs/CoreGenericClasses.phpstub
  tests/CoreStubsTest.php
  tests/DocumentationTest.php
  tests/InternalAnnotationTest.php
  tests/LanguageServer/Message.php
  tests/Traits/InvalidCodeAnalysisTestTrait.php
  tests/Traits/ValidCodeAnalysisTestTrait.php
Labels: release:internal

#10800 Use wider class-string when combining class strings with intersections
  src/Psalm/Internal/Type/TypeCombiner.php
  tests/TypeCombinationTest.php
  tests/TypeParseTest.php
Labels: release:fix

#10804 Forbid named arguments for ArrayAcccess methods
  stubs/CoreGenericClasses.phpstub
  tests/ArrayAccessTest.php
Labels: internal stubs/callmap, release:fix

#10806 Don't crash on invalid templates
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  tests/Template/ClassTemplateTest.php
Labels: release:fix

#10812 Fixed analysis of existing static methods if the `__callStatic()` method exists
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  tests/AssertAnnotationTest.php
Labels: release:fix

#10842 fix tests running with other than called PHP binary if called with a non-default PHP binary
  tests/EndToEnd/PsalmEndToEndTest.php
  tests/EndToEnd/PsalmRunnerTrait.php
Labels: release:internal

#10843 Explicitly set value in config to fix warning in tests
  tests/fixtures/DestructiveAutoloader/psalm.xml
  tests/fixtures/DummyProject/psalm.xml
  tests/fixtures/ModularConfig/psalm.xml
  tests/fixtures/SuicidalAutoloader/autoloader.php
  tests/fixtures/SuicidalAutoloader/psalm.xml
Labels: release:internal

#10832 [PHP 8.4] Fixes for implicit nullability deprecation
  src/Psalm/Codebase.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/IssueData.php
  src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ArithmeticOpAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/HighOrderFunctionArgInfo.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  src/Psalm/Internal/Codebase/Analyzer.php
  src/Psalm/Internal/Codebase/ConstantTypeResolver.php
  src/Psalm/Internal/Codebase/Methods.php
  src/Psalm/Internal/Provider/FakeFileProvider.php
  src/Psalm/Internal/Provider/FileProvider.php
  src/Psalm/Internal/Type/ParseTree/Value.php
  src/Psalm/Plugin/DynamicTemplateProvider.php
  src/Psalm/Plugin/EventHandler/Event/AfterMethodCallAnalysisEvent.php
  src/Psalm/Storage/FunctionLikeStorage.php
  src/Psalm/Type/Atomic.php
Labels: release:internal

#10829 Allow specifying flags to Codebase::isTypeContainedByType
  src/Psalm/Codebase.php
Labels: release:feature

#10805 Allow more callable types as subtypes of `callable`
  src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php
  src/Psalm/Internal/Type/Comparator/CallableTypeComparator.php
  src/Psalm/Type/Atomic/TCallable.php
  src/Psalm/Type/Atomic/TCallableArray.php
  src/Psalm/Type/Atomic/TCallableInterface.php
  src/Psalm/Type/Atomic/TCallableKeyedArray.php
  src/Psalm/Type/Atomic/TCallableList.php
  src/Psalm/Type/Atomic/TCallableObject.php
  src/Psalm/Type/Atomic/TCallableString.php
  tests/CallableTest.php
  tests/TypeComparatorTest.php
Labels: release:feature

#10838 Report `parent` being used in callable context when the class does not extend anything
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  tests/CallableTest.php
Labels: release:feature

#10824 Report error for additional deprecated arg types in PHP 8.1/8.3
  dictionaries/CallMap.php
  dictionaries/CallMap_81_delta.php
  dictionaries/CallMap_83_delta.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:feature

#10822 report error for single param name mismatch too since named args can even be used then
  src/Psalm/Internal/Analyzer/MethodComparator.php
  tests/MethodCallTest.php
  tests/MethodSignatureTest.php
  tests/UnusedCodeTest.php
Labels: release:fix

#10815 add support for named arguments for filter_var and filter_input
  src/Psalm/Internal/Provider/ReturnTypeProvider/FilterInputReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/FilterVarReturnTypeProvider.php
  tests/FunctionCallTest.php
Labels: release:fix

#10821 Enforce parameter names for consistent constructors
  docs/running_psalm/issues/ConstructorSignatureMismatch.md
  src/Psalm/Internal/Analyzer/MethodComparator.php
  tests/ClassTest.php
Labels: release:feature

#10756 When inside isset, make array fetch result nullable
  psalm-baseline.xml
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  tests/ArrayAssignmentTest.php
  tests/ArrayFunctionCallTest.php
  tests/TypeReconciliation/EmptyTest.php
  tests/TypeReconciliation/RedundantConditionTest.php
Labels: release:fix

#10817 Promoted properties missing in extended __construct should report PropertyNotSetInConstructor
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticCallAnalyzer.php
  tests/PropertyTypeTest.php
Labels: release:fix

#10839 Add misc missing errors for invalid callable methods
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  tests/CallableTest.php
Labels: release:feature

#10847 Updating signature of `getmxrr()`
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#10814 Improve string-int juggle consistency in array keys and display for int-like strings in type
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/ArrayAssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ExpressionIdentifier.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  src/Psalm/Type/Reconciler.php
  tests/ArrayKeysTest.php
  tests/TypeReconciliation/RedundantConditionTest.php
Labels: release:fix

#10856 Fix storage not available in thread for intersection doc types
  src/Psalm/Internal/Type/TypeParser.php
Labels: release:fix

#10858 Don't emit MissingOverrideAttribute for implicit Stringable implementations
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  tests/OverrideTest.php
Labels: release:fix

#10859 Specify array return type of session_get_cookie_params
  dictionaries/CallMap.php
  dictionaries/CallMap_73_delta.php
  dictionaries/CallMap_historical.php
Labels: internal stubs/callmap, release:fix

#10866 document that @psalm-internal works for namespace + class too
  docs/annotating_code/supported_annotations.md
  tests/InternalAnnotationTest.php
Labels: release:docs
