Repository vimeo/psalm, pull requests merged in 2024-01, with the labels that each got.

#10524 Fix #10512: Fixed SessionUpdateTimestampHandlerInterface parameter names
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: release:fix

#10532 Reduce memory consumption of caching and parallel processing without igbinary
  src/Psalm/Aliases.php
  src/Psalm/CodeLocation.php
  src/Psalm/Internal/MethodIdentifier.php
  src/Psalm/Storage/Assertion.php
  src/Psalm/Storage/AttributeArg.php
  src/Psalm/Storage/AttributeStorage.php
  src/Psalm/Storage/ClassConstantStorage.php
  src/Psalm/Storage/ClassLikeStorage.php
  src/Psalm/Storage/EnumCaseStorage.php
  src/Psalm/Storage/FileStorage.php
  src/Psalm/Storage/FunctionLikeParameter.php
  src/Psalm/Storage/FunctionLikeStorage.php
  src/Psalm/Storage/Possibilities.php
  src/Psalm/Storage/PropertyStorage.php
  src/Psalm/Storage/UnserializeMemoryUsageSuppressionTrait.php
  src/Psalm/Type/Atomic.php
  src/Psalm/Type/Union.php
Labels: release:feature

#10483 Fix GH-10465
  src/Psalm/Config.php
Labels: release:fix

#10498 filter_input & filter_var return type more specific
  config.xsd
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  docs/running_psalm/issues.md
  docs/running_psalm/issues/RedundantFlag.md
  src/Psalm/Internal/Provider/FunctionReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/FilterInputReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/FilterUtils.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/FilterVarReturnTypeProvider.php
  src/Psalm/Issue/RedundantFlag.php
  tests/FunctionCallTest.php
  tests/TypeReconciliation/ConditionalTest.php
Labels: release:feature

#10500 Fix callable without args not handled correctly
  src/Psalm/Codebase.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/HighOrderFunctionArgHandler.php
  src/Psalm/Internal/Codebase/Functions.php
  tests/FunctionCallTest.php
Labels: release:fix

#10505 Add error when using readonly property in by-ref arg
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  tests/ImmutableAnnotationTest.php
Labels: release:fix

#10508 fix: #10496 #10503
  src/Psalm/Internal/Type/TypeParser.php
  tests/AnnotationTest.php
Labels: release:fix

#10518 Deprecated Template Classes are not ignored by @psalm-suppress DeprecatedClass
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Storage/ClassLikeStorage.php
  tests/DeprecatedAnnotationTest.php
Labels: release:fix

#10536 Implement __set method in SimpleXMLElement stub
  stubs/extensions/simplexml.phpstub
  tests/PropertyTypeTest.php
Labels: release:fix

#10543 Fix mb_get_info can return null - CI failing bc of reflection
  dictionaries/CallMap.php
  dictionaries/CallMap_82_delta.php
Labels: release:fix

#10545 make basename & dirname return types more specific
  src/Psalm/Internal/Provider/ReturnTypeProvider/BasenameReturnTypeProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/DirnameReturnTypeProvider.php
  tests/ReturnTypeProvider/BasenameTest.php
  tests/ReturnTypeProvider/DirnameTest.php
Labels: release:fix

#10544 add support for extract to set variables for keyed arrays and respect EXTR_SKIP
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NamedFunctionCallHandler.php
  tests/FunctionCallTest.php
Labels: release:fix

#10542 remove redundat directory separator which caused "//" in path not found errors
  src/Psalm/Config.php
Labels: release:fix

#10499 Fix empty literal string becomes non-empty-string
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php
  src/Psalm/Type.php
  tests/BinaryOperationTest.php
  tests/TypeCombinationTest.php
Labels: release:fix

#10502 report error for non-strict or empty comparison on truthy+falsy union
  config.xsd
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/RiskyTruthyFalsyComparison.md
  psalm-baseline.xml
  src/Psalm/Internal/Analyzer/Statements/Block/IfConditionalAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BooleanNotAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/EmptyAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  src/Psalm/Issue/RiskyTruthyFalsyComparison.php
  src/Psalm/PluginFileExtensionsSocket.php
  tests/ArrayAccessTest.php
  tests/FunctionCallTest.php
  tests/ImmutableAnnotationTest.php
  tests/JsonOutputTest.php
  tests/Loop/DoTest.php
  tests/Loop/WhileTest.php
  tests/MethodCallTest.php
  tests/MethodSignatureTest.php
  tests/PropertyTypeTest.php
  tests/ReturnTypeTest.php
  tests/SwitchTypeTest.php
  tests/Template/ClassTemplateTest.php
  tests/TypeReconciliation/AssignmentInConditionalTest.php
  tests/TypeReconciliation/ConditionalTest.php
  tests/TypeReconciliation/EmptyTest.php
  tests/TypeReconciliation/IssetTest.php
  tests/TypeReconciliation/RedundantConditionTest.php
  tests/TypeReconciliation/TypeAlgebraTest.php
  tests/UnusedVariableTest.php
Labels: release:feature

#10564 Do not use JIT on windows
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Fork/PsalmRestarter.php
Labels: release:internal

#10565 Let disable-extension also disable zend extensions
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Fork/PsalmRestarter.php
Labels: release:internal

#10568 Fix template, conditional array keys
  src/Psalm/Internal/Type/TypeParser.php
  tests/ArrayKeysTest.php
Labels: release:fix

#10569 Merge 5.x
  src/Psalm/Internal/Type/TypeParser.php
  tests/ArrayKeysTest.php
Labels: release:internal

#10572 Fix #10552
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php
  tests/MethodCallTest.php
Labels: release:fix

#10576 Merge 5.x
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php
  tests/MethodCallTest.php
Labels: release:internal

#10574 Unit test improvements for php-parser 5
  tests/ClassTest.php
  tests/FileUpdates/TemporaryUpdateTest.php
  tests/PropertyTypeTest.php
Labels: release:fix

#10586 Fix template replacement edge case
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  tests/Template/FunctionTemplateTest.php
Labels: release:fix

#10593 Baseline update
  psalm-baseline.xml
Labels: release:internal

#10588 Partial revert "Fix auto completion by partial property or method"
  src/Psalm/Codebase.php
  src/Psalm/Internal/LanguageServer/Server/TextDocument.php
  tests/LanguageServer/CompletionTest.php
Labels: release:fix

#10607 [LSP] Add issue type in description
  src/Psalm/Internal/LanguageServer/LanguageServer.php
Labels: language server, release:fix

#10610 Remove unnecessary null type from `initialized_methods` Context property
  src/Psalm/Context.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/ExistingAtomicStaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php
  tests/Config/ConfigFileTest.php
Labels: release:internal

#10597 Update master from 5.x
  .github/workflows/bcc.yml
  .github/workflows/build-phar.yml
  .github/workflows/ci.yml
  .github/workflows/windows-ci.yml
  psalm-baseline.xml
  src/Psalm/Codebase.php
  src/Psalm/Internal/Analyzer/Statements/Expression/EncapsulatedStringAnalyzer.php
  src/Psalm/Internal/LanguageServer/Server/TextDocument.php
  src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php
  tests/ClassTest.php
  tests/FileUpdates/TemporaryUpdateTest.php
  tests/LanguageServer/CompletionTest.php
  tests/PropertyTypeTest.php
  tests/Template/FunctionTemplateTest.php
Labels: release:internal

#10601 Do not validate callable arguments in lenient contexts
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  tests/FunctionCallTest.php
Labels: release:fix

#10600 `readgzfile()` is impure
  dictionaries/ImpureFunctionsList.php
Labels: release:fix

#10599 Allow properties on intersections with enum interfaces
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  tests/EnumTest.php
Labels: release:fix

#10598 `key_exists()` is an alias for `array_key_exists()`
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  tests/TypeReconciliation/ArrayKeyExistsTest.php
Labels: release:fix

#10614 Fix language server running with `opcache.save_comments=0`
  src/Psalm/Internal/Fork/PsalmRestarter.php
Labels: language server, release:fix

#10615 Report `MissingConstructor` for natively typed mixed properties
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  tests/PropertyTypeTest.php
Labels: release:fix

#10605 Minor php-parser tweaks
  src/Psalm/CodeLocation.php
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php
Labels: release:internal

#10618 Update master from 5.x
  dictionaries/ImpureFunctionsList.php
  src/Psalm/CodeLocation.php
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/UnusedAssignmentRemover.php
  src/Psalm/Internal/Fork/PsalmRestarter.php
  src/Psalm/Internal/LanguageServer/LanguageServer.php
  src/Psalm/Internal/PhpVisitor/CheckTrivialExprVisitor.php
  src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php
  src/Psalm/Internal/Type/TypeExpander.php
  tests/EnumTest.php
  tests/FunctionCallTest.php
  tests/PropertyTypeTest.php
  tests/TypeAnnotationTest.php
  tests/TypeReconciliation/ArrayKeyExistsTest.php
Labels: release:internal

#10619 Fix ownerDocument type in dom-ext classes
  dictionaries/PropertyMap.php
  stubs/extensions/dom.phpstub
  tests/CoreStubsTest.php
  tests/PropertyTypeTest.php
Labels: release:fix

#10621 Fix numeric scalar validate filter var input return type wrong
  src/Psalm/Internal/Provider/ReturnTypeProvider/FilterUtils.php
  tests/FunctionCallTest.php
Labels: release:fix

#10623 Allow inline comments in typedef shapes
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  tests/TypeAnnotationTest.php
Labels: release:feature
