Repository vimeo/psalm, pull requests merged in 2024-02, with the labels that each got.

#10628 Fix baseline loading for path specified on the command line
  src/Psalm/Internal/Cli/Psalm.php
Labels: release:fix

#10625 allow typedef imports from any kind of classlike
  src/Psalm/Internal/Analyzer/FileAnalyzer.php
  src/Psalm/Internal/Type/TypeExpander.php
  tests/TypeAnnotationTest.php
Labels: release:feature

#10634 Allow enum cases to be global constants
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  tests/EnumTest.php
Labels: release:feature

#10633 Stable baseline
  psalm-baseline.xml
  src/Psalm/ErrorBaseline.php
Labels: release:fix

#10647 Drop unused local composer repo
  composer.json
Labels: release:internal

#10639 Allow sebastian/diff v6
  composer.json
Labels: release:fix

#10637 CallMap: Adjust return type for `inotify_add_watch()` to `int|false`
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: internal stubs/callmap, release:fix

#10648 Fix check-type when using builtin types from within a namespace
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  tests/AssertAnnotationTest.php
  tests/CheckTypeTest.php
Labels: release:fix

#10644 New InvalidOverride issue for Override attribute
  config.xsd
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/InvalidOverride.md
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Issue/InvalidOverride.php
  tests/AttributeTest.php
  tests/DocumentationTest.php
Labels: release:feature

#10649 Clarify that Pull request labels failure is to be resolved by maintainers
  .github/workflows/pr-labels.yml
Labels: release:internal

#10654 Do not add `callable` as a native property type
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Type/Atomic/TClosure.php
  tests/FileManipulation/MissingPropertyTypeTest.php
Labels: psalter, release:fix

#10603 Fix unstable `hasFullyQualified(Interface|Enum)()`
  src/Psalm/Codebase.php
  src/Psalm/Internal/Codebase/ClassLikes.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
  tests/TypeReconciliation/ReconcilerTest.php
Labels: release:internal

#10656 Update master from 5.x
  .github/workflows/pr-labels.yml
  composer.json
  config.xsd
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  dictionaries/PropertyMap.php
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/InvalidOverride.md
  psalm-baseline.xml
  src/Psalm/ErrorBaseline.php
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/FileAnalyzer.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/FilterUtils.php
  src/Psalm/Internal/Type/TypeExpander.php
  src/Psalm/Issue/InvalidOverride.php
  src/Psalm/Type/Atomic/TClosure.php
  stubs/extensions/dom.phpstub
  tests/AssertAnnotationTest.php
  tests/AttributeTest.php
  tests/CheckTypeTest.php
  tests/CoreStubsTest.php
  tests/DocumentationTest.php
  tests/FileManipulation/MissingPropertyTypeTest.php
  tests/FunctionCallTest.php
  tests/PropertyTypeTest.php
  tests/TypeAnnotationTest.php
Labels: release:internal

#10629 Analyze dynamic names for static property and const fetches
  src/Psalm/Internal/Analyzer/Statements/Expression/ClassConstAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/StaticPropertyFetchAnalyzer.php
  tests/ConstantTest.php
  tests/UnusedVariableTest.php
Labels: release:feature

#10651 New MissingOverrideAttribute issue
  config.xsd
  docs/running_psalm/configuration.md
  docs/running_psalm/error_levels.md
  docs/running_psalm/issues.md
  docs/running_psalm/issues/MissingOverrideAttribute.md
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Issue/MissingOverrideAttribute.php
  tests/AttributeTest.php
  tests/DocumentationTest.php
  tests/OverrideTest.php
Labels: release:feature

#10630 Fix additional places where base_dir was broken due to missing separator
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  psalm.xml.dist
  src/Psalm/Config.php
  src/Psalm/Internal/Cli/LanguageServer.php
  src/Psalm/Internal/Cli/Plugin.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Cli/Psalter.php
  src/Psalm/Internal/Cli/Refactor.php
  src/Psalm/Internal/CliUtils.php
  src/Psalm/Internal/PluginManager/Command/DisableCommand.php
  src/Psalm/Internal/PluginManager/Command/EnableCommand.php
  src/Psalm/Internal/PluginManager/Command/ShowCommand.php
  src/Psalm/Internal/PluginManager/PluginListFactory.php
  tests/Cache/CacheTest.php
  tests/EndToEnd/PsalmEndToEndTest.php
  tests/StubTest.php
  tests/TestConfig.php
Labels: release:fix

#10655 Late binding of enum cases
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  src/Psalm/Internal/Codebase/ConstantTypeResolver.php
  src/Psalm/Internal/Codebase/Methods.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/GetObjectVarsReturnTypeProvider.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Storage/EnumCaseStorage.php
  src/Psalm/Type/Atomic/TValueOf.php
  tests/EnumTest.php
Labels: release:fix, enum

#10661 Flag `stdClass::__construct()` calls that have arguments
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php
  tests/MethodCallTest.php
Labels: release:feature

#10665 Fix parsing magic method annotations
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeDocblockParser.php
  tests/ClassLikeDocblockParserTest.php
Labels: release:fix

#10666 Strip callmap prefixes from parameter names
  src/Psalm/Internal/Codebase/InternalCallMapHandler.php
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
  tests/MethodSignatureTest.php
Labels: release:fix

#10671 Revert partial mistakenly pushed fix
  dictionaries/CallMap.php
Labels: release:internal

#10676 Narrow `ord()` return type to `int<0,255>`
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
Labels: internal stubs/callmap, release:fix

#10677 Template union object incorrect assertions
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  tests/Template/FunctionTemplateTest.php
Labels: release:fix

#10679 Don't show backtrace in `InvalidDocblock` issue message
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
  tests/AssertAnnotationTest.php
Labels: release:fix

#10091 Improve Reflection stubs
  dictionaries/CallMap.php
  dictionaries/CallMap_historical.php
  stubs/Php80.phpstub
  stubs/Reflection.phpstub
Labels: release:feature

#10686 Forbid constructors from returning any values
  psalm-baseline.xml
  src/Psalm/Internal/Analyzer/Statements/ReturnAnalyzer.php
  tests/ReturnTypeTest.php
Labels: release:feature

#10688 Suppress scanning output in CI
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Progress/LongProgress.php
Labels: release:fix

#10675 Prevent mixed|null
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  tests/ArgTest.php
Labels: release:fix

#10691 Report first class callables generated for unknown static methods
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  tests/MethodCallTest.php
Labels: release:feature

#10695 Fix composer warnings
  .github/workflows/ci.yml
  src/Psalm/Node/Stmt/VirtualDeclareItem.php
  src/Psalm/Node/VirtualUseItem.php
Labels: release:internal

#10690 Process `@psalm-this-out` on `__construct()` as well
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php
  tests/ThisOutTest.php
Labels: release:feature

#10694 Suppress unused config suppression detection when running in partial or cache mode
  src/Psalm/Codebase.php
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/IssueBuffer.php
Labels: release:fix

#10693 Update master from 5.x
  psalm-baseline.xml
  src/Psalm/Internal/Analyzer/Statements/ReturnAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  tests/ArgTest.php
  tests/ReturnTypeTest.php
Labels: release:internal

#10699 Report invalid number of arguments for psalm-taint-*
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php
  tests/Template/ConditionalReturnTypeTest.php
Labels: release:feature

#10709 Improve randomizer stubs
  stubs/extensions/random.phpstub
Labels: release:fix

#10713 Improve parsing of `@psalm-type`
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  tests/AnnotationTest.php
  tests/TypeAnnotationTest.php
Labels: release:fix

#10714 Update master from 5.x
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php
  stubs/extensions/random.phpstub
  tests/AnnotationTest.php
  tests/MethodCallTest.php
  tests/Template/ConditionalReturnTypeTest.php
  tests/ThisOutTest.php
  tests/TypeAnnotationTest.php
Labels: release:internal

#10704 Fix detecting magic static methods
  src/Psalm/Internal/Analyzer/MethodAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodVisibilityAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  src/Psalm/Internal/Codebase/Methods.php
  tests/MagicMethodAnnotationTest.php
  tests/MagicPropertyTest.php
  tests/MethodCallTest.php
  tests/MethodSignatureTest.php
  tests/MixinAnnotationTest.php
  tests/TestCase.php
  tests/Traits/InvalidCodeAnalysisWithIssuesTestTrait.php
Labels: release:fix

#10726 Update PHP 8.2 stubs to include `SensitiveParameterValue`
  stubs/Php82.phpstub
Labels: internal stubs/callmap, release:feature

#10728 Add list of statements to BeforeFileAnalysisEvent
  src/Psalm/Internal/Analyzer/FileAnalyzer.php
  src/Psalm/Plugin/EventHandler/Event/BeforeFileAnalysisEvent.php
Labels: release:feature

#10722 Fix non-empty-lowercase-string handling with literal non-lowercase strings
  src/Psalm/Internal/Type/TypeCombiner.php
  tests/TypeCombinationTest.php
Labels: release:fix

#10733 Fix RiskyTruthyFalsyComparison irrelevant errors when there is no explicit truthy/falsy type
  docs/running_psalm/issues/RiskyTruthyFalsyComparison.md
  src/Psalm/Internal/Analyzer/Statements/Block/IfConditionalAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BooleanNotAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/EmptyAnalyzer.php
  tests/TypeReconciliation/ConditionalTest.php
Labels: release:fix

#10734 Allow `Override` attribute to be used in pure contexts
  stubs/CoreGenericAttributes.phpstub
  tests/OverrideTest.php
Labels: release:fix

#10720 Catch missing classlike exceptions during scanning
  src/Psalm/Type.php
  tests/NativeIntersectionsTest.php
Labels: release:fix

#10746 Use TaintKind/TaintKindGroup constants instead of string values
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
  src/Psalm/Internal/Provider/AddRemoveTaints/HtmlFunctionTainter.php
  src/Psalm/Type/TaintKindGroup.php
Labels: release:internal

#10749 Skip symlink test on Windows
  tests/Config/ConfigTest.php
Labels: release:internal, Windows

#10748 Fix loading stubs from phar file on Windows
  src/Psalm/Config.php
Labels: release:fix, Windows

#10750 Update master from 5.x
  docs/running_psalm/issues/RiskyTruthyFalsyComparison.md
  psalm-baseline.xml
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/FileAnalyzer.php
  src/Psalm/Internal/Analyzer/MethodAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfConditionalAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOpAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BooleanNotAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodVisibilityAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/EmptyAnalyzer.php
  src/Psalm/Internal/Codebase/Methods.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php
  src/Psalm/Internal/Provider/AddRemoveTaints/HtmlFunctionTainter.php
  src/Psalm/Internal/Type/TypeCombiner.php
  src/Psalm/Plugin/EventHandler/Event/BeforeFileAnalysisEvent.php
  src/Psalm/Type.php
  src/Psalm/Type/TaintKindGroup.php
  stubs/CoreGenericAttributes.phpstub
  stubs/Php82.phpstub
  tests/Config/ConfigTest.php
  tests/MagicMethodAnnotationTest.php
  tests/MagicPropertyTest.php
  tests/MethodCallTest.php
  tests/MethodSignatureTest.php
  tests/MixinAnnotationTest.php
  tests/NativeIntersectionsTest.php
  tests/OverrideTest.php
  tests/TaintTest.php
  tests/TestCase.php
  tests/Traits/InvalidCodeAnalysisWithIssuesTestTrait.php
  tests/TypeCombinationTest.php
  tests/TypeReconciliation/ConditionalTest.php
Labels: release:internal

#10738 Fix a false flag issue with InvalidConstantAssignmentValue
  src/Psalm/Internal/Analyzer/Statements/Expression/ClassConstAnalyzer.php
  tests/ConstantTest.php
Labels: release:fix

#10697 Forbid iterating over generators with non-nullable `send()`
  src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php
  tests/GeneratorTest.php
  tests/Loop/ForeachTest.php
Labels: release:feature

#10752 Set inside_isset false when analyzing ArrayDimFetch index
  src/Psalm/Internal/Analyzer/Statements/Block/IfConditionalAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  tests/ArrayAccessTest.php
Labels: release:fix

#10753 Set inside_isset = false when analyzing arguments
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  tests/FunctionCallTest.php
Labels: release:fix

#10760 Fix PHP notice - crash on invalid taint-escape
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php
  tests/AnnotationTest.php
Labels: causes crash, release:fix
