Repository vimeo/psalm, pull requests merged in 2024-05, with the labels that each got.

#10883 Update PHP 8.2 Call map delta with refined types for string comparison functions
  dictionaries/CallMap.php
  dictionaries/CallMap_82_delta.php
Labels: release:fix

#10953 Fix-GH-10933-And-GH-10951
  src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php
  tests/MissingClassConstTypeTest.php
Labels: release:fix

#10954 Update dealing_with_code_issues.md: Minor
  docs/running_psalm/dealing_with_code_issues.md
Labels: release:docs

#10934 redis: add possible types for `Redis#auth` method
  stubs/extensions/redis.phpstub
Labels: internal stubs/callmap, release:fix

#10935 Avoid false positive about array which are non-callable
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  tests/CallableTest.php
Labels: release:fix

#10930 Fix literal-string|non-empty-literal-string
  src/Psalm/Internal/Type/TypeCombiner.php
  tests/TypeCombinationTest.php
Labels: release:fix

#10941 Casting int-range should keep literals
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  tests/CastTest.php
Labels: release:feature
