Repository vimeo/psalm, pull requests merged in 2025-02, with the labels that each got.

#11228 Parse uppercase-string
  src/Psalm/Type/Atomic.php
Labels: release:fix

#11237 Add new psalm-review tool
  .github/workflows/build-phar.yml
  composer.json
  docs/running_psalm/command_line_usage.md
  psalm-review
  psalm.xml.dist
  src/Psalm/Internal/Cli/Review.php
Labels: release:feature

#11234 Fix standalone block analysis
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
Labels: release:fix

#11238 Fix indirect magic property usage
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/InstancePropertyAssignmentAnalyzer.php
  tests/MagicPropertyTest.php
  tests/MixinAnnotationTest.php
Labels: release:fix

#11240 Allow iterating over generator with void send() type
  src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php
  tests/Loop/ForeachTest.php
Labels: release:fix

#11239 Fix closure typehints in arrays
  psalm-baseline.xml
  src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php
  tests/ClosureTest.php
Labels: release:fix

#11245 Add forbiddenConstants config
  config.xsd
  docs/running_psalm/configuration.md
  docs/running_psalm/issues/ForbiddenCode.md
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ConstFetchAnalyzer.php
  tests/ForbiddenCodeTest.php
Labels: release:feature

#11247 Add array function parameter type providers
  bin/gen_callmap.php
  dictionaries/CallMap_70.php
  dictionaries/CallMap_71.php
  dictionaries/CallMap_72.php
  dictionaries/CallMap_73.php
  dictionaries/CallMap_74.php
  dictionaries/CallMap_80.php
  dictionaries/CallMap_81.php
  dictionaries/CallMap_82.php
  dictionaries/CallMap_83.php
  dictionaries/CallMap_84.php
  dictionaries/override/CallMap.php
  dictionaries/override/CallMap_80_delta.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CastAnalyzer.php
  src/Psalm/Internal/Codebase/ConstantTypeResolver.php
  src/Psalm/Internal/Provider/FunctionParamsProvider.php
  src/Psalm/Internal/Provider/ParamsProvider/ArrayFilterParamsProvider.php
  src/Psalm/Internal/Provider/ParamsProvider/ArrayUArrayParamsProvider.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayFilterReturnTypeProvider.php
  src/Psalm/Internal/Type/SimpleAssertionReconciler.php
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  src/Psalm/Type.php
  src/Psalm/Type/MutableUnion.php
  tests/ArrayFunctionCallTest.php
Labels: release:fix

#11250 Disable uv to avoid fork() issues
  src/Psalm/Internal/Cli/LanguageServer.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Cli/Psalter.php
Labels: release:fix

#11243 Fix issue with insufficient shared memory for interned strings buffer
  src/Psalm/Internal/Fork/PsalmRestarter.php
Labels: release:fix

#11256 Simplify redis return types
  bin/gen_callmap.php
  dictionaries/CallMap_80.php
  dictionaries/CallMap_81.php
  dictionaries/CallMap_82.php
  dictionaries/CallMap_83.php
  dictionaries/CallMap_84.php
  dictionaries/autogen/CallMap_80.php
  dictionaries/autogen/CallMap_81.php
  dictionaries/autogen/CallMap_82.php
  dictionaries/autogen/CallMap_83.php
  dictionaries/autogen/CallMap_84.php
  dictionaries/override/CallMap.php
  dictionaries/override/CallMap_80_delta.php
Labels: release:fix

#11257 Improve performance and accuracy of types comparison
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/FilterUtils.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/SprintfReturnTypeProvider.php
  src/Psalm/Internal/Type/AssertionReconciler.php
  src/Psalm/Internal/Type/Comparator/ScalarTypeComparator.php
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
  src/Psalm/Internal/Type/TypeCombiner.php
  src/Psalm/Type/UnionTrait.php
  tests/TypeCombinationTest.php
Labels: release:fix

#11258 Fix TemplateInferredTypeReplacer
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArrayFunctionArgumentsAnalyzer.php
  src/Psalm/Internal/Type/ArrayType.php
  src/Psalm/Internal/Type/TemplateInferredTypeReplacer.php
  src/Psalm/Type.php
  tests/Template/ConditionalReturnTypeTest.php
Labels: release:fix

#11260 Allow sebastian/diff v7
  composer.json
Labels: release:internal

#11264 Fix deep scanning of files light-scanned in main thread
  src/Psalm/Internal/Provider/ClassLikeStorageProvider.php
Labels: release:fix

#11267 Template inference bugfix
  src/Psalm/Internal/Type/TypeExpander.php
  tests/Template/FunctionTemplateTest.php
Labels: release:fix

#11259 Add allFunctionsGlobal and allConstantsGlobal options
  config.xsd
  docs/running_psalm/configuration.md
  psalm-baseline.xml
  psalm.xml.dist
  src/Psalm/Codebase.php
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ConstFetchAnalyzer.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Codebase/Functions.php
  src/Psalm/Internal/Codebase/Scanner.php
  src/Psalm/Internal/Fork/ShutdownScannerTask.php
  src/Psalm/Internal/PhpVisitor/Reflector/ExpressionScanner.php
  src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php
  src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php
  tests/ReportOutputTest.php
  tests/TypeParseTest.php
  tests/fixtures/stubs/conditional_constant_define_inferred.phpstub
Labels: release:feature

#11270 Force usage of latest patch version to avoid JIT bugs
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Internal/CliUtils.php
Labels: release:fix

#11271 Specify minimum PHP patch release in composer.json as well
  composer.json
Labels: release:fix

#11273 Bump `symfony/filesystem`
  composer.json
Labels: release:fix

#11269 Fix type assertion for Arithemtic addition and subtraction
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ArithmeticOpAnalyzer.php
  tests/BinaryOperationTest.php
Labels: release:fix

#11276 Improve stub docs
  bin/update-property-map.php
  docs/running_psalm/configuration.md
  docs/running_psalm/issues/UndefinedClass.md
  docs/running_psalm/issues/UndefinedConstant.md
  docs/running_psalm/issues/UndefinedFunction.md
  stubs/CoreGenericFunctions.phpstub
Labels: release:docs

#11255 Fix config error in LSP
  psalm-baseline.xml
  src/Psalm/Internal/LanguageServer/Client/Workspace.php
  src/Psalm/Internal/LanguageServer/LanguageClient.php
Labels: release:fix

#11278 Reorganize tools
  .circleci/config.yml
  .github/workflows/build-phar.yml
  .github/workflows/ci.yml
  .github/workflows/windows-ci.yml
  bin/ci/build-phar.sh
  bin/ci/composer-require-checker-config.json
  bin/ci/generate_testsuites.php
  bin/ci/github-deploy-phar.sh
  bin/ci/improve_class_alias.php
  bin/ci/phar.psalm.xml
  bin/ci/test-with-real-projects.sh
  bin/ci/tests-github-actions.sh
  bin/docs/generate_issues_list_doc.php
  bin/docs/generate_levels_doc.php
  bin/docs/max_used_shortcode.php
  bin/stubs/Dockerfile_7.0
  bin/stubs/Dockerfile_7.1
  bin/stubs/Dockerfile_7.2
  bin/stubs/Dockerfile_7.3
  bin/stubs/Dockerfile_7.4
  bin/stubs/Dockerfile_8.0
  bin/stubs/Dockerfile_8.1
  bin/stubs/Dockerfile_8.2
  bin/stubs/Dockerfile_8.3
  bin/stubs/Dockerfile_8.4
  bin/stubs/README.md
  bin/stubs/gen_base_callmap.php
  bin/stubs/gen_callmap.php
  bin/stubs/gen_callmap.sh
  bin/stubs/gen_callmap_utils.php
  bin/stubs/php.ini
  bin/stubs/update-property-map.php
  bin/stubs/update_signaturemap_from_other_tool.php
  composer.json
  src/Psalm/Internal/VersionUtils.php
  tests/DocumentationTest.php
Labels: release:internal

#10206 fix: add taint source on plugin-added taints
  docs/security_analysis/custom_taint_sources.md
  examples/plugins/TaintActiveRecords.php
  src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/ArrayAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/InstancePropertyAssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOpAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallReturnTypeFetcher.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallReturnTypeFetcher.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/EncapsulatedStringAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/EvalAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/AtomicPropertyFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Expression/IncludeAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/ReturnAnalyzer.php
  src/Psalm/Internal/DataFlow/TaintSource.php
  tests/Config/Plugin/EventHandler/AddTaints/AddTaintsInterfaceTest.php
  tests/Config/Plugin/EventHandler/AddTaints/TaintBadDataPlugin.php
  tests/Config/Plugin/EventHandler/RemoveTaints/RemoveAllTaintsPlugin.php
  tests/Config/Plugin/EventHandler/RemoveTaints/RemoveTaintsInterfaceTest.php
  tests/Config/PluginTest.php
Labels: release:fix

#11286 handle instanceof $this
  examples/plugins/TaintActiveRecords.php
  psalm-baseline.xml
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  tests/Config/Plugin/EventHandler/AddTaints/AddTaintsInterfaceTest.php
  tests/Config/Plugin/EventHandler/AddTaints/TaintBadDataPlugin.php
  tests/Config/Plugin/EventHandler/RemoveTaints/RemoveAllTaintsPlugin.php
  tests/Config/Plugin/EventHandler/RemoveTaints/RemoveTaintsInterfaceTest.php
  tests/TypeReconciliation/ConditionalTest.php
Labels: release:fix

#11277 Fix key type in PossiblyUndefinedStringArrayOffset.md
  docs/running_psalm/issues/PossiblyUndefinedStringArrayOffset.md
Labels: release:docs

#11157 Add missing reset of context inside_general_use
  src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/InstancePropertyFetchAnalyzer.php
Labels: release:fix

#11156 Fix object properties lose type
  src/Psalm/Type/Reconciler.php
  tests/ReturnTypeProvider/GetObjectVarsTest.php
Labels: release:fix

#11212 Fix false positives for UnusedIssueHandlerSuppression
  src/Psalm/IssueBuffer.php
Labels: release:fix

#11291 Object property types
  src/Psalm/Type/Reconciler.php
  tests/ReturnTypeProvider/GetObjectVarsTest.php
Labels: release:fix

#11155 Allow running generate_testsuites.php from a different dir
  bin/ci/generate_testsuites.php
Labels: release:feature

#11153 Fix some more tests when running phpunit with args
  tests/AsyncTestCase.php
  tests/Cache/CacheTest.php
  tests/Config/ConfigFileTest.php
  tests/Config/ConfigTest.php
  tests/Config/PluginTest.php
  tests/ForbiddenCodeTest.php
  tests/ProjectCheckerTest.php
  tests/StubTest.php
  tests/VariadicTest.php
Labels: release:fix

#11152 Fix type of property-get with coalesce
  src/Psalm/Internal/Analyzer/Statements/Expression/IssetAnalyzer.php
  tests/MagicPropertyTest.php
Labels: release:fix

#11293 Fix condition on lowercase-string
  src/Psalm/Internal/Type/Comparator/ScalarTypeComparator.php
  src/Psalm/Type.php
  tests/Template/ConditionalReturnTypeTest.php
Labels: release:fix

#11296 Types in lazy objects
  src/Psalm/Config.php
  stubs/Php84.phpstub
  tests/Php84Test.php
Labels: release:feature

#11134 Fix parameter name in SplObjectStorage
  stubs/SPL.phpstub
Labels: release:fix

#11111 Fix empty compact report if baseline file is used
  src/Psalm/Report/CompactReport.php
Labels: release:fix

#11297 Expose Progress instance to plugins
  src/Psalm/Codebase.php
  src/Psalm/PluginRegistrationSocket.php
Labels: release:internal

#11283 Enable more features by default
  config.xsd
  docs/running_psalm/configuration.md
  docs/running_psalm/issues/RedundantIdentityWithTrue.md
  docs/running_psalm/issues/UndefinedMagicPropertyAssignment.md
  docs/running_psalm/issues/UndefinedMagicPropertyFetch.md
  psalm-baseline.xml
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/Statements/Expression/AssertionFinder.php
  src/Psalm/Storage/ClassLikeStorage.php
  tests/BinaryOperationTest.php
  tests/ClassLoadOrderTest.php
  tests/ClassTest.php
  tests/InternalAnnotationTest.php
  tests/IssueSuppressionTest.php
  tests/MagicPropertyTest.php
  tests/MethodCallTest.php
  tests/PropertyTypeTest.php
  tests/Template/ClassTemplateExtendsTest.php
  tests/Template/ClassTemplateTest.php
  tests/TestConfig.php
  tests/UnusedCodeTest.php
Labels: release:feature

#11300 Require jsonmapper v5
  composer.json
Labels: release:internal

#11302 Add longScanWarning config
  config.xsd
  docs/running_psalm/configuration.md
  src/Psalm/Config.php
  src/Psalm/Internal/Codebase/Analyzer.php
  src/Psalm/Internal/Codebase/Scanner.php
  src/Psalm/Internal/Fork/Pool.php
Labels: release:feature

#11136 Die when PHP doc not found in update-property-map.php
  bin/stubs/update-property-map.php
Labels: release:fix

#11309 Preload all classes before forking (+5% performance)
  composer.json
  phpcs.xml
  psalm-baseline.xml
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Cli/Psalter.php
  src/Psalm/Internal/Preloader.php
  src/Psalm/Internal/PreloaderList.php
Labels: release:feature

#11313 Do not throw exceptions on deprecation errors while autoloading deps
  bin/stubs/gen_preloader.php
  src/Psalm/Internal/CliUtils.php
Labels: release:fix

#10782 Deduplicate loop analysis
  psalm-baseline.xml
  src/Psalm/Context.php
  src/Psalm/Internal/Analyzer/Statements/Block/DoAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/ForAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/SwitchCaseAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/Block/WhileAnalyzer.php
  src/Psalm/Internal/Scope/LoopScope.php
Labels: release:fix

#11317 Log PHP version earlier
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Internal/Cli/Psalm.php
Labels: release:internal

#11323 Fix phar generation
  scoper.inc.php
  vendor-bin/box/composer.json
Labels: release:fix

#10566 Reproducible builds (fixes #10446)
  box.json.dist
  composer.json
  scoper.inc.php
  vendor-bin/box/composer.json
  vendor-bin/box/composer.lock
Labels: release:internal

#11328 Fixes PHP Error: Undefined array key 1
  src/Psalm/Internal/Analyzer/ClassAnalyzer.php
Labels: release:fix

#11329 Allow integer and string concatenation
  psalm-baseline.xml
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php
  tests/BinaryOperationTest.php
Labels: release:fix

#11150 Fix array_reverse type for `list{0: int, 1?: int}` etc.
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayReverseReturnTypeProvider.php
  tests/ArrayFunctionCallTest.php
Labels: release:fix

#11332 Update configuration.md: Adding `--config=` cli parameter
  docs/running_psalm/configuration.md
Labels: release:docs

#11334 Improve closure template inference
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php
  src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayReverseReturnTypeProvider.php
  tests/ArrayFunctionCallTest.php
  tests/ClosureTest.php
Labels: release:fix

#11335 Allow RoundingMode as param to round
  bin/stubs/gen_callmap.sh
  dictionaries/CallMap_84.php
  dictionaries/override/CallMap.php
  dictionaries/override/CallMap_84_delta.php
Labels: release:fix

#11339 Improve debugging of PHP bugs
  src/Psalm/Internal/Fork/ForkContext.php
Labels: release:internal

#11341 Fix Could not locate trait statement errors
  src/Psalm/Internal/PhpVisitor/TraitFinder.php
Labels: release:fix

#11345 Fix polyfill version range
  composer.json
Labels: release:fix
