Repository vimeo/psalm, pull requests merged in 2025-01, with the labels that each got.

#10963 Fix typos
  docs/contributing/adding_issues.md
  docs/contributing/philosophy.md
  docs/running_psalm/installation.md
  docs/running_psalm/issues/DirectConstructorCall.md
  docs/running_psalm/issues/InvalidOverride.md
  docs/running_psalm/issues/MissingConstructor.md
  docs/running_psalm/issues/RedundantPropertyInitializationCheck.md
  docs/running_psalm/plugins/authoring_plugins.md
  src/Psalm/Context.php
  src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php
  src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/ExecutionEnvironment/BuildInfoCollector.php
  src/Psalm/Internal/LanguageServer/Server/Workspace.php
  src/Psalm/Internal/Type/AssertionReconciler.php
  src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php
  src/Psalm/Internal/Type/NegatedAssertionReconciler.php
  src/Psalm/Internal/Type/TypeParser.php
  src/Psalm/Type/Atomic.php
  src/Psalm/Type/Atomic/TKeyedArray.php
  src/Psalm/Type/Atomic/TPropertiesOf.php
  stubs/extensions/amqp.phpstub
  stubs/extensions/redis.phpstub
  tests/AnnotationTest.php
  tests/ArrayAccessTest.php
  tests/ArrayFunctionCallTest.php
  tests/AssertAnnotationTest.php
  tests/CallableTest.php
  tests/ClassTest.php
  tests/ClosureTest.php
  tests/ConstantTest.php
  tests/DeprecatedAnnotationTest.php
  tests/ErrorBaselineTest.php
  tests/InterfaceTest.php
  tests/IssueBufferTest.php
  tests/Loop/ForeachTest.php
  tests/Loop/WhileTest.php
  tests/MagicMethodAnnotationTest.php
  tests/MethodSignatureTest.php
  tests/PropertyTypeTest.php
  tests/ReadonlyPropertyTest.php
  tests/Template/ClassTemplateExtendsTest.php
  tests/Template/ClassTemplateTest.php
  tests/Template/ConditionalReturnTypeTest.php
  tests/Template/FunctionTemplateAssertTest.php
  tests/TypeAnnotationTest.php
  tests/TypeParseTest.php
  tests/TypeReconciliation/ArrayKeyExistsTest.php
  tests/TypeReconciliation/ConditionalTest.php
  tests/TypeReconciliation/ReconcilerTest.php
  tests/UnusedVariableTest.php
Labels: release:typo

#10928 Add support for PHP 8.4
  .github/workflows/ci.yml
  composer.json
  psalm-baseline.xml
  tests/Internal/Codebase/InternalCallMapHandlerTest.php
Labels: release:internal

#11219 Refactor Pool for much more efficient multithreaded parallelism
  composer.json
  config.xsd
  docs/contributing/editing_callmaps.md
  docs/running_psalm/configuration.md
  psalm-baseline.xml
  src/Psalm/Config.php
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Cli/Psalter.php
  src/Psalm/Internal/Cli/Refactor.php
  src/Psalm/Internal/CliUtils.php
  src/Psalm/Internal/Codebase/Analyzer.php
  src/Psalm/Internal/Codebase/Scanner.php
  src/Psalm/Internal/Fork/AnalyzerTask.php
  src/Psalm/Internal/Fork/ForkContext.php
  src/Psalm/Internal/Fork/InitAnalyzerTask.php
  src/Psalm/Internal/Fork/InitScannerTask.php
  src/Psalm/Internal/Fork/Pool.php
  src/Psalm/Internal/Fork/ScannerTask.php
  src/Psalm/Internal/Fork/ShutdownAnalyzerTask.php
  src/Psalm/Internal/Fork/ShutdownScannerTask.php
  src/Psalm/Internal/LanguageServer/LanguageServer.php
  src/Psalm/Internal/Provider/ClassLikeStorageProvider.php
  src/Psalm/Internal/Provider/FileStorageProvider.php
  src/Psalm/Internal/Scanner/ParsedDocblock.php
  src/Psalm/IssueBuffer.php
  tests/FileUpdates/TemporaryUpdateTest.php
  tests/Internal/Codebase/MethodGetCompletionItemsForClassishThingTest.php
  tests/LanguageServer/CompletionTest.php
  tests/LanguageServer/DiagnosticTest.php
  tests/LanguageServer/FileMapTest.php
  tests/LanguageServer/SymbolLookupTest.php
  tests/fixtures/DummyProjectWithErrors/diff_composer.lock
Labels: release:fix

#11221 Fix language server
  src/Psalm/Internal/LanguageServer/Server/Workspace.php
Labels: release:fix

#11222 Improve default opcache options
  src/Psalm/Internal/Fork/PsalmRestarter.php
Labels: release:internal

#11225 Log files being processed for too long
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Fork/ForkContext.php
  src/Psalm/Internal/Fork/IgbinarySerializer.php
  src/Psalm/Internal/Fork/Pool.php
Labels: release:feature

#11231 Periodic logging for long processing
  src/Psalm/Internal/Fork/Pool.php
Labels: release:feature

#11232 Fix storage should not be null errors
  src/Psalm/Internal/Provider/ClassLikeStorageProvider.php
Labels: release:fix

#11233 Avoid further issues caused by duplicate class declarations
  src/Psalm/Internal/Analyzer/Statements/Expression/ClassConstAnalyzer.php
Labels: release:fix
