Repository vimeo/psalm, pull requests merged in 2025-03, with the labels that each got.

#11348 Small performance improvement
  src/Psalm/Progress/DefaultProgress.php
Labels: release:internal

#11351 Improve idn_to_* signatures for 8.4
  dictionaries/CallMap_84.php
  dictionaries/override/CallMap.php
  dictionaries/override/CallMap_84_delta.php
Labels: release:fix

#11349 More detailed progress for taint graph resolution
  UPGRADING.md
  src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Codebase/Analyzer.php
  src/Psalm/Internal/Codebase/TaintFlowGraph.php
  src/Psalm/Internal/LanguageServer/Progress.php
  src/Psalm/Internal/Preloader.php
  src/Psalm/Progress/DebugProgress.php
  src/Psalm/Progress/DefaultProgress.php
  src/Psalm/Progress/LongProgress.php
  src/Psalm/Progress/Phase.php
  src/Psalm/Progress/Progress.php
  src/Psalm/Progress/VoidProgress.php
  tests/AsyncTestCase.php
  tests/TestCase.php
Labels: release:feature

#11354 push original callable when creating callable-object in order to keep return type
  src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php
  tests/CallableTest.php
Labels: release:fix

#11307 Add docker image
  .github/workflows/build-docker.yml
  bin/ci/build-docker.php
  bin/docker/Dockerfile
  bin/docker/deepbind.patch
  bin/docker/docker-php-ext-configure
  bin/docker/docker-php-ext-enable
  bin/docker/docker-php-ext-install
  bin/docker/docker-php-source
  bin/docker/entrypoint.sh
  bin/docker/php.ini
  docs/running_psalm/installation.md
  docs/running_psalm/issues/MissingOverrideAttribute.md
Labels: release:feature

#11366 Hotfix #11363
  src/Psalm/Internal/Provider/ReturnTypeProvider/FilterInputReturnTypeProvider.php
Labels: release:fix

#11367 Bump docker image to 8.4.5
  bin/docker/Dockerfile
Labels: release:internal

#11364 Allow concatenation between (string|int) and similar types
  psalm-baseline.xml
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php
  src/Psalm/Type/UnionTrait.php
  tests/BinaryOperationTest.php
Labels: release:fix

#11369 Backport #11364 to 6.x
  psalm-baseline.xml
  src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/ConcatAnalyzer.php
  src/Psalm/Type/UnionTrait.php
  tests/BinaryOperationTest.php
Labels: release:fix

#11371 Merge multiple docblocks for statements
  src/Psalm/Internal/Analyzer/StatementsAnalyzer.php
  tests/TypeReconciliation/TypeTest.php
Labels: release:fix

#11374 Show progress when merging thread results
  src/Psalm/Internal/Codebase/Analyzer.php
  src/Psalm/Progress/DebugProgress.php
  src/Psalm/Progress/DefaultProgress.php
  src/Psalm/Progress/LongProgress.php
  src/Psalm/Progress/Phase.php
Labels: release:feature

#11380 Add forceJit and noCache configuration keys
  config.xsd
  docs/running_psalm/configuration.md
  psalm.xml.dist
  src/Psalm/Config.php
  src/Psalm/Internal/Cli/Psalm.php
  src/Psalm/Internal/Cli/Psalter.php
Labels: release:feature

#11383 Add rank to SARIF report
  src/Psalm/Report/SarifReport.php
Labels: release:feature
